// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#pragma once

/// @file api.hpp
/// @brief Typed client for every Kalshi Predictions REST operation.

#include "kalshi/error.hpp"
#include "kalshi/http_client.hpp"
#include "kalshi/models.hpp"
#include "kalshi/rate_limit.hpp"

#include <memory>
#include <string_view>

namespace kalshi {

/// Client for the Kalshi Predictions REST API. Each method maps to one
/// operation in Kalshi's OpenAPI document, named after its operationId.
///
/// Failures come back as `Error`: `InvalidRequest` for a request the SDK
/// rejects before sending (or HTTP 400/409/422), `AuthenticationError`,
/// `NotFound`, `RateLimited`, `ServerError`, `NetworkError`, or `ParseError`.
/// `Error::api_code` carries Kalshi's machine-readable code when it sends one.
class KalshiClient {
public:
	/// Uses a libcurl client. It signs requests when constructed with a Signer.
	explicit KalshiClient(HttpClient client);
	/// Uses any transport, such as RetryingTransport or a test double.
	explicit KalshiClient(std::shared_ptr<const HttpTransport> transport);
	~KalshiClient();

	KalshiClient(KalshiClient&&) noexcept;
	KalshiClient& operator=(KalshiClient&&) noexcept;
	KalshiClient(const KalshiClient&) = delete;
	KalshiClient& operator=(const KalshiClient&) = delete;

	[[nodiscard]] const HttpTransport& transport() const noexcept;

	// ----- account -----------------------------------------------------------

	/// Get Account API Limits
	/// `GET /account/limits`
	[[nodiscard]] Result<GetAccountApiLimitsResponse> get_account_api_limits();

	/// Upgrade Account API Usage Level
	/// `POST /account/api_usage_level/upgrade`
	[[nodiscard]] Result<void> upgrade_account_api_usage_level();

	/// Get Account API Usage Level Volume Progress
	/// `GET /account/api_usage_level/volume_progress`
	[[nodiscard]] Result<std::vector<AccountApiUsageLevelVolumeProgress>>
	get_account_api_usage_level_volume_progress();

	/// List Non-Default Endpoint Costs
	/// `GET /account/endpoint_costs`
	[[nodiscard]] Result<GetAccountEndpointCostsResponse> get_account_endpoint_costs();

	// ----- api-keys ----------------------------------------------------------

	/// Get API Keys
	/// `GET /api_keys`
	[[nodiscard]] Result<GetApiKeysResponse> get_api_keys(const GetApiKeysParams& params = {});

	/// Create API Key
	/// `POST /api_keys`
	[[nodiscard]] Result<CreateApiKeyResponse> create_api_key(const CreateApiKeyRequest& body);

	/// Generate API Key
	/// `POST /api_keys/generate`
	[[nodiscard]] Result<GenerateApiKeyResponse>
	generate_api_key(const GenerateApiKeyRequest& body);

	/// Delete API Key
	/// `DELETE /api_keys/{api_key}`
	[[nodiscard]] Result<void> delete_api_key(std::string_view api_key);

	// ----- communications ----------------------------------------------------

	/// Get Communications ID
	/// `GET /communications/id`
	[[nodiscard]] Result<std::string> get_communications_id();

	/// Get Block Trade Proposals
	/// `GET /communications/block-trade-proposals`
	[[nodiscard]] Result<GetBlockTradeProposalsResponse>
	get_block_trade_proposals(const GetBlockTradeProposalsParams& params = {});

	/// Propose Block Trade
	/// `POST /communications/block-trade-proposals`
	[[nodiscard]] Result<std::string> propose_block_trade(const ProposeBlockTradeRequest& body);

	/// Accept Block Trade Proposal
	/// `POST /communications/block-trade-proposals/{block_trade_proposal_id}/accept`
	[[nodiscard]] Result<void>
	accept_block_trade_proposal(std::string_view block_trade_proposal_id,
								const AcceptBlockTradeProposalRequest& body);

	/// Get RFQs
	/// `GET /communications/rfqs`
	[[nodiscard]] Result<GetRFQsResponse> get_rfqs(const GetRfqsParams& params = {});

	/// Create RFQ
	/// `POST /communications/rfqs`
	[[nodiscard]] Result<std::string> create_rfq(const CreateRFQRequest& body);

	/// Get RFQ
	/// `GET /communications/rfqs/{rfq_id}`
	[[nodiscard]] Result<RFQ> get_rfq(std::string_view rfq_id);

	/// Delete RFQ
	/// `DELETE /communications/rfqs/{rfq_id}`
	[[nodiscard]] Result<void> delete_rfq(std::string_view rfq_id);

	/// Get RFQ Quote
	/// `GET /communications/rfqs/{rfq_id}/quotes/{quote_id}`
	[[nodiscard]] Result<Quote> get_rfq_quote(std::string_view rfq_id, std::string_view quote_id);

	/// Delete RFQ Quote
	/// `DELETE /communications/rfqs/{rfq_id}/quotes/{quote_id}`
	[[nodiscard]] Result<void> delete_rfq_quote(std::string_view rfq_id, std::string_view quote_id);

	/// Accept RFQ Quote
	/// `PUT /communications/rfqs/{rfq_id}/quotes/{quote_id}/accept`
	[[nodiscard]] Result<void> accept_rfq_quote(std::string_view rfq_id, std::string_view quote_id,
												const AcceptQuoteRequest& body);

	/// Confirm RFQ Quote
	/// `PUT /communications/rfqs/{rfq_id}/quotes/{quote_id}/confirm`
	[[nodiscard]] Result<void> confirm_rfq_quote(std::string_view rfq_id,
												 std::string_view quote_id);

	/// Get Quotes
	/// `GET /communications/quotes`
	[[nodiscard]] Result<GetQuotesResponse> get_quotes(const GetQuotesParams& params = {});

	/// Create Quote
	/// `POST /communications/quotes`
	[[nodiscard]] Result<std::string> create_quote(const CreateQuoteRequest& body);

	/// Get Quote
	/// `GET /communications/quotes/{quote_id}`
	[[deprecated("deprecated by Kalshi")]] [[nodiscard]] Result<Quote>
	get_quote(std::string_view quote_id);

	/// Delete Quote
	/// `DELETE /communications/quotes/{quote_id}`
	[[deprecated("deprecated by Kalshi")]] [[nodiscard]] Result<void>
	delete_quote(std::string_view quote_id);

	/// Accept Quote
	/// `PUT /communications/quotes/{quote_id}/accept`
	[[deprecated("deprecated by Kalshi")]] [[nodiscard]] Result<void>
	accept_quote(std::string_view quote_id, const AcceptQuoteRequest& body);

	/// Confirm Quote
	/// `PUT /communications/quotes/{quote_id}/confirm`
	[[deprecated("deprecated by Kalshi")]] [[nodiscard]] Result<void>
	confirm_quote(std::string_view quote_id);

	// ----- events ------------------------------------------------------------

	/// Get Event Candlesticks
	/// `GET /series/{series_ticker}/events/{ticker}/candlesticks`
	[[nodiscard]] Result<GetEventCandlesticksResponse>
	get_market_candlesticks_by_event(std::string_view series_ticker, std::string_view ticker,
									 const GetMarketCandlesticksByEventParams& params);

	/// Get Events
	/// `GET /events`
	[[nodiscard]] Result<GetEventsResponse> get_events(const GetEventsParams& params = {});

	/// Get Multivariate Events
	/// `GET /events/multivariate`
	[[nodiscard]] Result<GetMultivariateEventsResponse>
	get_multivariate_events(const GetMultivariateEventsParams& params = {});

	/// Get Event Fee Changes
	/// `GET /events/fee_changes`
	[[nodiscard]] Result<GetEventFeeChangesResponse>
	get_event_fee_changes(const GetEventFeeChangesParams& params = {});

	/// Get Event
	/// `GET /events/{event_ticker}`
	[[nodiscard]] Result<GetEventResponse> get_event(std::string_view event_ticker,
													 const GetEventParams& params = {});

	/// Get Event Metadata
	/// `GET /events/{event_ticker}/metadata`
	[[nodiscard]] Result<GetEventMetadataResponse>
	get_event_metadata(std::string_view event_ticker);

	/// Get Event Forecast Percentile History
	/// `GET /series/{series_ticker}/events/{ticker}/forecast_percentile_history`
	[[nodiscard]] Result<std::vector<ForecastPercentilesPoint>>
	get_event_forecast_percentiles_history(std::string_view series_ticker, std::string_view ticker,
										   const GetEventForecastPercentilesHistoryParams& params);

	// ----- exchange ----------------------------------------------------------

	/// Get Exchange Status
	/// `GET /exchange/status`
	[[nodiscard]] Result<ExchangeStatus> get_exchange_status();

	/// Get Series Fee Changes
	/// `GET /series/fee_changes`
	[[nodiscard]] Result<std::vector<SeriesFeeChange>>
	get_series_fee_changes(const GetSeriesFeeChangesParams& params = {});

	/// Get Exchange Schedule
	/// `GET /exchange/schedule`
	[[nodiscard]] Result<Schedule> get_exchange_schedule();

	/// Get User Data Timestamp
	/// `GET /exchange/user_data_timestamp`
	[[nodiscard]] Result<std::string> get_user_data_timestamp();

	// ----- fcm ---------------------------------------------------------------

	/// Get FCM Fills
	/// `GET /fcm/fills`
	[[nodiscard]] Result<GetFcmFillsResponse> get_fcm_fills(const GetFcmFillsParams& params = {});

	/// Get FCM Orders
	/// `GET /fcm/orders`
	[[nodiscard]] Result<GetOrdersResponse> get_fcm_orders(const GetFcmOrdersParams& params = {});

	/// List FCM Subtraders
	/// `GET /fcm/subtraders`
	[[nodiscard]] Result<std::vector<FCMSubtrader>> get_fcm_subtraders();

	/// Create FCM Subtrader
	/// `POST /fcm/subtraders`
	[[nodiscard]] Result<std::string> create_fcm_subtrader(const CreateFCMSubtraderRequest& body);

	/// Get FCM Subtrader Event Contract Daily Cap
	/// `GET /fcm/subtraders/event_contract_daily_cap`
	[[nodiscard]] Result<GetFCMEventContractDailyCapResponse>
	get_fcm_event_contract_daily_cap(const GetFcmEventContractDailyCapParams& params = {});

	/// Update FCM Subtrader Event Contract Daily Cap
	/// `PUT /fcm/subtraders/event_contract_daily_cap`
	[[nodiscard]] Result<void>
	update_fcm_event_contract_daily_cap(const UpdateFCMEventContractDailyCapRequest& body);

	/// Delete FCM Subtrader Event Contract Daily Cap
	/// `DELETE /fcm/subtraders/event_contract_daily_cap`
	[[nodiscard]] Result<void>
	delete_fcm_event_contract_daily_cap(const DeleteFcmEventContractDailyCapParams& params);

	/// Get FCM Subtrader Blocked Categories
	/// `GET /fcm/subtraders/blocked_categories`
	[[nodiscard]] Result<std::vector<std::string>>
	get_fcm_subtrader_blocked_categories(const GetFcmSubtraderBlockedCategoriesParams& params);

	/// Update FCM Subtrader Blocked Categories
	/// `PUT /fcm/subtraders/blocked_categories`
	[[nodiscard]] Result<std::vector<std::string>>
	update_fcm_subtrader_blocked_categories(const UpdateFCMSubtraderBlockedCategoriesRequest& body);

	/// Get FCM Positions
	/// `GET /fcm/positions`
	[[nodiscard]] Result<GetPositionsResponse>
	get_fcm_positions(const GetFcmPositionsParams& params = {});

	// ----- historical --------------------------------------------------------

	/// Get Historical Cutoff Timestamps
	/// `GET /historical/cutoff`
	[[nodiscard]] Result<GetHistoricalCutoffResponse> get_historical_cutoff();

	/// Get Historical Market Candlesticks
	/// `GET /historical/markets/{ticker}/candlesticks`
	[[nodiscard]] Result<GetMarketCandlesticksHistoricalResponse>
	get_market_candlesticks_historical(std::string_view ticker,
									   const GetMarketCandlesticksHistoricalParams& params);

	/// Get Historical Fills
	/// `GET /historical/fills`
	[[nodiscard]] Result<GetFillsResponse>
	get_fills_historical(const GetFillsHistoricalParams& params = {});

	/// Get Historical Orders
	/// `GET /historical/orders`
	[[nodiscard]] Result<GetOrdersResponse>
	get_historical_orders(const GetHistoricalOrdersParams& params = {});

	/// Get Historical Positions
	/// `GET /historical/positions`
	[[nodiscard]] Result<GetPositionsResponse>
	get_historical_positions(const GetHistoricalPositionsParams& params = {});

	/// Get Historical Trades
	/// `GET /historical/trades`
	[[nodiscard]] Result<GetTradesResponse>
	get_trades_historical(const GetTradesHistoricalParams& params = {});

	/// Get Historical Markets
	/// `GET /historical/markets`
	[[nodiscard]] Result<GetMarketsResponse>
	get_historical_markets(const GetHistoricalMarketsParams& params = {});

	/// Get Historical Market
	/// `GET /historical/markets/{ticker}`
	[[nodiscard]] Result<Market> get_historical_market(std::string_view ticker);

	// ----- incentive-programs ------------------------------------------------

	/// Get Incentives
	/// `GET /incentive_programs`
	[[nodiscard]] Result<GetIncentiveProgramsResponse>
	get_incentive_programs(const GetIncentiveProgramsParams& params = {});

	// ----- live-data ---------------------------------------------------------

	/// Get Live Data
	/// `GET /live_data/milestone/{milestone_id}`
	[[nodiscard]] Result<LiveData>
	get_live_data_by_milestone(std::string_view milestone_id,
							   const GetLiveDataByMilestoneParams& params = {});

	/// Get Live Data (with type)
	/// `GET /live_data/{type}/milestone/{milestone_id}`
	[[nodiscard]] Result<LiveData> get_live_data(std::string_view type,
												 std::string_view milestone_id,
												 const GetLiveDataParams& params = {});

	/// Get Multiple Live Data
	/// `GET /live_data/batch`
	[[nodiscard]] Result<std::vector<LiveData>> get_live_datas(const GetLiveDatasParams& params);

	/// Get Game Stats
	/// `GET /live_data/milestone/{milestone_id}/game_stats`
	[[nodiscard]] Result<std::optional<PlayByPlay>> get_game_stats(std::string_view milestone_id);

	/// Get Event Live Data
	/// `GET /live_data/events/{event_ticker}`
	[[nodiscard]] Result<EventLiveData>
	get_event_live_data(std::string_view event_ticker, const GetEventLiveDataParams& params = {});

	/// Get Weather Index
	/// `GET /live_data/weather/{city}`
	[[nodiscard]] Result<GetWeatherIndexResponse>
	get_weather_index(std::string_view city, const GetWeatherIndexParams& params = {});

	/// Get Weather Index Calibrations
	/// `GET /live_data/weather/{city}/calibrations`
	[[nodiscard]] Result<GetWeatherIndexCalibrationsResponse>
	get_weather_index_calibrations(std::string_view city);

	// ----- market ------------------------------------------------------------

	/// Get Market Candlesticks
	/// `GET /series/{series_ticker}/markets/{ticker}/candlesticks`
	[[nodiscard]] Result<GetMarketCandlesticksResponse>
	get_market_candlesticks(std::string_view series_ticker, std::string_view ticker,
							const GetMarketCandlesticksParams& params);

	/// Get Trades
	/// `GET /markets/trades`
	[[nodiscard]] Result<GetTradesResponse> get_trades(const GetTradesParams& params = {});

	/// Get Market Orderbook
	/// `GET /markets/{ticker}/orderbook`
	[[nodiscard]] Result<OrderbookCountFp>
	get_market_orderbook(std::string_view ticker, const GetMarketOrderbookParams& params = {});

	/// Get Multiple Market Orderbooks
	/// `GET /markets/orderbooks`
	[[nodiscard]] Result<std::vector<MarketOrderbookFp>>
	get_market_orderbooks(const GetMarketOrderbooksParams& params);

	/// Get Series
	/// `GET /series/{series_ticker}`
	[[nodiscard]] Result<Series> get_series(std::string_view series_ticker,
											const GetSeriesParams& params = {});

	/// Get Series List
	/// `GET /series`
	[[nodiscard]] Result<std::vector<Series>>
	get_series_list(const GetSeriesListParams& params = {});

	/// Get Markets
	/// `GET /markets`
	[[nodiscard]] Result<GetMarketsResponse> get_markets(const GetMarketsParams& params = {});

	/// Get Market
	/// `GET /markets/{ticker}`
	[[nodiscard]] Result<Market> get_market(std::string_view ticker);

	/// Batch Get Market Candlesticks
	/// `GET /markets/candlesticks`
	[[nodiscard]] Result<std::vector<MarketCandlesticksResponse>>
	batch_get_market_candlesticks(const BatchGetMarketCandlesticksParams& params);

	// ----- milestone ---------------------------------------------------------

	/// Get Milestone
	/// `GET /milestones/{milestone_id}`
	[[nodiscard]] Result<Milestone> get_milestone(std::string_view milestone_id);

	/// Get Milestones
	/// `GET /milestones`
	[[nodiscard]] Result<GetMilestonesResponse> get_milestones(const GetMilestonesParams& params);

	// ----- multivariate ------------------------------------------------------

	/// Get Multivariate Event Collection
	/// `GET /multivariate_event_collections/{collection_ticker}`
	[[nodiscard]] Result<MultivariateEventCollection>
	get_multivariate_event_collection(std::string_view collection_ticker);

	/// Create Market In Multivariate Event Collection
	/// `POST /multivariate_event_collections/{collection_ticker}`
	[[nodiscard]] Result<CreateMarketInMultivariateEventCollectionResponse>
	create_market_in_multivariate_event_collection(
		std::string_view collection_ticker,
		const CreateMarketInMultivariateEventCollectionRequest& body);

	/// Get Multivariate Event Collections
	/// `GET /multivariate_event_collections`
	[[nodiscard]] Result<GetMultivariateEventCollectionsResponse>
	get_multivariate_event_collections(const GetMultivariateEventCollectionsParams& params = {});

	// ----- order-groups ------------------------------------------------------

	/// Get Order Groups
	/// `GET /portfolio/order_groups`
	[[nodiscard]] Result<std::optional<std::vector<OrderGroup>>>
	get_order_groups(const GetOrderGroupsParams& params = {});

	/// Create Order Group
	/// `POST /portfolio/order_groups/create`
	[[nodiscard]] Result<CreateOrderGroupResponse>
	create_order_group(const CreateOrderGroupRequest& body);

	/// Get Order Group
	/// `GET /portfolio/order_groups/{order_group_id}`
	[[nodiscard]] Result<GetOrderGroupResponse>
	get_order_group(std::string_view order_group_id, const GetOrderGroupParams& params = {});

	/// Delete Order Group
	/// `DELETE /portfolio/order_groups/{order_group_id}`
	[[nodiscard]] Result<void> delete_order_group(std::string_view order_group_id,
												  const DeleteOrderGroupParams& params = {});

	/// Reset Order Group
	/// `PUT /portfolio/order_groups/{order_group_id}/reset`
	[[nodiscard]] Result<void> reset_order_group(std::string_view order_group_id,
												 const ResetOrderGroupParams& params = {});

	/// Trigger Order Group
	/// `PUT /portfolio/order_groups/{order_group_id}/trigger`
	[[nodiscard]] Result<void> trigger_order_group(std::string_view order_group_id,
												   const TriggerOrderGroupParams& params = {});

	/// Update Order Group Limit
	/// `PUT /portfolio/order_groups/{order_group_id}/limit`
	[[nodiscard]] Result<void>
	update_order_group_limit(std::string_view order_group_id,
							 const UpdateOrderGroupLimitRequest& body,
							 const UpdateOrderGroupLimitParams& params = {});

	// ----- orders ------------------------------------------------------------

	/// Get Orders
	/// `GET /portfolio/orders`
	[[nodiscard]] Result<GetOrdersResponse> get_orders(const GetOrdersParams& params = {});

	/// Get Order
	/// `GET /portfolio/orders/{order_id}`
	[[nodiscard]] Result<Order> get_order(std::string_view order_id);

	/// Get Queue Positions for Orders
	/// `GET /portfolio/orders/queue_positions`
	[[nodiscard]] Result<std::vector<OrderQueuePosition>>
	get_order_queue_positions(const GetOrderQueuePositionsParams& params = {});

	/// Get Order Queue Position
	/// `GET /portfolio/orders/{order_id}/queue_position`
	[[nodiscard]] Result<FixedPointCount> get_order_queue_position(std::string_view order_id);

	/// Create Order
	/// `POST /portfolio/events/orders`
	[[nodiscard]] Result<CreateOrderV2Response> create_order(const CreateOrderV2Request& body);

	/// Cancel All Orders
	/// `DELETE /portfolio/events/orders`
	[[nodiscard]] Result<void> cancel_all_orders(const CancelAllOrdersParams& params = {});

	/// Batch Create Orders
	/// `POST /portfolio/events/orders/batched`
	[[nodiscard]] Result<std::vector<BatchCreateOrdersV2ResponseOrdersItem>>
	batch_create_orders(const BatchCreateOrdersV2Request& body);

	/// Batch Cancel Orders
	/// `DELETE /portfolio/events/orders/batched`
	[[nodiscard]] Result<std::vector<BatchCancelOrdersV2ResponseOrdersItem>>
	batch_cancel_orders(const BatchCancelOrdersV2Request& body);

	/// Cancel Order
	/// `DELETE /portfolio/events/orders/{order_id}`
	[[nodiscard]] Result<CancelOrderV2Response> cancel_order(std::string_view order_id,
															 const CancelOrderParams& params = {});

	/// Amend Order
	/// `POST /portfolio/events/orders/{order_id}/amend`
	[[nodiscard]] Result<AmendOrderV2Response> amend_order(std::string_view order_id,
														   const AmendOrderV2Request& body,
														   const AmendOrderParams& params = {});

	/// Decrease Order
	/// `POST /portfolio/events/orders/{order_id}/decrease`
	[[nodiscard]] Result<DecreaseOrderV2Response>
	decrease_order(std::string_view order_id, const DecreaseOrderV2Request& body,
				   const DecreaseOrderParams& params = {});

	// ----- portfolio ---------------------------------------------------------

	/// Get Balance
	/// `GET /portfolio/balance`
	[[nodiscard]] Result<GetBalanceResponse> get_balance(const GetBalanceParams& params = {});

	/// Intra Account Transfer
	/// `POST /portfolio/intra_exchange_instance_transfer`
	[[nodiscard]] Result<std::string>
	intra_exchange_instance_transfer(const IntraExchangeInstanceTransferRequest& body);

	/// Get Intra Account Transfers
	/// `GET /portfolio/intra_exchange_instance_transfers`
	[[nodiscard]] Result<GetIntraExchangeInstanceTransfersResponse>
	get_intra_exchange_instance_transfers(
		const GetIntraExchangeInstanceTransfersParams& params = {});

	/// Get Intra Account Transfer
	/// `GET /portfolio/intra_exchange_instance_transfers/{transfer_id}`
	[[nodiscard]] Result<IntraExchangeInstanceTransfer>
	get_intra_exchange_instance_transfer(std::string_view transfer_id);

	/// Create Subaccount
	/// `POST /portfolio/subaccounts`
	[[nodiscard]] Result<std::int64_t> create_subaccount(const CreateSubaccountRequest& body);

	/// Transfer Between Subaccounts
	/// `POST /portfolio/subaccounts/transfer`
	[[nodiscard]] Result<void>
	apply_subaccount_transfer(const ApplySubaccountTransferRequest& body);

	/// Get All Subaccount Balances
	/// `GET /portfolio/subaccounts/balances`
	[[nodiscard]] Result<std::vector<SubaccountBalance>> get_subaccount_balances();

	/// Get Subaccount Transfers
	/// `GET /portfolio/subaccounts/transfers`
	[[nodiscard]] Result<GetSubaccountTransfersResponse>
	get_subaccount_transfers(const GetSubaccountTransfersParams& params = {});

	/// Get Subaccount Netting
	/// `GET /portfolio/subaccounts/netting`
	[[nodiscard]] Result<std::vector<SubaccountNettingConfig>> get_subaccount_netting();

	/// Update Subaccount Netting
	/// `PUT /portfolio/subaccounts/netting`
	[[nodiscard]] Result<void>
	update_subaccount_netting(const UpdateSubaccountNettingRequest& body);

	/// Get Positions
	/// `GET /portfolio/positions`
	[[nodiscard]] Result<GetPositionsResponse> get_positions(const GetPositionsParams& params = {});

	/// Get Settlements
	/// `GET /portfolio/settlements`
	[[nodiscard]] Result<GetSettlementsResponse>
	get_settlements(const GetSettlementsParams& params = {});

	/// Get Deposits
	/// `GET /portfolio/deposits`
	[[nodiscard]] Result<GetDepositsResponse> get_deposits(const GetDepositsParams& params = {});

	/// Get Withdrawals
	/// `GET /portfolio/withdrawals`
	[[nodiscard]] Result<GetWithdrawalsResponse>
	get_withdrawals(const GetWithdrawalsParams& params = {});

	/// Get Total Resting Order Value
	/// `GET /portfolio/summary/total_resting_order_value`
	[[nodiscard]] Result<GetPortfolioRestingOrderTotalValueResponse>
	get_portfolio_resting_order_total_value();

	/// Get Fills
	/// `GET /portfolio/fills`
	[[nodiscard]] Result<GetFillsResponse> get_fills(const GetFillsParams& params = {});

	/// Get Target Balance Allocation
	/// `GET /portfolio/target_balance_allocation`
	[[nodiscard]] Result<GetTargetBalanceAllocationResponse> get_target_balance_allocation();

	/// Set Target Balance Allocation
	/// `POST /portfolio/target_balance_allocation`
	[[nodiscard]] Result<void>
	set_target_balance_allocation(const SetTargetBalanceAllocationRequest& body);

	// ----- search ------------------------------------------------------------

	/// Get Tags for Series Categories
	/// `GET /search/tags_by_categories`
	[[nodiscard]] Result<std::map<std::string, std::vector<std::string>>>
	get_tags_for_series_categories();

	/// Get Filters for Sports
	/// `GET /search/filters_by_sport`
	[[nodiscard]] Result<GetFiltersBySportsResponse> get_filters_for_sports();

	// ----- structured-targets ------------------------------------------------

	/// Get Structured Targets
	/// `GET /structured_targets`
	[[nodiscard]] Result<GetStructuredTargetsResponse>
	get_structured_targets(const GetStructuredTargetsParams& params = {});

	/// Get Structured Target
	/// `GET /structured_targets/{structured_target_id}`
	[[nodiscard]] Result<std::optional<StructuredTarget>>
	get_structured_target(std::string_view structured_target_id);

private:
	struct Impl;
	std::unique_ptr<Impl> impl_;
};

/// Builds a RateLimitedTransport config from `get_account_api_limits()` and
/// `get_account_endpoint_costs()`.
[[nodiscard]] RateLimitConfig rate_limit_config(const GetAccountApiLimitsResponse& limits,
												const GetAccountEndpointCostsResponse& costs);

} // namespace kalshi
