// Generated by tools/codegen/generate.py from spec/asyncapi.yaml. Do not edit.
#pragma once

// WebSocket message types. They live in `kalshi::ws` because several share
// names with REST models, such as `Trade` and `Fill`.

#include "kalshi/models.hpp"

#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <variant>
#include <vector>

namespace kalshi::ws {

/// A WebSocket channel.
enum class Channel : std::uint8_t {
	Unknown,					 ///< A value this SDK version does not know.
	OrderbookDelta,				 ///< `orderbook_delta`
	Ticker,						 ///< `ticker`
	Trade,						 ///< `trade`
	Fill,						 ///< `fill`
	MarketPositions,			 ///< `market_positions`
	MarketLifecycleV2,			 ///< `market_lifecycle_v2`
	MultivariateMarketLifecycle, ///< `multivariate_market_lifecycle`
	Communications,				 ///< `communications`
	OrderGroupUpdates,			 ///< `order_group_updates`
	UserOrders,					 ///< `user_orders`
	CfbenchmarksValue,			 ///< `cfbenchmarks_value`
	CfbenchmarksValue5hz,		 ///< `cfbenchmarks_value_5hz`
	PythValue,					 ///< `pyth_value`
};

[[nodiscard]] constexpr std::string_view to_string(Channel value) noexcept {
	switch (value) {
		case Channel::OrderbookDelta:
			return "orderbook_delta";
		case Channel::Ticker:
			return "ticker";
		case Channel::Trade:
			return "trade";
		case Channel::Fill:
			return "fill";
		case Channel::MarketPositions:
			return "market_positions";
		case Channel::MarketLifecycleV2:
			return "market_lifecycle_v2";
		case Channel::MultivariateMarketLifecycle:
			return "multivariate_market_lifecycle";
		case Channel::Communications:
			return "communications";
		case Channel::OrderGroupUpdates:
			return "order_group_updates";
		case Channel::UserOrders:
			return "user_orders";
		case Channel::CfbenchmarksValue:
			return "cfbenchmarks_value";
		case Channel::CfbenchmarksValue5hz:
			return "cfbenchmarks_value_5hz";
		case Channel::PythValue:
			return "pyth_value";
		case Channel::Unknown:
			break;
	}
	return "";
}

/// Collateral return type, MECNET or DIRECNET of the event.
enum class CollateralReturnType : std::uint8_t {
	Unknown,  ///< A value this SDK version does not know.
	MECNET,	  ///< `MECNET`
	DIRECNET, ///< `DIRECNET`
	Unset,	  ///< empty string
};

[[nodiscard]] constexpr std::string_view to_string(CollateralReturnType value) noexcept {
	switch (value) {
		case CollateralReturnType::MECNET:
			return "MECNET";
		case CollateralReturnType::DIRECNET:
			return "DIRECNET";
		case CollateralReturnType::Unset:
			return "";
		case CollateralReturnType::Unknown:
			break;
	}
	return "";
}

/// Event fee type override.
enum class FeeTypeOverride : std::uint8_t {
	Unknown,					  ///< A value this SDK version does not know.
	Quadratic,					  ///< `quadratic`
	QuadraticWithMakerFees,		  ///< `quadratic_with_maker_fees`
	QuadraticWithComboMakerFees,  ///< `quadratic_with_combo_maker_fees`
	Flat,						  ///< `flat`
	MarginMarketMakerProgramFees, ///< `margin_market_maker_program_fees`
};

[[nodiscard]] constexpr std::string_view to_string(FeeTypeOverride value) noexcept {
	switch (value) {
		case FeeTypeOverride::Quadratic:
			return "quadratic";
		case FeeTypeOverride::QuadraticWithMakerFees:
			return "quadratic_with_maker_fees";
		case FeeTypeOverride::QuadraticWithComboMakerFees:
			return "quadratic_with_combo_maker_fees";
		case FeeTypeOverride::Flat:
			return "flat";
		case FeeTypeOverride::MarginMarketMakerProgramFees:
			return "margin_market_maker_program_fees";
		case FeeTypeOverride::Unknown:
			break;
	}
	return "";
}

/// Optional - The market price level structure on creation or price_level_structure_updated
/// events
enum class LifecyclePriceLevelStructure : std::uint8_t {
	Unknown,				  ///< A value this SDK version does not know.
	BandedCentiCent,		  ///< `banded_centi_cent`
	Unset,					  ///< empty string
	LinearCent,				  ///< `linear_cent`
	DeciCent,				  ///< `deci_cent`
	TaperedDeciCent,		  ///< `tapered_deci_cent`
	CenterWholeEdgeHalfCent,  ///< `center_whole_edge_half_cent`
	CenterWholeEdgeQuintCent, ///< `center_whole_edge_quint_cent`
	CenterHalfEdgeHalfCent,	  ///< `center_half_edge_half_cent`
	CenterHalfEdgeQuintCent,  ///< `center_half_edge_quint_cent`
	CenterHalfEdgeDeciCent,	  ///< `center_half_edge_deci_cent`
	CenterQuintEdgeQuintCent, ///< `center_quint_edge_quint_cent`
	CenterQuintEdgeDeciCent,  ///< `center_quint_edge_deci_cent`
	CenterCentiEdgeCentiCent, ///< `center_centi_edge_centi_cent`
	CenterDeciEdgeCentiCent,  ///< `center_deci_edge_centi_cent`
};

[[nodiscard]] constexpr std::string_view to_string(LifecyclePriceLevelStructure value) noexcept {
	switch (value) {
		case LifecyclePriceLevelStructure::BandedCentiCent:
			return "banded_centi_cent";
		case LifecyclePriceLevelStructure::Unset:
			return "";
		case LifecyclePriceLevelStructure::LinearCent:
			return "linear_cent";
		case LifecyclePriceLevelStructure::DeciCent:
			return "deci_cent";
		case LifecyclePriceLevelStructure::TaperedDeciCent:
			return "tapered_deci_cent";
		case LifecyclePriceLevelStructure::CenterWholeEdgeHalfCent:
			return "center_whole_edge_half_cent";
		case LifecyclePriceLevelStructure::CenterWholeEdgeQuintCent:
			return "center_whole_edge_quint_cent";
		case LifecyclePriceLevelStructure::CenterHalfEdgeHalfCent:
			return "center_half_edge_half_cent";
		case LifecyclePriceLevelStructure::CenterHalfEdgeQuintCent:
			return "center_half_edge_quint_cent";
		case LifecyclePriceLevelStructure::CenterHalfEdgeDeciCent:
			return "center_half_edge_deci_cent";
		case LifecyclePriceLevelStructure::CenterQuintEdgeQuintCent:
			return "center_quint_edge_quint_cent";
		case LifecyclePriceLevelStructure::CenterQuintEdgeDeciCent:
			return "center_quint_edge_deci_cent";
		case LifecyclePriceLevelStructure::CenterCentiEdgeCentiCent:
			return "center_centi_edge_centi_cent";
		case LifecyclePriceLevelStructure::CenterDeciEdgeCentiCent:
			return "center_deci_edge_centi_cent";
		case LifecyclePriceLevelStructure::Unknown:
			break;
	}
	return "";
}

/// Field to annotate which of the event type this event is for
enum class MarketLifecycleV2EventType : std::uint8_t {
	Unknown,					///< A value this SDK version does not know.
	Created,					///< `created`
	Deactivated,				///< `deactivated`
	Activated,					///< `activated`
	CloseDateUpdated,			///< `close_date_updated`
	Determined,					///< `determined`
	Settled,					///< `settled`
	PriceLevelStructureUpdated, ///< `price_level_structure_updated`
};

[[nodiscard]] constexpr std::string_view to_string(MarketLifecycleV2EventType value) noexcept {
	switch (value) {
		case MarketLifecycleV2EventType::Created:
			return "created";
		case MarketLifecycleV2EventType::Deactivated:
			return "deactivated";
		case MarketLifecycleV2EventType::Activated:
			return "activated";
		case MarketLifecycleV2EventType::CloseDateUpdated:
			return "close_date_updated";
		case MarketLifecycleV2EventType::Determined:
			return "determined";
		case MarketLifecycleV2EventType::Settled:
			return "settled";
		case MarketLifecycleV2EventType::PriceLevelStructureUpdated:
			return "price_level_structure_updated";
		case MarketLifecycleV2EventType::Unknown:
			break;
	}
	return "";
}

/// Field to annotate which of the event type this event is for
enum class MultivariateMarketLifecycleEventType : std::uint8_t {
	Unknown,		  ///< A value this SDK version does not know.
	Created,		  ///< `created`
	Deactivated,	  ///< `deactivated`
	Activated,		  ///< `activated`
	CloseDateUpdated, ///< `close_date_updated`
	Determined,		  ///< `determined`
	Settled,		  ///< `settled`
};

[[nodiscard]] constexpr std::string_view
to_string(MultivariateMarketLifecycleEventType value) noexcept {
	switch (value) {
		case MultivariateMarketLifecycleEventType::Created:
			return "created";
		case MultivariateMarketLifecycleEventType::Deactivated:
			return "deactivated";
		case MultivariateMarketLifecycleEventType::Activated:
			return "activated";
		case MultivariateMarketLifecycleEventType::CloseDateUpdated:
			return "close_date_updated";
		case MultivariateMarketLifecycleEventType::Determined:
			return "determined";
		case MultivariateMarketLifecycleEventType::Settled:
			return "settled";
		case MultivariateMarketLifecycleEventType::Unknown:
			break;
	}
	return "";
}

/// Deprecated.
enum class OrderAction : std::uint8_t {
	Unknown,	 ///< A value this SDK version does not know.
	Buy,		 ///< `buy`
	Sell,		 ///< `sell`
	SellPartial, ///< `sell_partial`
	SellToClose, ///< `sell_to_close`
	Unset,		 ///< empty string
};

[[nodiscard]] constexpr std::string_view to_string(OrderAction value) noexcept {
	switch (value) {
		case OrderAction::Buy:
			return "buy";
		case OrderAction::Sell:
			return "sell";
		case OrderAction::SellPartial:
			return "sell_partial";
		case OrderAction::SellToClose:
			return "sell_to_close";
		case OrderAction::Unset:
			return "";
		case OrderAction::Unknown:
			break;
	}
	return "";
}

/// Order group event type
enum class OrderGroupUpdatesEventType : std::uint8_t {
	Unknown,	  ///< A value this SDK version does not know.
	Created,	  ///< `created`
	Triggered,	  ///< `triggered`
	Reset,		  ///< `reset`
	Deleted,	  ///< `deleted`
	LimitUpdated, ///< `limit_updated`
};

[[nodiscard]] constexpr std::string_view to_string(OrderGroupUpdatesEventType value) noexcept {
	switch (value) {
		case OrderGroupUpdatesEventType::Created:
			return "created";
		case OrderGroupUpdatesEventType::Triggered:
			return "triggered";
		case OrderGroupUpdatesEventType::Reset:
			return "reset";
		case OrderGroupUpdatesEventType::Deleted:
			return "deleted";
		case OrderGroupUpdatesEventType::LimitUpdated:
			return "limit_updated";
		case OrderGroupUpdatesEventType::Unknown:
			break;
	}
	return "";
}

enum class UpdateAction : std::uint8_t {
	Unknown,				///< A value this SDK version does not know.
	AddMarkets,				///< `add_markets`
	DeleteMarkets,			///< `delete_markets`
	GetSnapshot,			///< `get_snapshot`
	SubscribeIndices,		///< `subscribe_indices`
	UnsubscribeIndices,		///< `unsubscribe_indices`
	Indexlist,				///< `indexlist`
	SubscribeUnderlyings,	///< `subscribe_underlyings`
	UnsubscribeUnderlyings, ///< `unsubscribe_underlyings`
	UnderlyingList,			///< `underlying_list`
};

[[nodiscard]] constexpr std::string_view to_string(UpdateAction value) noexcept {
	switch (value) {
		case UpdateAction::AddMarkets:
			return "add_markets";
		case UpdateAction::DeleteMarkets:
			return "delete_markets";
		case UpdateAction::GetSnapshot:
			return "get_snapshot";
		case UpdateAction::SubscribeIndices:
			return "subscribe_indices";
		case UpdateAction::UnsubscribeIndices:
			return "unsubscribe_indices";
		case UpdateAction::Indexlist:
			return "indexlist";
		case UpdateAction::SubscribeUnderlyings:
			return "subscribe_underlyings";
		case UpdateAction::UnsubscribeUnderlyings:
			return "unsubscribe_underlyings";
		case UpdateAction::UnderlyingList:
			return "underlying_list";
		case UpdateAction::Unknown:
			break;
	}
	return "";
}

/// Communications channel only.
enum class UserFilter : std::uint8_t {
	Unknown, ///< A value this SDK version does not know.
	Unset,	 ///< empty string
	Self,	 ///< `self`
};

[[nodiscard]] constexpr std::string_view to_string(UserFilter value) noexcept {
	switch (value) {
		case UserFilter::Unset:
			return "";
		case UserFilter::Self:
			return "self";
		case UserFilter::Unknown:
			break;
	}
	return "";
}

/// A handle for one channel subscription. It stays the same across reconnects;
/// the server's `sid` does not.
struct Subscription {
	std::int64_t id{0};
	Channel channel{Channel::Unknown};

	friend bool operator==(const Subscription&, const Subscription&) = default;
};

/// One data frame. `msg` holds the channel's payload.
template <typename T>
struct Update {
	/// The server's subscription ID, which changes after a reconnect.
	std::int64_t sid{0};
	/// Present on sequenced channels. The client checks it for gaps.
	std::optional<std::int64_t> seq;
	/// The command that asked for this frame, such as a `get_snapshot`.
	std::optional<std::int64_t> id;
	/// `Subscription::id` of the subscription that produced the frame.
	std::int64_t subscription{0};
	T msg;
};

/// The index IDs recently observed on the 5Hz stream, sent in response to an indexlist action
struct Cfbenchmarks5HzIndexList {
	/// Index IDs recently observed on the 5Hz stream
	std::vector<std::string> index_ids;
};

/// Trailing 60-second average metadata.
struct CfbenchmarksAvgData {
	/// Average value over the window, formatted to 8 decimal places
	std::string value;
	/// Number of ticks counted in the window
	std::int64_t window_size{};
	/// Window start boundary (unix ms)
	std::int64_t window_start_ts_ms{};
	/// Window end boundary, exclusive (unix ms)
	std::int64_t window_end_ts_exclusive{};
};

/// The set of available CF Benchmarks index IDs, sent in response to an indexlist action
struct CfbenchmarksIndexList {
	/// Available CF Benchmarks index IDs
	std::vector<std::string> index_ids;
};

/// Real-time CF Benchmarks index value with trailing 60-second and quarter-hour averages
struct CfbenchmarksValue {
	/// CF Benchmarks index ID (for example "BRTI")
	std::string index_id;
	/// When Kalshi received the upstream frame (unix ms)
	std::int64_t received_at{};
	/// The raw CF Benchmarks JSON frame, as a string
	std::string data;
	/// Trailing 60-second average metadata.
	CfbenchmarksAvgData avg_60s_data;
	/// Optional - present only during the final minute before quarter-hour close (:00, :15, :30,
	/// :45).
	std::optional<CfbenchmarksAvgData> last_60s_windowed_average_15min;
};

/// Real-time CF Benchmarks index value at up to 5 updates per second
struct CfbenchmarksValue5Hz {
	/// CF Benchmarks index ID (for example "BRTI")
	std::string index_id;
	/// Index value in USD, formatted with exactly 8 decimal places
	std::string value_usd;
	/// Upstream publication timestamp of the tick (unix ms)
	std::int64_t source_ts_ms{};
	/// When Kalshi received the upstream frame (unix ms)
	std::int64_t received_at{};
	/// The raw CF Benchmarks JSON frame, as a string
	std::string data;
};

/// Emitted when an event-level fee override is set or cleared
struct EventFeeUpdate {
	/// Unique identifier for the event
	std::string event_ticker;
	/// Event fee type override.
	std::optional<FeeTypeOverride> fee_type_override;
	/// Event fee multiplier override.
	std::optional<double> fee_multiplier_override;
};

/// Event creation notification
struct EventLifecycle {
	/// Unique identifier for the event being created
	std::string event_ticker;
	/// Identifier for the exchange shard the event's markets live on
	std::int64_t exchange_index{};
	/// Title of event
	std::string title;
	/// Subtitle of event
	std::string subtitle;
	/// Collateral return type, MECNET or DIRECNET of the event.
	CollateralReturnType collateral_return_type{};
	/// Series ticker for the event
	std::string series_ticker;
	/// Optional - Unix timestamp to indicate the strike date of the event if there is one
	std::optional<std::int64_t> strike_date;
	/// Optional - String to indicate the strike period of the event if there is one
	std::optional<std::string> strike_period;
};

/// Private fill information for authenticated user
struct Fill {
	/// Unique identifier for fills.
	std::string trade_id;
	/// Unique identifier for orders.
	std::string order_id;
	/// Optional client-provided order ID
	std::optional<std::string> client_order_id;
	/// Unique identifier for markets.
	std::string market_ticker;
	/// Identifier for the exchange shard where the fill occurred
	std::int64_t exchange_index{};
	/// If you were a taker on this fill
	bool is_taker{};
	/// Deprecated.
	kalshi::Side side{};
	/// Deprecated - Unix timestamp for when the update happened (in seconds).
	std::int64_t ts{};
	/// Unix timestamp for when the update happened (in milliseconds)
	std::int64_t ts_ms{};
	/// Price for the yes side of the fill in dollars
	std::string yes_price_dollars;
	/// Fixed-point contracts filled (2 decimals)
	std::string count_fp;
	/// Exchange fee paid for this fill in fixed-point dollars
	std::string fee_cost;
	/// Deprecated.
	OrderAction action{};
	/// Fixed-point position after the fill (2 decimals)
	std::string post_position_fp;
	/// Deprecated.
	kalshi::Side purchased_side{};
	/// The outcome side this fill positioned the user for.
	kalshi::OutcomeSide outcome_side{};
	/// Same directional bit as outcome_side in book vocabulary.
	kalshi::BookSide book_side{};
	/// Optional subaccount number for the fill
	std::optional<std::int64_t> subaccount;
};

/// Optional - This key will be emitted when the market is created
struct LifecycleAdditionalMetadata {
	std::string name;
	std::string title;
	std::string yes_sub_title;
	std::string no_sub_title;
	std::string rules_primary;
	std::string rules_secondary;
	bool can_close_early{};
	std::string event_ticker;
	std::int64_t expected_expiration_ts{};
	std::optional<std::string> strike_type;
	std::optional<double> floor_strike;
	std::optional<double> cap_strike;
	std::optional<RawJson> custom_strike;
};

struct MarketLifecycleV2PriceRangesItem {
	/// Starting price for this band, in dollars
	std::string start;
	/// Ending price for this band, in dollars
	std::string end;
	/// Tick size (minimum price increment) within this band, in dollars
	std::string step;
};

/// Market lifecycle events (created, activated, deactivated, close_date_updated, determined,
/// settled, price_level_structure_updated)
struct MarketLifecycleV2 {
	/// Unique identifier for markets.
	std::string market_ticker;
	/// Optional - This key will ONLY exist when the market is created.
	std::optional<std::int64_t> exchange_index;
	/// Optional - This key will ONLY exist when the market is created.
	std::optional<std::int64_t> open_ts;
	/// Optional - This key will ONLY exist when the market is created OR when the close date is
	/// updated.
	std::optional<std::int64_t> close_ts;
	/// Optional - This key will ONLY exist when the market is determined.
	std::optional<std::int64_t> determination_ts;
	/// Optional - This key will ONLY exist when the market is settled.
	std::optional<std::int64_t> settled_ts;
	/// Optional - This key will ONLY exist when the market is determined.
	std::optional<std::string> result;
	/// Optional - This key will ONLY exist when the market is determined.
	std::optional<std::string> settlement_value;
	/// Optional - This key will ONLY exist when the market is paused/unpaused.
	std::optional<bool> is_deactivated;
	/// Optional - This key will be emitted when the market is created
	std::optional<LifecycleAdditionalMetadata> additional_metadata;
	/// Field to annotate which of the event type this event is for
	MarketLifecycleV2EventType event_type{};
	/// Optional - The market price level structure on creation or price_level_structure_updated
	/// events
	std::optional<LifecyclePriceLevelStructure> price_level_structure;
	/// Optional - Emitted alongside price_level_structure (on market creation and
	/// price_level_structure_updated events).
	std::optional<std::vector<MarketLifecycleV2PriceRangesItem>> price_ranges;
};

/// Updated strike information or yes subtitle
struct MarketMetadataUpdated {
	/// Unique identifier for markets.
	std::string market_ticker;
	/// Optional - This key will ONLY exist for metadata_updated events.
	std::optional<std::string> strike_type;
	/// Optional - This key will ONLY exist for metadata_updated events.
	std::optional<double> floor_strike;
	/// Optional - This key will ONLY exist for metadata_updated events.
	std::optional<double> cap_strike;
	/// Optional - This key will ONLY exist for metadata_updated events with a custom or structured
	/// strike type
	std::optional<RawJson> custom_strike;
	/// Optional - This key will ONLY exist for metadata_updated events.
	std::optional<std::string> yes_sub_title;
};

/// Real-time position updates for authenticated user
struct MarketPosition {
	/// User ID for the position
	std::string user_id;
	/// Market ticker for the position
	std::string market_ticker;
	/// Fixed-point net position (2 decimals)
	std::string position_fp;
	/// Current cost basis of the position as a fixed-point dollar string
	std::string position_cost_dollars;
	/// Realized profit/loss as a fixed-point dollar string
	std::string realized_pnl_dollars;
	/// Total fees paid as a fixed-point dollar string
	std::string fees_paid_dollars;
	/// Total position fee cost as a fixed-point dollar string
	std::string position_fee_cost_dollars;
	/// Fixed-point total volume traded (2 decimals)
	std::string volume_fp;
	/// Optional subaccount number for the position
	std::optional<std::int64_t> subaccount;
};

/// Multivariate market lifecycle events (created, activated, deactivated, close_date_updated,
/// determined, settled)
struct MultivariateMarketLifecycle {
	/// Unique identifier for markets.
	std::string market_ticker;
	/// Optional - This key will ONLY exist when the market is created.
	std::optional<std::int64_t> exchange_index;
	/// Optional - This key will ONLY exist when the market is created.
	std::optional<std::int64_t> open_ts;
	/// Optional - This key will ONLY exist when the market is created OR when the close date is
	/// updated.
	std::optional<std::int64_t> close_ts;
	/// Optional - This key will ONLY exist when the market is determined.
	std::optional<std::int64_t> determination_ts;
	/// Optional - This key will ONLY exist when the market is settled.
	std::optional<std::int64_t> settled_ts;
	/// Optional - This key will ONLY exist when the market is determined.
	std::optional<std::string> result;
	/// Optional - This key will ONLY exist when the market is determined.
	std::optional<std::string> settlement_value;
	/// Optional - This key will ONLY exist when the market is paused/unpaused.
	std::optional<bool> is_deactivated;
	/// Optional - This key will be emitted when the market is created
	std::optional<LifecycleAdditionalMetadata> additional_metadata;
	/// Field to annotate which of the event type this event is for
	MultivariateMarketLifecycleEventType event_type{};
	/// Optional - The market price level structure on creation
	std::optional<LifecyclePriceLevelStructure> price_level_structure;
};

/// Order group lifecycle and limit updates for authenticated user
struct OrderGroupUpdates {
	/// Order group event type
	OrderGroupUpdatesEventType event_type{};
	/// Order group identifier
	std::string order_group_id;
	/// Updated contracts limit in fixed-point (2 decimals).
	std::optional<std::string> contracts_limit_fp;
	/// Matching engine timestamp at which the event was processed, as Unix epoch milliseconds.
	std::int64_t ts_ms{};
};

/// Update to be applied to the current order book view
struct OrderbookDelta {
	/// Unique market identifier
	std::string market_ticker;
	/// Unique market UUID
	std::string market_id;
	/// Price level in dollars
	std::string price_dollars;
	/// Fixed-point contract delta (2 decimals)
	std::string delta_fp;
	/// Market side
	kalshi::Side side{};
	/// Optional - Present only when you caused this orderbook change.
	std::optional<std::string> client_order_id;
	/// Deprecated - Optional timestamp for when the orderbook change was recorded (RFC3339).
	std::optional<std::string> ts;
	/// Optional - Unix timestamp for when the orderbook change was recorded (in milliseconds)
	std::optional<std::int64_t> ts_ms;
	/// Optional - Present only when you caused this orderbook change and are using subaccounts.
	std::optional<std::int64_t> subaccount;
};

/// Complete view of the order book's aggregated price levels
struct OrderbookSnapshot {
	/// Unique market identifier
	std::string market_ticker;
	/// Unique market UUID
	std::string market_id;
	/// Optional - This key will not exist if there are no Yes offers in the orderbook.
	std::optional<std::vector<std::array<std::string, 2>>> yes_dollars_fp;
	/// Optional - Same format as "yes_dollars_fp" but for the NO side of the orderbook.
	std::optional<std::vector<std::array<std::string, 2>>> no_dollars_fp;
};

/// Recently streamed Pyth underlying tickers
struct PythUnderlyingList {
	/// Underlying tickers observed on the Pyth stream in the last two hours
	std::vector<std::string> underlying_tickers;
};

/// Deduplicated real-time Pyth price for an underlying ticker
struct PythValue {
	/// Qualified Pyth underlying ticker
	std::string underlying_ticker;
	/// USD value formatted to 8 decimal places
	std::string value_usd;
	/// Pyth source timestamp (unix ms)
	std::int64_t source_ts_ms{};
	/// When Kalshi received the Pyth update (unix ms)
	std::int64_t received_at{};
};

/// Notification when a quote is accepted
struct QuoteAccepted {
	/// Unique identifier for the quote
	std::string quote_id;
	/// Identifier of the RFQ this quote is for
	std::string rfq_id;
	/// Public communications ID of the quote creator (anonymized)
	std::string quote_creator_id;
	/// Public communications ID of the RFQ creator (anonymized)
	std::string rfq_creator_id;
	/// Market ticker for the quote
	std::string market_ticker;
	/// Event ticker (optional)
	std::optional<std::string> event_ticker;
	/// Yes side bid price in dollars
	std::string yes_bid_dollars;
	/// No side bid price in dollars
	std::string no_bid_dollars;
	/// Which side was accepted (yes/no) (optional)
	std::optional<kalshi::Side> accepted_side;
	/// Fixed-point contracts accepted (2 decimals) (optional)
	std::optional<std::string> contracts_accepted_fp;
	/// Fixed-point yes contracts offered (2 decimals) (optional)
	std::optional<std::string> yes_contracts_offered_fp;
	/// Fixed-point no contracts offered (2 decimals) (optional)
	std::optional<std::string> no_contracts_offered_fp;
	/// Target cost from the RFQ in dollars (optional)
	std::optional<std::string> rfq_target_cost_dollars;
	/// Optional - Present only when your side of this quote used a subaccount.
	std::optional<std::int64_t> subaccount;
};

/// Notification when a quote is created on an RFQ
struct QuoteCreated {
	/// Unique identifier for the quote
	std::string quote_id;
	/// Identifier of the RFQ this quote is for
	std::string rfq_id;
	/// Public communications ID of the quote creator (anonymized)
	std::string quote_creator_id;
	/// Public communications ID of the RFQ creator (anonymized)
	std::string rfq_creator_id;
	/// Market ticker for the quote
	std::string market_ticker;
	/// Event ticker (optional)
	std::optional<std::string> event_ticker;
	/// Yes side bid price in dollars
	std::string yes_bid_dollars;
	/// No side bid price in dollars
	std::string no_bid_dollars;
	/// Fixed-point yes contracts offered (2 decimals) (optional)
	std::optional<std::string> yes_contracts_offered_fp;
	/// Fixed-point no contracts offered (2 decimals) (optional)
	std::optional<std::string> no_contracts_offered_fp;
	/// Target cost from the RFQ in dollars (optional)
	std::optional<std::string> rfq_target_cost_dollars;
	/// Timestamp when the quote was created
	std::string created_ts;
	/// Optional - Present only when your side of this quote used a subaccount.
	std::optional<std::int64_t> subaccount;
};

/// Notification when a quote is executed and orders are placed
struct QuoteExecuted {
	/// Unique identifier for the quote that was executed
	std::string quote_id;
	/// Identifier of the RFQ this quote was for
	std::string rfq_id;
	/// Anonymized identifier for the quote creator
	std::string quote_creator_id;
	/// Anonymized identifier for the RFQ creator
	std::string rfq_creator_id;
	/// Your order ID resulting from the quote execution.
	std::string order_id;
	/// Your client order ID for the executed order.
	std::string client_order_id;
	/// Market ticker for the executed quote
	std::string market_ticker;
	/// Timestamp when the quote was executed and orders were placed
	std::string executed_ts;
	/// Optional - Present only when your side of this quote used a subaccount.
	std::optional<std::int64_t> subaccount;
};

struct RfqCreatedMveSelectedLegsItem {
	/// Event ticker for the selected leg
	std::string event_ticker;
	/// Market ticker for the selected leg
	std::string market_ticker;
	/// Side selected for the leg
	kalshi::Side side{};
	/// Yes settlement value in dollars for the selected leg.
	std::optional<std::string> yes_settlement_value_dollars;
};

/// Notification when an RFQ is created
struct RfqCreated {
	/// Unique identifier for the RFQ
	std::string id;
	/// Public communications ID of the RFQ creator (anonymized).
	std::string creator_id;
	/// Market ticker for the RFQ
	std::string market_ticker;
	/// Event ticker (optional)
	std::optional<std::string> event_ticker;
	/// Fixed-point contracts requested (2 decimals) (optional)
	std::optional<std::string> contracts_fp;
	/// Target cost in dollars (optional)
	std::optional<std::string> target_cost_dollars;
	/// Timestamp when the RFQ was created
	std::string created_ts;
	/// Multivariate event collection ticker.
	std::optional<std::string> mve_collection_ticker;
	/// Selected legs for an MVE RFQ.
	std::optional<std::vector<RfqCreatedMveSelectedLegsItem>> mve_selected_legs;
};

/// Notification when an RFQ is deleted
struct RfqDeleted {
	/// Unique identifier for the RFQ
	std::string id;
	/// Public communications ID of the RFQ creator (anonymized)
	std::string creator_id;
	/// Market ticker for the RFQ
	std::string market_ticker;
	/// Event ticker (optional)
	std::optional<std::string> event_ticker;
	/// Fixed-point contracts requested (2 decimals) (optional)
	std::optional<std::string> contracts_fp;
	/// Target cost in dollars (optional)
	std::optional<std::string> target_cost_dollars;
	/// Timestamp when the RFQ was deleted
	std::string deleted_ts;
};

/// Options for subscribe; the client sets the channel.
struct SubscribeParams {
	/// Subscribe to a single market.
	std::optional<std::string> market_ticker;
	/// Subscribe to multiple markets.
	std::vector<std::string> market_tickers;
	/// Subscribe to a single market by UUID (ticker only; mutually exclusive with market_ids and
	/// market_ticker(s))
	std::optional<std::string> market_id;
	/// Subscribe to multiple markets by UUID (ticker only; mutually exclusive with market_id and
	/// market_ticker(s))
	std::vector<std::string> market_ids;
	/// If true, receive an initial snapshot for requested market tickers on the ticker channel
	std::optional<bool> send_initial_snapshot;
	/// If true, OK responses omit the market_tickers/market_ids lists for this subscription
	std::optional<bool> skip_ticker_ack;
	/// Orderbook channel only.
	std::optional<bool> use_yes_price;
	/// Communications channel only.
	std::optional<UserFilter> user_filter;
	/// Number of shards for communications channel fanout (optional)
	std::optional<std::int64_t> shard_factor;
	/// Shard key for communications channel fanout (requires shard_factor)
	std::optional<std::int64_t> shard_key;
	/// cfbenchmarks_value and cfbenchmarks_value_5hz channels only.
	std::vector<std::string> index_ids;
	/// pyth_value channel only.
	std::vector<std::string> underlying_tickers;
};

/// Market price ticker information
struct Ticker {
	/// Unique market UUID
	std::string market_id;
	/// Unique market identifier
	std::string market_ticker;
	/// Last traded price in dollars
	std::string price_dollars;
	/// Best bid price for yes side in dollars
	std::string yes_bid_dollars;
	/// Best ask price for yes side in dollars
	std::string yes_ask_dollars;
	/// Fixed-point total contracts traded (2 decimals)
	std::string volume_fp;
	/// Fixed-point open interest (2 decimals)
	std::string open_interest_fp;
	/// Signed whole-dollar cumulative traded notional
	std::int64_t dollar_volume{};
	/// Signed whole-dollar open-interest notional
	std::int64_t dollar_open_interest{};
	/// Fixed-point contracts at best bid (2 decimals)
	std::string yes_bid_size_fp;
	/// Fixed-point contracts at best ask (2 decimals)
	std::string yes_ask_size_fp;
	/// Fixed-point contracts in last trade (2 decimals)
	std::string last_trade_size_fp;
	/// Deprecated - Unix timestamp for when the update happened (in seconds).
	std::int64_t ts{};
	/// Unix timestamp for when the update happened (in milliseconds)
	std::int64_t ts_ms{};
	/// Deprecated - Timestamp for when the update happened (RFC3339).
	std::string time;
};

/// Public trade information
struct Trade {
	/// Unique identifier for the trade
	std::string trade_id;
	/// Unique market identifier
	std::string market_ticker;
	/// Yes side price in dollars
	std::string yes_price_dollars;
	/// No side price in dollars
	std::string no_price_dollars;
	/// Fixed-point contracts traded (2 decimals)
	std::string count_fp;
	/// Deprecated.
	kalshi::Side taker_side{};
	/// The outcome side the taker is positioned for.
	kalshi::OutcomeSide taker_outcome_side{};
	/// Same directional bit as taker_outcome_side in book vocabulary.
	kalshi::BookSide taker_book_side{};
	/// True if the trade was matched off book as a block trade
	bool is_block_trade{};
	/// Deprecated - Unix timestamp in seconds.
	std::int64_t ts{};
	/// Unix timestamp in milliseconds
	std::int64_t ts_ms{};
};

/// Options for update_subscription; the client sets the subscription.
struct UpdateSubscriptionParams {
	/// Add/remove a single market.
	std::optional<std::string> market_ticker;
	/// Add/remove multiple markets.
	std::vector<std::string> market_tickers;
	/// Add/remove a single market by UUID (ticker only)
	std::optional<std::string> market_id;
	/// Add/remove multiple markets by UUID (ticker only)
	std::vector<std::string> market_ids;
	/// If true, receive an initial snapshot for newly added market tickers on the ticker channel
	std::optional<bool> send_initial_snapshot;
	UpdateAction action{};
	/// CF Benchmarks index IDs to add or remove.
	std::vector<std::string> index_ids;
	/// Pyth underlyings to add or remove.
	std::vector<std::string> underlying_tickers;
};

/// Real-time order updates for authenticated user
struct UserOrder {
	/// Unique order identifier
	std::string order_id;
	/// User identifier
	std::string user_id;
	/// Market ticker for the order
	std::string ticker;
	/// Identifier for the exchange shard where the order resides
	std::int64_t exchange_index{};
	/// Current order status
	kalshi::OrderStatus status{};
	/// Deprecated.
	kalshi::Side side{};
	/// Deprecated.
	bool is_yes{};
	/// The outcome side this order is positioned for.
	kalshi::OutcomeSide outcome_side{};
	/// Same directional bit as outcome_side in book vocabulary.
	kalshi::BookSide book_side{};
	/// Yes price in fixed-point dollars (4 decimals)
	std::string yes_price_dollars;
	/// Number of contracts filled in fixed-point (2 decimals)
	std::string fill_count_fp;
	/// Number of contracts remaining in fixed-point (2 decimals)
	std::string remaining_count_fp;
	/// Initial number of contracts in fixed-point (2 decimals)
	std::string initial_count_fp;
	/// Taker fill cost in fixed-point dollars (6 decimals)
	std::string taker_fill_cost_dollars;
	/// Maker fill cost in fixed-point dollars (6 decimals)
	std::string maker_fill_cost_dollars;
	/// Taker fees in fixed-point dollars (6 decimals).
	std::string taker_fees_dollars;
	/// Maker fees in fixed-point dollars (6 decimals).
	std::string maker_fees_dollars;
	/// Client-provided order identifier
	std::string client_order_id;
	/// Order group identifier, if applicable
	std::optional<std::string> order_group_id;
	/// Self-trade prevention type
	std::optional<kalshi::SelfTradePreventionType> self_trade_prevention_type;
	/// Deprecated - Order creation time in RFC3339 format.
	std::optional<std::string> created_time;
	/// Deprecated - Last update time in RFC3339 format.
	std::optional<std::string> last_update_time;
	/// Deprecated - Order expiration time in RFC3339 format.
	std::optional<std::string> expiration_time;
	/// Order expiration time as a Unix timestamp in milliseconds
	std::optional<std::int64_t> expiration_ts_ms;
	/// Order creation time as a Unix timestamp in milliseconds
	std::optional<std::int64_t> created_ts_ms;
	/// Last update time as a Unix timestamp in milliseconds
	std::optional<std::int64_t> last_updated_ts_ms;
	/// Subaccount number (0 for primary, 1-63 for subaccounts)
	std::optional<std::int64_t> subaccount_number;
};

/// The server confirmed a subscription.
struct Subscribed {
	Subscription subscription;
	std::int64_t sid{0};
};

/// The server ended a subscription after `unsubscribe`.
struct Unsubscribed {
	Subscription subscription;
};

/// An `update_subscription` succeeded. The lists hold what the subscription
/// covers afterwards; market lists are empty when `skip_ticker_ack` was set.
struct Updated {
	Subscription subscription;
	std::vector<std::string> market_tickers;
	std::vector<std::string> market_ids;
	std::vector<std::string> index_ids;
	std::vector<std::string> underlying_tickers;
};

/// One entry of a `list_subscriptions` reply.
struct ListedSubscription {
	std::string channel;
	std::int64_t sid{0};
};

/// The reply to `list_subscriptions`; `id` is the command's ID.
struct SubscriptionList {
	std::int64_t id{0};
	std::vector<ListedSubscription> subscriptions;
};

/// Everything WebSocketClient delivers to on_message.
using Message =
	std::variant<Update<OrderbookSnapshot>, Update<OrderbookDelta>, Update<Ticker>, Update<Trade>,
				 Update<Fill>, Update<MarketPosition>, Update<EventLifecycle>,
				 Update<EventFeeUpdate>, Update<MultivariateMarketLifecycle>, Update<RfqCreated>,
				 Update<RfqDeleted>, Update<QuoteCreated>, Update<QuoteAccepted>,
				 Update<QuoteExecuted>, Update<OrderGroupUpdates>, Update<UserOrder>,
				 Update<CfbenchmarksValue>, Update<CfbenchmarksIndexList>,
				 Update<CfbenchmarksValue5Hz>, Update<Cfbenchmarks5HzIndexList>, Update<PythValue>,
				 Update<PythUnderlyingList>, Update<MarketMetadataUpdated>,
				 Update<MarketLifecycleV2>, Subscribed, Unsubscribed, Updated, SubscriptionList>;
/// Kalshi's name for a WebSocket error code, or an empty string for codes this
/// SDK version does not know.
[[nodiscard]] constexpr std::string_view error_code_name(std::int64_t code) noexcept {
	switch (code) {
		case 1:
			return "Unable to process message";
		case 2:
			return "Params required";
		case 3:
			return "Channels required";
		case 4:
			return "Subscription IDs required";
		case 5:
			return "Unknown command";
		case 7:
			return "Unknown subscription ID";
		case 8:
			return "Unknown channel name";
		case 9:
			return "Authentication required";
		case 10:
			return "Channel error";
		case 11:
			return "Invalid parameter";
		case 12:
			return "Exactly one subscription ID is required";
		case 13:
			return "Unsupported action";
		case 14:
			return "Market Ticker required";
		case 15:
			return "Action required";
		case 18:
			return "Command timeout";
		case 19:
			return "shard_factor must be > 0";
		case 20:
			return "shard_factor is required when shard_key is set";
		case 21:
			return "shard_key must be >= 0 and < shard_factor";
		case 22:
			return "shard_factor must be <= 100";
		case 23:
			return "Match IDs required";
		case 24:
			return "Index IDs required";
		case 25:
			return "Subscription buffer overflow";
		case 26:
			return "Subscription market limit exceeded";
		case 27:
			return "Too many requests";
		case 28:
			return "Underlying tickers required";
		default:
			return "";
	}
}
} // namespace kalshi::ws
