// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
// Every operation reaches its documented method and path, and a request body
// that fails validation never reaches the transport.

#include "kalshi/api.hpp"

#include <gtest/gtest.h>
#include <memory>
#include <string>

#include "support/recording_transport.hpp"

using namespace kalshi; // generated tests name many model types

namespace {

std::string route(const std::string& target) {
	return target.substr(0, target.find('?'));
}

} // namespace

TEST(OperationRoutes, GetExchangeStatus) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<ExchangeStatus> result = client.get_exchange_status();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/exchange/status");
}

TEST(OperationRoutes, GetSeriesFeeChanges) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<SeriesFeeChange>> result =
		client.get_series_fee_changes(GetSeriesFeeChangesParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/series/fee_changes");
}

TEST(OperationRoutes, GetExchangeSchedule) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Schedule> result = client.get_exchange_schedule();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/exchange/schedule");
}

TEST(OperationRoutes, GetUserDataTimestamp) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::string> result = client.get_user_data_timestamp();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/exchange/user_data_timestamp");
}

TEST(OperationRoutes, GetMarketCandlesticks) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetMarketCandlesticksResponse> result =
		client.get_market_candlesticks("p0", "p1", GetMarketCandlesticksParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/series/p0/markets/p1/candlesticks");
}

TEST(OperationRoutes, GetTrades) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetTradesResponse> result = client.get_trades(GetTradesParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/markets/trades");
}

TEST(OperationRoutes, GetMarketOrderbook) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<OrderbookCountFp> result =
		client.get_market_orderbook("p0", GetMarketOrderbookParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/markets/p0/orderbook");
}

TEST(OperationRoutes, GetMarketOrderbooks) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<MarketOrderbookFp>> result =
		client.get_market_orderbooks(GetMarketOrderbooksParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/markets/orderbooks");
}

TEST(OperationRoutes, GetSeries) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Series> result = client.get_series("p0", GetSeriesParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/series/p0");
}

TEST(OperationRoutes, GetSeriesList) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<Series>> result = client.get_series_list(GetSeriesListParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/series");
}

TEST(OperationRoutes, GetMarkets) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetMarketsResponse> result = client.get_markets(GetMarketsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/markets");
}

TEST(OperationRoutes, GetMarket) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Market> result = client.get_market("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/markets/p0");
}

TEST(OperationRoutes, BatchGetMarketCandlesticks) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<MarketCandlesticksResponse>> result =
		client.batch_get_market_candlesticks(BatchGetMarketCandlesticksParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/markets/candlesticks");
}

TEST(OperationRoutes, GetMarketCandlesticksByEvent) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetEventCandlesticksResponse> result =
		client.get_market_candlesticks_by_event("p0", "p1", GetMarketCandlesticksByEventParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/series/p0/events/p1/candlesticks");
}

TEST(OperationRoutes, GetEvents) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetEventsResponse> result = client.get_events(GetEventsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/events");
}

TEST(OperationRoutes, GetMultivariateEvents) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetMultivariateEventsResponse> result =
		client.get_multivariate_events(GetMultivariateEventsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/events/multivariate");
}

TEST(OperationRoutes, GetEventFeeChanges) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetEventFeeChangesResponse> result =
		client.get_event_fee_changes(GetEventFeeChangesParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/events/fee_changes");
}

TEST(OperationRoutes, GetEvent) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetEventResponse> result = client.get_event("p0", GetEventParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/events/p0");
}

TEST(OperationRoutes, GetEventMetadata) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetEventMetadataResponse> result = client.get_event_metadata("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/events/p0/metadata");
}

TEST(OperationRoutes, GetEventForecastPercentilesHistory) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<ForecastPercentilesPoint>> result =
		client.get_event_forecast_percentiles_history("p0", "p1",
													  GetEventForecastPercentilesHistoryParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/series/p0/events/p1/forecast_percentile_history");
}

TEST(OperationRoutes, GetOrders) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetOrdersResponse> result = client.get_orders(GetOrdersParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/orders");
}

TEST(OperationRoutes, GetOrder) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Order> result = client.get_order("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/orders/p0");
}

TEST(OperationRoutes, GetOrderQueuePositions) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<OrderQueuePosition>> result =
		client.get_order_queue_positions(GetOrderQueuePositionsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/orders/queue_positions");
}

TEST(OperationRoutes, GetOrderQueuePosition) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<FixedPointCount> result = client.get_order_queue_position("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/orders/p0/queue_position");
}

TEST(OperationRoutes, CreateOrderV2) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<CreateOrderV2Response> result = client.create_order(CreateOrderV2Request{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, CancelAllOrders) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.cancel_all_orders(CancelAllOrdersParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/portfolio/events/orders");
}

TEST(OperationRoutes, BatchCreateOrdersV2) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<BatchCreateOrdersV2ResponseOrdersItem>> result =
		client.batch_create_orders(BatchCreateOrdersV2Request{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/portfolio/events/orders/batched");
}

TEST(OperationRoutes, BatchCancelOrdersV2) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<BatchCancelOrdersV2ResponseOrdersItem>> result =
		client.batch_cancel_orders(BatchCancelOrdersV2Request{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/portfolio/events/orders/batched");
}

TEST(OperationRoutes, CancelOrderV2) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<CancelOrderV2Response> result = client.cancel_order("p0", CancelOrderParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/portfolio/events/orders/p0");
}

TEST(OperationRoutes, AmendOrderV2) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<AmendOrderV2Response> result =
		client.amend_order("p0", AmendOrderV2Request{}, AmendOrderParams{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, DecreaseOrderV2) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<DecreaseOrderV2Response> result =
		client.decrease_order("p0", DecreaseOrderV2Request{}, DecreaseOrderParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/portfolio/events/orders/p0/decrease");
}

TEST(OperationRoutes, GetOrderGroups) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::optional<std::vector<OrderGroup>>> result =
		client.get_order_groups(GetOrderGroupsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/order_groups");
}

TEST(OperationRoutes, CreateOrderGroup) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<CreateOrderGroupResponse> result =
		client.create_order_group(CreateOrderGroupRequest{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/portfolio/order_groups/create");
}

TEST(OperationRoutes, GetOrderGroup) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetOrderGroupResponse> result =
		client.get_order_group("p0", GetOrderGroupParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/order_groups/p0");
}

TEST(OperationRoutes, DeleteOrderGroup) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.delete_order_group("p0", DeleteOrderGroupParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/portfolio/order_groups/p0");
}

TEST(OperationRoutes, ResetOrderGroup) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.reset_order_group("p0", ResetOrderGroupParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::PUT);
	EXPECT_EQ(route(transport->target), "/portfolio/order_groups/p0/reset");
}

TEST(OperationRoutes, TriggerOrderGroup) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.trigger_order_group("p0", TriggerOrderGroupParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::PUT);
	EXPECT_EQ(route(transport->target), "/portfolio/order_groups/p0/trigger");
}

TEST(OperationRoutes, UpdateOrderGroupLimit) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.update_order_group_limit(
		"p0", UpdateOrderGroupLimitRequest{}, UpdateOrderGroupLimitParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::PUT);
	EXPECT_EQ(route(transport->target), "/portfolio/order_groups/p0/limit");
}

TEST(OperationRoutes, GetBalance) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetBalanceResponse> result = client.get_balance(GetBalanceParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/balance");
}

TEST(OperationRoutes, IntraExchangeInstanceTransfer) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::string> result =
		client.intra_exchange_instance_transfer(IntraExchangeInstanceTransferRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, GetIntraExchangeInstanceTransfers) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetIntraExchangeInstanceTransfersResponse> result =
		client.get_intra_exchange_instance_transfers(GetIntraExchangeInstanceTransfersParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/intra_exchange_instance_transfers");
}

TEST(OperationRoutes, GetIntraExchangeInstanceTransfer) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<IntraExchangeInstanceTransfer> result =
		client.get_intra_exchange_instance_transfer("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/intra_exchange_instance_transfers/p0");
}

TEST(OperationRoutes, CreateSubaccount) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::int64_t> result = client.create_subaccount(CreateSubaccountRequest{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/portfolio/subaccounts");
}

TEST(OperationRoutes, ApplySubaccountTransfer) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.apply_subaccount_transfer(ApplySubaccountTransferRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, GetSubaccountBalances) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<SubaccountBalance>> result = client.get_subaccount_balances();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/subaccounts/balances");
}

TEST(OperationRoutes, GetSubaccountTransfers) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetSubaccountTransfersResponse> result =
		client.get_subaccount_transfers(GetSubaccountTransfersParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/subaccounts/transfers");
}

TEST(OperationRoutes, GetSubaccountNetting) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<SubaccountNettingConfig>> result = client.get_subaccount_netting();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/subaccounts/netting");
}

TEST(OperationRoutes, UpdateSubaccountNetting) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.update_subaccount_netting(UpdateSubaccountNettingRequest{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::PUT);
	EXPECT_EQ(route(transport->target), "/portfolio/subaccounts/netting");
}

TEST(OperationRoutes, GetPositions) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetPositionsResponse> result = client.get_positions(GetPositionsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/positions");
}

TEST(OperationRoutes, GetSettlements) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetSettlementsResponse> result = client.get_settlements(GetSettlementsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/settlements");
}

TEST(OperationRoutes, GetDeposits) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetDepositsResponse> result = client.get_deposits(GetDepositsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/deposits");
}

TEST(OperationRoutes, GetWithdrawals) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetWithdrawalsResponse> result = client.get_withdrawals(GetWithdrawalsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/withdrawals");
}

TEST(OperationRoutes, GetPortfolioRestingOrderTotalValue) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetPortfolioRestingOrderTotalValueResponse> result =
		client.get_portfolio_resting_order_total_value();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/summary/total_resting_order_value");
}

TEST(OperationRoutes, GetFills) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetFillsResponse> result = client.get_fills(GetFillsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/fills");
}

TEST(OperationRoutes, GetCommunicationsID) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::string> result = client.get_communications_id();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/communications/id");
}

TEST(OperationRoutes, GetBlockTradeProposals) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetBlockTradeProposalsResponse> result =
		client.get_block_trade_proposals(GetBlockTradeProposalsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/communications/block-trade-proposals");
}

TEST(OperationRoutes, ProposeBlockTrade) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::string> result = client.propose_block_trade(ProposeBlockTradeRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, AcceptBlockTradeProposal) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result =
		client.accept_block_trade_proposal("p0", AcceptBlockTradeProposalRequest{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/communications/block-trade-proposals/p0/accept");
}

TEST(OperationRoutes, GetRFQs) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetRFQsResponse> result = client.get_rfqs(GetRfqsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/communications/rfqs");
}

TEST(OperationRoutes, CreateRFQ) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::string> result = client.create_rfq(CreateRFQRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, GetRFQ) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<RFQ> result = client.get_rfq("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/communications/rfqs/p0");
}

TEST(OperationRoutes, DeleteRFQ) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.delete_rfq("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/communications/rfqs/p0");
}

TEST(OperationRoutes, GetRFQQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Quote> result = client.get_rfq_quote("p0", "p1");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/communications/rfqs/p0/quotes/p1");
}

TEST(OperationRoutes, DeleteRFQQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.delete_rfq_quote("p0", "p1");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/communications/rfqs/p0/quotes/p1");
}

TEST(OperationRoutes, AcceptRFQQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.accept_rfq_quote("p0", "p1", AcceptQuoteRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, ConfirmRFQQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.confirm_rfq_quote("p0", "p1");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::PUT);
	EXPECT_EQ(route(transport->target), "/communications/rfqs/p0/quotes/p1/confirm");
}

TEST(OperationRoutes, GetQuotes) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetQuotesResponse> result = client.get_quotes(GetQuotesParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/communications/quotes");
}

TEST(OperationRoutes, CreateQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::string> result = client.create_quote(CreateQuoteRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, GetQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Quote> result = client.get_quote("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/communications/quotes/p0");
}

TEST(OperationRoutes, DeleteQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.delete_quote("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/communications/quotes/p0");
}

TEST(OperationRoutes, AcceptQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.accept_quote("p0", AcceptQuoteRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, ConfirmQuote) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.confirm_quote("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::PUT);
	EXPECT_EQ(route(transport->target), "/communications/quotes/p0/confirm");
}

TEST(OperationRoutes, GetApiKeys) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetApiKeysResponse> result = client.get_api_keys(GetApiKeysParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/api_keys");
}

TEST(OperationRoutes, CreateApiKey) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<CreateApiKeyResponse> result = client.create_api_key(CreateApiKeyRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, GenerateApiKey) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GenerateApiKeyResponse> result = client.generate_api_key(GenerateApiKeyRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, DeleteApiKey) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.delete_api_key("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/api_keys/p0");
}

TEST(OperationRoutes, GetAccountApiLimits) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetAccountApiLimitsResponse> result = client.get_account_api_limits();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/account/limits");
}

TEST(OperationRoutes, UpgradeAccountApiUsageLevel) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result = client.upgrade_account_api_usage_level();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/account/api_usage_level/upgrade");
}

TEST(OperationRoutes, GetAccountApiUsageLevelVolumeProgress) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<AccountApiUsageLevelVolumeProgress>> result =
		client.get_account_api_usage_level_volume_progress();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/account/api_usage_level/volume_progress");
}

TEST(OperationRoutes, GetAccountEndpointCosts) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetAccountEndpointCostsResponse> result = client.get_account_endpoint_costs();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/account/endpoint_costs");
}

TEST(OperationRoutes, GetTagsForSeriesCategories) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::map<std::string, std::vector<std::string>>> result =
		client.get_tags_for_series_categories();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/search/tags_by_categories");
}

TEST(OperationRoutes, GetFiltersForSports) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetFiltersBySportsResponse> result = client.get_filters_for_sports();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/search/filters_by_sport");
}

TEST(OperationRoutes, GetLiveDataByMilestone) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<LiveData> result =
		client.get_live_data_by_milestone("p0", GetLiveDataByMilestoneParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/live_data/milestone/p0");
}

TEST(OperationRoutes, GetLiveData) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<LiveData> result = client.get_live_data("p0", "p1", GetLiveDataParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/live_data/p0/milestone/p1");
}

TEST(OperationRoutes, GetLiveDatas) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<LiveData>> result = client.get_live_datas(GetLiveDatasParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/live_data/batch");
}

TEST(OperationRoutes, GetGameStats) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::optional<PlayByPlay>> result = client.get_game_stats("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/live_data/milestone/p0/game_stats");
}

TEST(OperationRoutes, GetEventLiveData) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<EventLiveData> result = client.get_event_live_data("p0", GetEventLiveDataParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/live_data/events/p0");
}

TEST(OperationRoutes, GetWeatherIndex) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetWeatherIndexResponse> result =
		client.get_weather_index("p0", GetWeatherIndexParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/live_data/weather/p0");
}

TEST(OperationRoutes, GetWeatherIndexCalibrations) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetWeatherIndexCalibrationsResponse> result =
		client.get_weather_index_calibrations("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/live_data/weather/p0/calibrations");
}

TEST(OperationRoutes, GetStructuredTargets) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetStructuredTargetsResponse> result =
		client.get_structured_targets(GetStructuredTargetsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/structured_targets");
}

TEST(OperationRoutes, GetStructuredTarget) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::optional<StructuredTarget>> result = client.get_structured_target("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/structured_targets/p0");
}

TEST(OperationRoutes, GetMilestone) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Milestone> result = client.get_milestone("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/milestones/p0");
}

TEST(OperationRoutes, GetMilestones) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetMilestonesResponse> result = client.get_milestones(GetMilestonesParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/milestones");
}

TEST(OperationRoutes, GetMultivariateEventCollection) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<MultivariateEventCollection> result =
		client.get_multivariate_event_collection("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/multivariate_event_collections/p0");
}

TEST(OperationRoutes, CreateMarketInMultivariateEventCollection) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<CreateMarketInMultivariateEventCollectionResponse> result =
		client.create_market_in_multivariate_event_collection(
			"p0", CreateMarketInMultivariateEventCollectionRequest{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/multivariate_event_collections/p0");
}

TEST(OperationRoutes, GetMultivariateEventCollections) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetMultivariateEventCollectionsResponse> result =
		client.get_multivariate_event_collections(GetMultivariateEventCollectionsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/multivariate_event_collections");
}

TEST(OperationRoutes, GetIncentivePrograms) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetIncentiveProgramsResponse> result =
		client.get_incentive_programs(GetIncentiveProgramsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/incentive_programs");
}

TEST(OperationRoutes, GetFCMFills) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetFcmFillsResponse> result = client.get_fcm_fills(GetFcmFillsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/fcm/fills");
}

TEST(OperationRoutes, GetFCMOrders) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetOrdersResponse> result = client.get_fcm_orders(GetFcmOrdersParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/fcm/orders");
}

TEST(OperationRoutes, ListFCMSubtraders) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<FCMSubtrader>> result = client.get_fcm_subtraders();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/fcm/subtraders");
}

TEST(OperationRoutes, CreateFCMSubtrader) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::string> result = client.create_fcm_subtrader(CreateFCMSubtraderRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, GetFCMEventContractDailyCap) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetFCMEventContractDailyCapResponse> result =
		client.get_fcm_event_contract_daily_cap(GetFcmEventContractDailyCapParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/fcm/subtraders/event_contract_daily_cap");
}

TEST(OperationRoutes, UpdateFCMEventContractDailyCap) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result =
		client.update_fcm_event_contract_daily_cap(UpdateFCMEventContractDailyCapRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, DeleteFCMEventContractDailyCap) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result =
		client.delete_fcm_event_contract_daily_cap(DeleteFcmEventContractDailyCapParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::DEL);
	EXPECT_EQ(route(transport->target), "/fcm/subtraders/event_contract_daily_cap");
}

TEST(OperationRoutes, GetFCMSubtraderBlockedCategories) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<std::string>> result =
		client.get_fcm_subtrader_blocked_categories(GetFcmSubtraderBlockedCategoriesParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/fcm/subtraders/blocked_categories");
}

TEST(OperationRoutes, UpdateFCMSubtraderBlockedCategories) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<std::vector<std::string>> result = client.update_fcm_subtrader_blocked_categories(
		UpdateFCMSubtraderBlockedCategoriesRequest{});
	ASSERT_FALSE(result.has_value());
	EXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);
	EXPECT_EQ(transport->calls, 0);
}

TEST(OperationRoutes, GetTargetBalanceAllocation) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetTargetBalanceAllocationResponse> result =
		client.get_target_balance_allocation();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/portfolio/target_balance_allocation");
}

TEST(OperationRoutes, SetTargetBalanceAllocation) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<void> result =
		client.set_target_balance_allocation(SetTargetBalanceAllocationRequest{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::POST);
	EXPECT_EQ(route(transport->target), "/portfolio/target_balance_allocation");
}

TEST(OperationRoutes, GetFCMPositions) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetPositionsResponse> result = client.get_fcm_positions(GetFcmPositionsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/fcm/positions");
}

TEST(OperationRoutes, GetHistoricalCutoff) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetHistoricalCutoffResponse> result = client.get_historical_cutoff();
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/cutoff");
}

TEST(OperationRoutes, GetMarketCandlesticksHistorical) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetMarketCandlesticksHistoricalResponse> result =
		client.get_market_candlesticks_historical("p0", GetMarketCandlesticksHistoricalParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/markets/p0/candlesticks");
}

TEST(OperationRoutes, GetFillsHistorical) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetFillsResponse> result = client.get_fills_historical(GetFillsHistoricalParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/fills");
}

TEST(OperationRoutes, GetHistoricalOrders) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetOrdersResponse> result =
		client.get_historical_orders(GetHistoricalOrdersParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/orders");
}

TEST(OperationRoutes, GetHistoricalPositions) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetPositionsResponse> result =
		client.get_historical_positions(GetHistoricalPositionsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/positions");
}

TEST(OperationRoutes, GetTradesHistorical) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetTradesResponse> result =
		client.get_trades_historical(GetTradesHistoricalParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/trades");
}

TEST(OperationRoutes, GetHistoricalMarkets) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<GetMarketsResponse> result =
		client.get_historical_markets(GetHistoricalMarketsParams{});
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/markets");
}

TEST(OperationRoutes, GetHistoricalMarket) {
	const std::shared_ptr<kalshi::test::RecordingTransport> transport =
		std::make_shared<kalshi::test::RecordingTransport>();
	kalshi::KalshiClient client(transport);
	const Result<Market> result = client.get_historical_market("p0");
	EXPECT_TRUE(result.has_value());
	EXPECT_EQ(transport->method, kalshi::HttpMethod::GET);
	EXPECT_EQ(route(transport->target), "/historical/markets/p0");
}
