#!/usr/bin/env python3
"""Generates the typed REST client and WebSocket messages from spec/.

    python3 tools/codegen/generate.py          # rewrite the generated files
    python3 tools/codegen/generate.py --check  # exit 1 if they are out of date

Needs PyYAML (`python3-yaml`, or pip in a virtual environment). Generated files start with a
"Generated by" banner; edit this script, not them.

Mapping rules:
- Component schemas become structs with the same name and member names, so
  Glaze reads and writes them by reflection. Nested inline objects become
  structs named after their parent and property.
- Required, non-nullable properties are plain members; everything else is
  std::optional, which also keeps absent fields out of request bodies.
- String enums become `enum class` types with an `Unknown` value, so a new
  server value never fails a response. Identical value sets share one type.
- Free-form objects become RawJson. Integers are int64.
- Each operation becomes a KalshiClient method named after its operationId.
  Path parameters are arguments, query parameters are a `...Params` struct,
  and a JSON body is its request schema. Responses with a single property are
  unwrapped to that property's type.

tools/codegen/ws.py maps spec/asyncapi.yaml the same way.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - guidance for developers
    sys.exit("PyYAML is required: install python3-yaml, or pip install pyyaml in a virtual environment")

from common import (CPP_RESERVED, ROOT, EnumType, Member, StructType, check_enums, clang_format,
                    doc_lines, emit_enum, emit_enum_adapter, emit_enum_parser, emit_struct,
                    first_sentence, ordered_structs, pascal, ref_name, snake)
from ws import WS_SPEC, WsGenerator

SPEC = ROOT / "spec" / "openapi.yaml"
BANNER = "// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.\n"

HTTP_METHODS = ("get", "post", "put", "delete")

# Methods whose operationId carries a version suffix the SDK does not need.
METHOD_RENAMES = {
    "CreateOrderV2": "create_order",
    "CancelOrderV2": "cancel_order",
    "AmendOrderV2": "amend_order",
    "DecreaseOrderV2": "decrease_order",
    "BatchCreateOrdersV2": "batch_create_orders",
    "BatchCancelOrdersV2": "batch_cancel_orders",
    "ListFCMSubtraders": "get_fcm_subtraders",
}

# Property names too generic to name an enum on their own.
GENERIC_ENUM_PROPERTIES = {"status", "type", "result", "market_result", "filter", "incentive_type"}

# Shared names for common inline enum value sets.
ENUM_NAMES_BY_VALUES = {
    frozenset({"yes", "no"}): "Side",
    frozenset({"buy", "sell"}): "Action",
}


@dataclass
class Operation:
    operation_id: str
    method_name: str
    http_method: str
    path: str
    tag: str
    summary: str
    deprecated: bool
    path_params: list[str]
    params_struct: StructType | None
    query: list[tuple[str, Member]]
    body_type: str | None
    empty_body: bool  # the operation takes an empty JSON object
    response_type: str | None  # None means Result<void>
    unwrap_member: str | None


class Generator:
    def __init__(self, spec: dict) -> None:
        self.spec = spec
        self.schemas: dict = spec["components"]["schemas"]
        self.parameters: dict = spec["components"].get("parameters", {})
        self.enums: dict[str, EnumType] = {}
        self.enum_by_values: dict[frozenset, str] = {}
        self.structs: dict[str, StructType] = {}
        self.aliases: dict[str, str] = {}
        self.operations: list[Operation] = []
        self.request_bodies: set[str] = set()

    # ----- types -----------------------------------------------------------

    def run(self) -> None:
        for name, schema in self.schemas.items():
            if "enum" in schema:
                self.enum_for(schema["enum"], name, schema.get("description", ""), fixed=name)
            elif schema.get("type") in ("string", "integer", "number", "boolean"):
                self.aliases[name] = self.primitive(schema)
        for name, schema in self.schemas.items():
            if schema.get("type") == "array":
                inner, _, _, _ = self.type_of(schema.get("items", {}), name + "Item")
                size = schema.get("minItems")
                fixed = size is not None and size == schema.get("maxItems")
                self.aliases[name] = f"std::array<{inner}, {size}>" if fixed else f"std::vector<{inner}>"
        for name, schema in self.schemas.items():
            empty = schema.get("type") == "object" and not schema.get("properties") and not schema.get("additionalProperties")
            if name not in self.enums and name not in self.aliases and not empty:
                self.struct_for(name, schema)
        for path, item in self.spec["paths"].items():
            for method in HTTP_METHODS:
                if method in item:
                    self.operation(path, method, item[method], item.get("parameters", []))
        check_enums(self.enums)

    def enum_for(self, values: list, context: str, doc: str, fixed: str | None = None,
                 prop: str = "") -> str:
        key = frozenset(values)
        if fixed:
            self.enums[fixed] = EnumType(fixed, list(values), first_sentence(doc))
            self.enum_by_values.setdefault(key, fixed)
            return fixed
        # A named enum whose name matches the property (outcome_side ->
        # OutcomeSide) wins over the shared names below.
        for enum in self.enums.values():
            if frozenset(enum.values) == key and prop and prop.endswith(snake(enum.name)):
                return enum.name
        name = ENUM_NAMES_BY_VALUES.get(key)
        if name in self.enums:
            return name
        if name is None and key in self.enum_by_values:
            return self.enum_by_values[key]
        if name is None:
            specific = prop and prop not in GENERIC_ENUM_PROPERTIES and not prop.endswith("_filter")
            name = pascal(prop) if specific and pascal(prop) not in self.enums else context
        while name in self.enums or name in self.schemas:
            name += "Value"
        self.enums[name] = EnumType(name, list(values), first_sentence(doc))
        self.enum_by_values.setdefault(key, name)
        return name

    @staticmethod
    def primitive(schema: dict) -> str:
        kind = schema.get("type")
        if kind == "integer":
            return "std::int64_t"
        if kind == "number":
            return "double"
        if kind == "boolean":
            return "bool"
        return "std::string"

    def unwrap(self, schema: dict) -> dict:
        while "allOf" in schema and len(schema["allOf"]) == 1:
            nullable = schema.get("nullable", False)
            schema = dict(schema["allOf"][0], nullable=nullable or schema["allOf"][0].get("nullable", False))
        return schema

    def type_of(self, schema: dict, context: str, prop: str = "") -> tuple[str, str, str, bool]:
        """Returns (cpp type, kind, element name, fixed_point)."""
        schema = self.unwrap(schema)
        if "$ref" in schema:
            name = ref_name(schema["$ref"])
            if name in self.enums:
                return name, "enum", name, False
            if name in self.aliases:
                kind = "string" if self.aliases[name] == "std::string" else "scalar"
                if self.aliases[name].startswith(("std::array", "std::vector")):
                    kind = "container"
                return name, kind, "", name.startswith("FixedPoint")
            return name, "struct", name, False
        if "enum" in schema and schema.get("type", "string") == "string":
            name = self.enum_for(schema["enum"], context, schema.get("description", ""), prop=prop)
            return name, "enum", name, False
        kind = schema.get("type")
        if kind == "array":
            inner, inner_kind, element, _ = self.type_of(schema.get("items", {}), context + "Item", prop)
            return f"std::vector<{inner}>", "vector", element if inner_kind in ("struct", "enum") else "", False
        if kind == "object" or "properties" in schema or "additionalProperties" in schema or not kind:
            if schema.get("properties"):
                self.struct_for(context, schema)
                return context, "struct", context, False
            extra = schema.get("additionalProperties")
            if isinstance(extra, dict) and extra:
                inner, _, element, _ = self.type_of(extra, context + "Value")
                return f"std::map<std::string, {inner}>", "map", element, False
            return "RawJson", "raw", "", False
        return self.primitive(schema), "string" if kind == "string" else "scalar", "", False

    def member(self, owner: str, json_name: str, schema: dict, required: bool) -> Member:
        schema_u = self.unwrap(schema)
        cpp, kind, element, fixed = self.type_of(schema, owner + pascal(json_name), json_name)
        nullable = bool(schema_u.get("nullable")) or bool(schema.get("nullable"))
        plain = required and not nullable
        if json_name in CPP_RESERVED:
            raise SystemExit(f"{owner}.{json_name} needs a rename; add glz::meta support first")
        return Member(
            json_name=json_name,
            cpp_type=cpp if plain else f"std::optional<{cpp}>",
            doc=schema.get("description") or schema_u.get("description", ""),
            fixed_point=fixed,
            required=plain,
            base_kind=kind,
            element=element,
        )

    def struct_for(self, name: str, schema: dict) -> StructType:
        if name in self.structs:
            return self.structs[name]
        struct = StructType(name, doc=first_sentence(schema.get("description")))
        self.structs[name] = struct
        required = set(schema.get("required", []))
        for json_name, prop in schema.get("properties", {}).items():
            struct.members.append(self.member(name, json_name, prop, json_name in required))
        return struct

    # ----- operations ------------------------------------------------------

    def parameter(self, param: dict) -> dict:
        return self.parameters[ref_name(param["$ref"])] if "$ref" in param else param

    def operation(self, path: str, method: str, op: dict, shared: list) -> None:
        op_id = op["operationId"]
        method_name = METHOD_RENAMES.get(op_id, snake(op_id))
        params = [self.parameter(p) for p in shared + op.get("parameters", [])]
        path_params = [p["name"] for p in params if p["in"] == "path"]
        in_path = re.findall(r"{([^}]+)}", path)
        if sorted(path_params) != sorted(in_path):
            raise SystemExit(f"{op_id}: path parameters {path_params} do not match {path}")
        query_params = [p for p in params if p["in"] == "query"]
        params_struct = None
        query: list[tuple[str, Member]] = []
        if query_params:
            params_struct = StructType(pascal(method_name) + "Params", doc=f"Query parameters for `{method_name}`.")
            for p in query_params:
                schema = dict(p.get("schema", {}))
                if not schema.get("description") and p.get("description"):
                    schema["description"] = p["description"]
                m = self.member(pascal(method_name), p["name"], schema, bool(p.get("required")))
                if m.base_kind == "vector":
                    m.cpp_type = m.cpp_type.removeprefix("std::optional<").removesuffix(">") if not m.required else m.cpp_type
                params_struct.members.append(m)
                query.append((p["name"], m))
            self.structs[params_struct.name] = params_struct

        body_type = None
        empty_body = False
        if "requestBody" in op:
            content = op["requestBody"].get("content", {}).get("application/json", {})
            schema = content.get("schema", {})
            if "$ref" in schema and ref_name(schema["$ref"]) in self.structs:
                body_type = ref_name(schema["$ref"])
                self.request_bodies.add(body_type)
            else:
                empty_body = True

        response_type, unwrap_member = None, None
        responses = op.get("responses", {})
        ok = next((code for code in ("200", "201", "204") if code in responses), None)
        if ok and ok != "204":
            schema = responses[ok].get("content", {}).get("application/json", {}).get("schema", {})
            if "$ref" in schema:
                name = ref_name(schema["$ref"])
                target = self.schemas[name]
                props = target.get("properties", {})
                if target.get("type") == "object" and not props:
                    response_type = None
                elif len(props) == 1:
                    struct = self.structs[name]
                    unwrap_member = struct.members[0].json_name
                    response_type = struct.members[0].cpp_type
                else:
                    response_type = name

        self.operations.append(Operation(
            operation_id=op_id,
            method_name=method_name,
            http_method=method.upper(),
            path=path,
            tag=(op.get("tags") or ["misc"])[0],
            summary=first_sentence(op.get("summary") or op.get("description")),
            deprecated=bool(op.get("deprecated")),
            path_params=in_path,
            params_struct=params_struct,
            query=query,
            body_type=body_type,
            empty_body=empty_body,
            response_type=response_type,
            unwrap_member=unwrap_member,
        ))

    # ----- emission --------------------------------------------------------

    def ordered_structs(self) -> list[StructType]:
        return ordered_structs(self.structs)

    def models_header(self) -> str:
        out = [BANNER, "#pragma once\n\n#include \"kalshi/raw_json.hpp\"\n\n",
               "#include <array>\n#include <cstdint>\n#include <map>\n#include <optional>\n#include <string>\n",
               "#include <string_view>\n#include <vector>\n\nnamespace kalshi {\n\n"]
        out.append("// ----- Scalars ----------------------------------------------------------\n\n")
        for name, cpp in sorted(self.aliases.items()):
            out.extend(line + "\n" for line in doc_lines(self.schemas[name].get("description", ""), ""))
            out.append(f"using {name} = {cpp};\n\n")
        out.append("// ----- Enums ------------------------------------------------------------\n\n")
        for enum in sorted(self.enums.values(), key=lambda e: e.name):
            out.append(emit_enum(enum))
        out.append("// ----- Models -----------------------------------------------------------\n\n")
        for struct in self.ordered_structs():
            out.append(emit_struct(struct))
        out.append("} // namespace kalshi\n")
        return "".join(out)

    @staticmethod
    def result_type(op: Operation) -> str:
        return f"Result<{op.response_type}>" if op.response_type else "Result<void>"

    def signature(self, op: Operation, qualified: bool) -> str:
        result = self.result_type(op)
        args = [f"std::string_view {name}" for name in op.path_params]
        if op.body_type:
            args.append(f"const {op.body_type}& body")
        if op.params_struct:
            needs_value = any(m.required for m in op.params_struct.members)
            default = "" if needs_value or qualified else " = {}"
            args.append(f"const {op.params_struct.name}& params{default}")
        scope = "KalshiClient::" if qualified else ""
        return f"{result} {scope}{op.method_name}({', '.join(args)})"

    def api_declarations(self) -> str:
        out: list[str] = []
        by_tag: dict[str, list[Operation]] = {}
        for op in self.operations:
            by_tag.setdefault(op.tag, []).append(op)
        for tag in sorted(by_tag):
            out.append(f"\t// ----- {tag} " + "-" * max(4, 66 - len(tag)) + "\n\n")
            for op in by_tag[tag]:
                out.extend(line + "\n" for line in doc_lines(re.sub(r"\s*\(V\d\)$", "", op.summary), "\t"))
                out.append(f"\t/// `{op.http_method} {op.path}`\n")
                attrs = "[[nodiscard]] "
                if op.deprecated:
                    attrs = '[[deprecated("deprecated by Kalshi")]] ' + attrs
                out.append(f"\t{attrs}{self.signature(op, qualified=False)};\n\n")
        return "".join(out)

    def operations_source(self, tag: str, ops: list[Operation]) -> str:
        out = [BANNER, '#include "kalshi/api.hpp"\n\n#include "../support.hpp"\n#include "../validate.hpp"\n\n',
               "namespace kalshi {\n\n"]
        for op in ops:
            out.append(self.signature(op, qualified=True) + " {\n")
            if op.body_type and self.needs_validation(op.body_type):
                out.append(f"\tif (Result<void> valid = detail::validate(body); !valid) {{\n"
                           f"\t\treturn std::unexpected(std::move(valid.error()));\n\t}}\n")
            if op.path_params:
                values = ", ".join(op.path_params)
                out.append(f'\tResult<std::string> target = detail::expand_path("{op.path}", {{{values}}});\n'
                           "\tif (!target) {\n\t\treturn std::unexpected(std::move(target.error()));\n\t}\n")
                target = "*target"
            else:
                target = f'std::string{{"{op.path}"}}'
            if op.query:
                out.append(f"\tdetail::Query query({target});\n")
                for name, m in op.query:
                    out.append(f'\tquery.add("{name}", params.{name});\n')
                target = "std::move(query).str()"
            body = "detail::encode(body)" if op.body_type else ('std::string{"{}"}' if op.empty_body else "{}")
            call = f'impl_->send(HttpMethod::{"DEL" if op.http_method == "DELETE" else op.http_method}, {target}, {body}, "{op.method_name}")'
            if op.response_type is None:
                out.append(f"\treturn detail::expect_success({call});\n")
            elif op.unwrap_member:
                wrapper = self.structs_for_unwrap(op)
                out.append(f"\tResult<{wrapper}> response = detail::decode<{wrapper}>({call});\n"
                           "\tif (!response) {\n\t\treturn std::unexpected(std::move(response.error()));\n\t}\n"
                           f"\treturn {self.take(op.response_type, f'response->{op.unwrap_member}')};\n")
            else:
                out.append(f"\treturn detail::decode<{op.response_type}>({call});\n")
            out.append("}\n\n")
        out.append("} // namespace kalshi\n")
        return "".join(out)

    def take(self, cpp_type: str, expr: str) -> str:
        """Moves out of `expr` unless the type is trivially copyable."""
        trivial = cpp_type in ("std::int64_t", "double", "bool") or cpp_type in self.enums
        return expr if trivial else f"std::move({expr})"

    def structs_for_unwrap(self, op: Operation) -> str:
        path_item = self.spec["paths"][op.path][op.http_method.lower()]
        responses = path_item["responses"]
        ok = next(code for code in ("200", "201") if code in responses)
        return ref_name(responses[ok]["content"]["application/json"]["schema"]["$ref"])

    # Validation of request bodies: fixed-point strings parse, required enums
    # are set, and required strings are non-empty.

    def needs_validation(self, name: str, seen: set[str] | None = None) -> bool:
        seen = seen or set()
        if name in seen or name not in self.structs:
            return False
        seen.add(name)
        for m in self.structs[name].members:
            if m.fixed_point or (m.required and m.base_kind in ("enum", "string")):
                return True
            if m.base_kind in ("struct", "vector") and m.element in self.structs and self.needs_validation(m.element, seen):
                return True
        return False

    def default_is_invalid(self, name: str) -> bool:
        """Whether a default-constructed body fails validation."""
        return any(m.required and (m.fixed_point or m.base_kind in ("enum", "string"))
                   for m in self.structs[name].members)

    def validate_header(self) -> str:
        names: list[str] = []
        pending = sorted(self.request_bodies)
        while pending:
            name = pending.pop()
            if name in names or not self.needs_validation(name):
                continue
            names.append(name)
            for m in self.structs[name].members:
                if m.element in self.structs:
                    pending.append(m.element)
        order = [s.name for s in self.ordered_structs() if s.name in names]
        out = [BANNER, "#pragma once\n\n#include \"kalshi/api.hpp\"\n#include \"kalshi/fixed_point.hpp\"\n\n",
               "#include <string>\n#include <string_view>\n\nnamespace kalshi::detail {\n\n",
               "inline Result<void> invalid(std::string_view type, std::string_view field, std::string_view why) {\n"
               "\treturn std::unexpected(Error{ErrorCode::InvalidRequest,\n"
               "\t\t\t\t\t\t\t\t std::string(type) + \".\" + std::string(field) + \" \" + std::string(why)});\n}\n\n"]
        for name in order:
            out.append(f"inline Result<void> validate(const {name}& value);\n")
        out.append("\n")
        for name in order:
            out.append(f"inline Result<void> validate(const {name}& value) {{\n")
            for m in self.structs[name].members:
                access = f"value.{m.json_name}"
                opt = not m.required
                if m.fixed_point:
                    cond = f"({access} && !FixedPoint::parse(*{access}))" if opt else f"!FixedPoint::parse({access})"
                    out.append(f'\tif ({cond}) {{\n\t\treturn invalid("{name}", "{m.json_name}", "is not a fixed-point decimal");\n\t}}\n')
                elif m.required and m.base_kind == "enum":
                    out.append(f'\tif ({access} == {m.element}::Unknown) {{\n\t\treturn invalid("{name}", "{m.json_name}", "is required");\n\t}}\n')
                elif m.required and m.base_kind == "string":
                    out.append(f'\tif ({access}.empty()) {{\n\t\treturn invalid("{name}", "{m.json_name}", "is required");\n\t}}\n')
                elif m.element in order and m.base_kind == "struct":
                    if opt:
                        out.append(f"\tif ({access}) {{\n\t\tif (Result<void> valid = validate(*{access}); !valid) {{\n"
                                   "\t\t\treturn valid;\n\t\t}\n\t}\n")
                    else:
                        out.append(f"\tif (Result<void> valid = validate({access}); !valid) {{\n\t\treturn valid;\n\t}}\n")
                elif m.element in order and m.base_kind == "vector":
                    rng = f"*{access}" if opt else access
                    guard_open = f"\tif ({access}) {{\n" if opt else ""
                    guard_close = "\t}\n" if opt else ""
                    out.append(f"{guard_open}\tfor (const {m.element}& item : {rng}) {{\n"
                               "\t\tif (Result<void> valid = validate(item); !valid) {\n\t\t\treturn valid;\n\t\t}\n\t}\n"
                               f"{guard_close}")
            out.append("\treturn {};\n}\n\n")
        out.append("} // namespace kalshi::detail\n")
        return "".join(out)

    def json_meta_header(self) -> str:
        out = [BANNER, "#pragma once\n\n// Glaze adapters for generated enums: unknown strings read as Unknown.\n\n",
               '#include "kalshi/models.hpp"\n\n#include <string>\n#include <string_view>\n\n#include "../json.hpp"\n\n',
               "namespace kalshi::detail {\n\n"]
        for enum in sorted(self.enums.values(), key=lambda e: e.name):
            out.append(emit_enum_parser(enum, enum.name))
        out.append("} // namespace kalshi::detail\n\nnamespace glz {\n\n")
        for enum in sorted(self.enums.values(), key=lambda e: e.name):
            out.append(emit_enum_adapter(enum, f"kalshi::{enum.name}", f"kalshi::detail::parse_{snake(enum.name)}"))
        out.append("} // namespace glz\n")
        return "".join(out)

    def routes_test(self) -> str:
        out = [BANNER, "// Every operation reaches its documented method and path, and a request body\n"
               "// that fails validation never reaches the transport.\n\n",
               '#include "kalshi/api.hpp"\n\n#include <gtest/gtest.h>\n#include <memory>\n#include <string>\n\n'
               '#include "support/recording_transport.hpp"\n\n',
               "using namespace kalshi; // generated tests name many model types\n\n"
               "namespace {\n\nstd::string route(const std::string& target) {\n"
               "\treturn target.substr(0, target.find('?'));\n}\n\n} // namespace\n\n"]
        for op in self.operations:
            args = [f'"p{i}"' for i, _ in enumerate(op.path_params)]
            if op.body_type:
                args.append(f"{op.body_type}{{}}")
            if op.params_struct:
                args.append(f"{op.params_struct.name}{{}}")
            path = op.path
            for i, name in enumerate(op.path_params):
                path = path.replace("{" + name + "}", f"p{i}")
            method = "DEL" if op.http_method == "DELETE" else op.http_method
            out.append(f"TEST(OperationRoutes, {op.operation_id}) {{\n"
                       "\tconst std::shared_ptr<kalshi::test::RecordingTransport> transport =\n"
                       "\t\tstd::make_shared<kalshi::test::RecordingTransport>();\n"
                       "\tkalshi::KalshiClient client(transport);\n"
                       f"\tconst {self.result_type(op)} result =\n"
                       f"\t\tclient.{op.method_name}({', '.join(args)});\n")
            if op.body_type and self.default_is_invalid(op.body_type):
                out.append("\tASSERT_FALSE(result.has_value());\n"
                           "\tEXPECT_EQ(result.error().code, kalshi::ErrorCode::InvalidRequest);\n"
                           "\tEXPECT_EQ(transport->calls, 0);\n}\n\n")
            else:
                out.append("\tEXPECT_TRUE(result.has_value());\n"
                           f"\tEXPECT_EQ(transport->method, kalshi::HttpMethod::{method});\n"
                           f'\tEXPECT_EQ(route(transport->target), "{path}");\n}}\n\n')
        return "".join(out)

    def operations_doc(self) -> str:
        version = self.spec.get("info", {}).get("version", "?")
        out = ["# REST operations\n\n",
               f"Generated from Kalshi Predictions OpenAPI {version} (`spec/openapi.yaml`).\n",
               "Each row is a `KalshiClient` method.\n"]
        for tag, ops in sorted(self.tags().items()):
            out.append(f"\n## {tag}\n\n| Method | Route | C++ |\n| --- | --- | --- |\n")
            for op in ops:
                note = " (deprecated)" if op.deprecated else ""
                out.append(f"| {op.http_method} | `{op.path}` | `{op.method_name}`{note} |\n")
        return "".join(out)

    def tags(self) -> dict[str, list[Operation]]:
        by_tag: dict[str, list[Operation]] = {}
        for op in self.operations:
            by_tag.setdefault(op.tag, []).append(op)
        return by_tag


def render_api(declarations: str) -> str:
    template = (ROOT / "tools" / "codegen" / "api.hpp.in").read_text()
    return BANNER + template.replace("@OPERATIONS@\n", declarations)


def outputs(gen: Generator, ws: WsGenerator) -> dict[Path, str]:
    files = {
        ROOT / "include" / "kalshi" / "models.hpp": gen.models_header(),
        ROOT / "include" / "kalshi" / "api.hpp": render_api(gen.api_declarations()),
        ROOT / "src" / "models" / "json_meta.hpp": gen.json_meta_header(),
        ROOT / "src" / "api" / "validate.hpp": gen.validate_header(),
        ROOT / "tests" / "test_operation_routes.cpp": gen.routes_test(),
        ROOT / "docs" / "operations.md": gen.operations_doc(),
        ROOT / "include" / "kalshi" / "ws_models.hpp": ws.models_header(),
        ROOT / "src" / "ws" / "wire.hpp": ws.wire_header(),
        ROOT / "tests" / "test_ws_messages.cpp": ws.messages_test(),
        ROOT / "docs" / "channels.md": ws.channels_doc(),
    }
    for tag, ops in gen.tags().items():
        if not re.fullmatch(r"[a-z0-9_-]+", tag):
            raise SystemExit(f"tag {tag!r} cannot name a source file")
        files[ROOT / "src" / "api" / "operations" / f"{tag.replace('-', '_')}.cpp"] = gen.operations_source(tag, ops)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    gen = Generator(yaml.safe_load(SPEC.read_text()))
    gen.run()
    ws = WsGenerator(yaml.safe_load(WS_SPEC.read_text()), gen.enums)
    ws.run()
    files = {path: clang_format(path, text) if path.suffix in (".hpp", ".cpp") else text
             for path, text in outputs(gen, ws).items()}

    stale = [path for path, text in files.items() if not path.exists() or path.read_text() != text]
    generated_dir = ROOT / "src" / "api" / "operations"
    orphans = [p for p in generated_dir.glob("*.cpp") if p not in files] if generated_dir.exists() else []
    if args.check:
        for path in stale + orphans:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale or orphans else 0
    for path in orphans:
        path.unlink()
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(files[path])
        print(f"wrote {path.relative_to(ROOT)}")
    print(f"REST: {len(gen.operations)} operations, {len(gen.structs)} structs, {len(gen.enums)} enums")
    print(f"WebSocket: {len(ws.channels)} channels, {len(ws.messages)} messages, {len(ws.structs)} structs, "
          f"{len(ws.enums)} enums")
    return 0


if __name__ == "__main__":
    sys.exit(main())
