"""Generates the WebSocket message types from spec/asyncapi.yaml.

Mapping rules:
- Each data message's `msg` payload becomes a struct in `kalshi::ws` named after
  the message (`ticker` -> `ws::Ticker`). Frames arrive as `ws::Update<T>`,
  which adds the envelope's `sid`, `seq`, and `id`.
- Enums reuse a REST enum with the same values when the match is unambiguous,
  so `ws::Fill::side` and `Fill::side` are both `kalshi::Side`.
- Messages that share a `type` are told apart by a `msg` property with a
  `const` value (`market_lifecycle_v2` frames with `event_type:
  metadata_updated` are `ws::MarketMetadataUpdated`).
- Subscribe and update_subscription parameters become `ws::SubscribeParams`
  and `ws::UpdateSubscriptionParams`; the client adds the channel and `sids`.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field

from common import (CPP_RESERVED, ROOT, UNKNOWN_VALUE, EnumType, Member, StructType, check_enums,
                    emit_enum, emit_enum_adapter, emit_enum_parser, emit_struct, first_sentence,
                    ordered_structs, pascal, ref_name, snake)

WS_SPEC = ROOT / "spec" / "asyncapi.yaml"
WS_BANNER = "// Generated by tools/codegen/generate.py from spec/asyncapi.yaml. Do not edit.\n"

CONTROL_CHANNELS = {"root", "control_frames"}

# Property names that need the owning message in their enum's name.
GENERIC_PROPERTIES = {"status", "type", "event_type", "action", "result"}

# Shared names for common value sets, matching the REST generator.
ENUM_NAMES_BY_VALUES = {
    frozenset({"yes", "no"}): "Side",
    frozenset({"buy", "sell"}): "Action",
}

# The update_subscription payload variants, merged into one parameter struct.
UPDATE_PAYLOADS = ("updateSubscriptionCommandPayload", "cfbenchmarksUpdateSubscriptionCommandPayload",
                   "pythUpdateSubscriptionCommandPayload")


@dataclass
class DataMessage:
    key: str  # components.messages key
    type: str  # the envelope's "type"
    struct: str  # C++ struct for `msg`
    summary: str
    channels: list[str] = field(default_factory=list)
    discriminator: tuple[str, str] | None = None  # (msg property, const value)
    examples: list[dict] = field(default_factory=list)


class WsGenerator:
    def __init__(self, spec: dict, rest_enums: dict[str, EnumType]) -> None:
        self.spec = spec
        self.schemas: dict = spec["components"]["schemas"]
        self.message_specs: dict = spec["components"]["messages"]
        self.rest_enums = rest_enums
        self.enums: dict[str, EnumType] = {}
        self.structs: dict[str, StructType] = {}
        self.messages: list[DataMessage] = []
        self.channels: list[str] = []
        self.channel_docs: dict[str, str] = {}
        self.error_codes: list[tuple[int, str]] = []
        self.subscribe_params: StructType | None = None
        self.update_params: StructType | None = None

    # ----- types -----------------------------------------------------------

    def run(self) -> None:
        subscribe = self.schemas["subscribeCommandPayload"]["properties"]["params"]
        self.channels = list(subscribe["properties"]["channels"]["items"]["enum"])
        self.enums["Channel"] = EnumType("Channel", self.channels, "A WebSocket channel.")

        for channel, spec in self.spec["channels"].items():
            if channel in CONTROL_CHANNELS:
                continue
            self.channel_docs[channel] = first_sentence(spec.get("description"))
            for ref in spec.get("messages", {}).values():
                self.data_message(ref_name(ref["$ref"]), channel)
        self.discriminate()

        self.subscribe_params = self.params_struct("SubscribeParams", [subscribe], skip={"channels"},
                                                   doc="Options for subscribe; the client sets the channel.")
        self.update_params = self.params_struct(
            "UpdateSubscriptionParams",
            [self.schemas[name]["properties"]["params"] for name in UPDATE_PAYLOADS],
            skip={"sid", "sids"}, doc="Options for update_subscription; the client sets the subscription.")
        self.error_codes = [(c["code"], c["name"]) for c in self.spec.get("x-error-codes", {}).get("codes", [])]
        check_enums(self.enums)

    def data_message(self, key: str, channel: str) -> None:
        existing = next((m for m in self.messages if m.key == key), None)
        if existing:
            existing.channels.append(channel)
            return
        spec = self.message_specs[key]
        payload = self.schemas[ref_name(spec["payload"]["$ref"])]
        type_value = payload["properties"]["type"]["const"]
        name = pascal(key)
        self.struct_for(name, payload["properties"]["msg"], doc=spec.get("summary") or spec.get("title"))
        self.messages.append(DataMessage(key, type_value, name, first_sentence(spec.get("summary")), [channel],
                                         examples=[e["payload"] for e in spec.get("examples", [])]))

    def discriminate(self) -> None:
        by_type: dict[str, list[DataMessage]] = {}
        for message in self.messages:
            by_type.setdefault(message.type, []).append(message)
        for type_value, group in by_type.items():
            if len(group) == 1:
                continue
            defaults = []
            for message in group:
                payload = self.schemas[ref_name(self.message_specs[message.key]["payload"]["$ref"])]
                props = payload["properties"]["msg"].get("properties", {})
                const = next(((k, v["const"]) for k, v in props.items() if "const" in v), None)
                message.discriminator = const
                if const is None:
                    defaults.append(message)
            if len(defaults) != 1:
                # Without exactly one default, a new discriminator value would have
                # nowhere to go and every such frame would fail to parse.
                raise SystemExit(f"messages of type {type_value} need exactly one without a const "
                                 f"discriminator; found {len(defaults)}")
            # The default message is tried last.
            group.sort(key=lambda m: m.discriminator is None)
            self.messages = [m for m in self.messages if m not in group] + group

    def resolve(self, schema: dict) -> tuple[str | None, dict]:
        if "$ref" not in schema:
            return None, schema
        name = ref_name(schema["$ref"])
        merged = dict(self.schemas[name])
        merged.update({k: v for k, v in schema.items() if k != "$ref"})
        return name, merged

    def type_of(self, schema: dict, context: str, prop: str) -> tuple[str, str, str, bool]:
        """Returns (cpp type, kind, element name, nullable)."""
        name, schema = self.resolve(schema)
        kind = schema.get("type")
        nullable = False
        if isinstance(kind, list):
            nullable = "null" in kind
            kind = next((k for k in kind if k != "null"), None)
        if "enum" in schema:
            values = [v for v in schema["enum"] if v is not None]
            nullable = nullable or None in schema["enum"]
            enum = self.enum_for(values, name, context, prop, schema.get("description", ""))
            return enum, "enum", enum.rsplit("::", 1)[-1], nullable
        if kind == "array":
            inner, inner_kind, element, _ = self.type_of(schema.get("items", {}), context + "Item", prop)
            size = schema.get("minItems")
            if size is not None and size > 1 and size == schema.get("maxItems"):
                return f"std::array<{inner}, {size}>", "container", "", nullable
            return f"std::vector<{inner}>", "vector", element if inner_kind in ("struct", "enum") else "", nullable
        if kind == "object" or "properties" in schema:
            if schema.get("properties"):
                struct = pascal(name) if name else context
                self.struct_for(struct, schema)
                return struct, "struct", struct, nullable
            return "RawJson", "raw", "", nullable
        if kind == "integer":
            return "std::int64_t", "scalar", "", nullable
        if kind == "number":
            return "double", "scalar", "", nullable
        if kind == "boolean":
            return "bool", "scalar", "", nullable
        return "std::string", "string", "", nullable

    def enum_for(self, values: list[str], schema_name: str | None, context: str, prop: str, doc: str) -> str:
        known = frozenset(v for v in values if v != UNKNOWN_VALUE)
        # `context` is the owner plus the property (TradeTakerSide), so a generic
        # property such as `status` still gets a specific name.
        if schema_name:
            preferred = pascal(schema_name)
        elif not prop or prop in GENERIC_PROPERTIES:
            preferred = context
        else:
            preferred = pascal(prop)
        rest = [e for e in self.rest_enums.values() if frozenset(e.known) == known]
        choice = None
        if len(rest) == 1:
            choice = rest[0].name
        elif rest:
            choice = next((e.name for e in rest if prop.endswith(snake(e.name))), None) \
                or next((e.name for e in rest if e.name == ENUM_NAMES_BY_VALUES.get(known)), None) \
                or next((e.name for e in rest if preferred.endswith(e.name)), None)
        if choice:
            return f"kalshi::{choice}"
        for enum in self.enums.values():
            if frozenset(enum.known) == known and set(enum.values) == set(values):
                return enum.name
        name = preferred
        while name in self.enums:
            name += "Value"
        self.enums[name] = EnumType(name, list(values), first_sentence(doc))
        return name

    def member(self, owner: str, json_name: str, schema: dict, required: bool) -> Member:
        cpp, kind, element, nullable = self.type_of(schema, owner + pascal(json_name), json_name)
        if json_name in CPP_RESERVED:
            raise SystemExit(f"{owner}.{json_name} needs a rename")
        plain = required and not nullable
        _, resolved = self.resolve(schema)
        return Member(json_name=json_name, cpp_type=cpp if plain else f"std::optional<{cpp}>",
                      doc=schema.get("description") or resolved.get("description", ""),
                      required=plain, base_kind=kind, element=element)

    def struct_for(self, name: str, schema: dict, doc: str | None = None) -> StructType:
        if name in self.structs:
            return self.structs[name]
        struct = StructType(name, doc=first_sentence(doc or schema.get("description")))
        self.structs[name] = struct
        required = set(schema.get("required", []))
        for json_name, prop in schema.get("properties", {}).items():
            if "const" in prop:
                continue  # discriminators carry no information once dispatched
            struct.members.append(self.member(name, json_name, prop, json_name in required))
        return struct

    def params_struct(self, name: str, schemas: list[dict], skip: set[str], doc: str) -> StructType:
        """Merges command parameter schemas into one struct of options."""
        props: dict[str, dict] = {}
        required: set[str] = set()
        for schema in schemas:
            required |= set(schema.get("required", []))
            for key, prop in schema.get("properties", {}).items():
                if key in skip:
                    continue
                if key in props and "enum" in prop:  # e.g. every update_subscription action
                    merged = props[key].get("enum", []) + [v for v in prop["enum"] if v not in props[key].get("enum", [])]
                    props[key] = dict(props[key], enum=merged)
                else:
                    props.setdefault(key, prop)
        struct = StructType(name, doc=doc)
        self.structs[name] = struct
        for key, prop in props.items():
            context = "UpdateAction" if name == "UpdateSubscriptionParams" and key == "action" else name + pascal(key)
            cpp, kind, element, _ = self.type_of(prop, context, "" if key == "action" else key)
            plain = key in required
            if kind == "vector":
                plain = True  # an empty list means "not set" and is left out
            struct.members.append(Member(json_name=key, cpp_type=cpp if plain else f"std::optional<{cpp}>",
                                         doc=prop.get("description", ""), required=plain, base_kind=kind,
                                         element=element))
        return struct

    # ----- emission --------------------------------------------------------

    def models_header(self) -> str:
        template = (ROOT / "tools" / "codegen" / "ws_models.hpp.in").read_text()
        enums = "".join(emit_enum(e) for e in sorted(self.enums.values(), key=lambda e: e.name))
        structs = "".join(emit_struct(s) for s in ordered_structs(self.structs))
        alternatives = ",\n\t".join([f"Update<{m.struct}>" for m in self.messages] +
                                    ["Subscribed", "Unsubscribed", "Updated", "SubscriptionList"])
        variant = f"/// Everything WebSocketClient delivers to on_message.\nusing Message = std::variant<{alternatives}>;\n"
        codes = "".join(f'\t\tcase {code}:\n\t\t\treturn "{name}";\n' for code, name in self.error_codes)
        errors = ("/// Kalshi's name for a WebSocket error code, or an empty string for codes this\n"
                  "/// SDK version does not know.\n"
                  "[[nodiscard]] constexpr std::string_view error_code_name(std::int64_t code) noexcept {\n"
                  f"\tswitch (code) {{\n{codes}\t\tdefault:\n\t\t\treturn \"\";\n\t}}\n}}\n")
        return WS_BANNER + (template.replace("@ENUMS@\n", enums).replace("@STRUCTS@\n", structs)
                            .replace("@MESSAGE@\n", variant).replace("@ERROR_CODES@\n", errors))

    def wire_header(self) -> str:
        out = [WS_BANNER, "#pragma once\n\n// Glaze adapters for WebSocket enums, command parameters, and frame dispatch.\n\n",
               '#include "kalshi/websocket.hpp"\n\n#include <cstdint>\n#include <optional>\n#include <string>\n'
               '#include <string_view>\n#include <vector>\n\n#include "../models/json_meta.hpp"\n#include "frame_support.hpp"\n\n',
               "namespace kalshi::detail {\n\n"]
        for enum in sorted(self.enums.values(), key=lambda e: e.name):
            out.append(emit_enum_parser(enum, f"ws::{enum.name}", prefix="ws_"))
        for struct, extra, extra_type in ((self.subscribe_params, "channels", "std::vector<ws::Channel>"),
                                          (self.update_params, "sids", "std::vector<std::int64_t>")):
            wire = struct.name.replace("Params", "Wire")
            out.append(f"/// `{struct.name}` plus the `{extra}` the client fills in, in wire order.\n"
                       f"struct {wire} {{\n\t{extra_type} {extra};\n")
            for m in struct.members:
                cpp = self.qualified(m.cpp_type)
                if m.base_kind == "vector":
                    cpp = f"std::optional<{cpp}>"  # Kalshi rejects empty lists
                init = "{}" if m.required and m.base_kind in ("scalar", "enum") else ""
                out.append(f"\t{cpp} {m.json_name}{init};\n")
            out.append("};\n\n")
            out.append(f"inline {wire} to_wire({extra_type} {extra}, const ws::{struct.name}& params) {{\n"
                       f"\t{wire} wire;\n\twire.{extra} = std::move({extra});\n")
            for m in struct.members:
                if m.base_kind == "vector":
                    out.append(f"\tif (!params.{m.json_name}.empty()) {{\n\t\twire.{m.json_name} = params.{m.json_name};\n\t}}\n")
                else:
                    out.append(f"\twire.{m.json_name} = params.{m.json_name};\n")
            out.append("\treturn wire;\n}\n\n")
        out.append("/// Parses a data frame whose envelope `type` is `type`.\n"
                   "inline std::optional<WsMessage> parse_data_frame(std::string_view type, const std::string& json) {\n")
        emitted: set[str] = set()
        for message in self.messages:
            if message.type in emitted:
                continue
            group = [m for m in self.messages if m.type == message.type]
            emitted.add(message.type)
            out.append(f'\tif (type == "{message.type}") {{\n')
            if len(group) == 1:
                out.append(f"\t\treturn read_update<ws::{message.struct}>(json);\n\t}}\n")
                continue
            for m in group:
                if m.discriminator:
                    prop, value = m.discriminator
                    if prop != "event_type":
                        raise SystemExit(f"add a reader for msg.{prop} to src/ws/frame_support.hpp")
                    out.append(f'\t\tif (msg_event_type(json) == "{value}") {{\n'
                               f"\t\t\treturn read_update<ws::{m.struct}>(json);\n\t\t}}\n")
                else:
                    out.append(f"\t\treturn read_update<ws::{m.struct}>(json);\n")
            out.append("\t}\n")
        out.append("\treturn std::nullopt;\n}\n\n")
        types = sorted({m.type for m in self.messages})
        checks = " ||\n\t\t   ".join(f'type == "{t}"' for t in types)
        out.append("/// Whether `type` names a data message this SDK version parses.\n"
                   f"inline bool is_data_type(std::string_view type) noexcept {{\n\treturn {checks};\n}}\n\n")
        out.append("} // namespace kalshi::detail\n\nnamespace glz {\n\n")
        for enum in sorted(self.enums.values(), key=lambda e: e.name):
            out.append(emit_enum_adapter(enum, f"kalshi::ws::{enum.name}", f"kalshi::detail::parse_ws_{snake(enum.name)}"))
        out.append("} // namespace glz\n")
        return "".join(out)

    def qualified(self, cpp: str) -> str:
        """Qualifies generated WebSocket types for use outside `kalshi::ws`."""
        for name in sorted(set(self.enums) | set(self.structs), key=len, reverse=True):
            cpp = re.sub(rf"(?<![:\w]){name}(?!\w)", f"ws::{name}", cpp)
        return cpp

    def messages_test(self) -> str:
        out = [WS_BANNER, "// Every example frame in Kalshi's AsyncAPI document parses into its message type.\n\n",
               '#include "kalshi/websocket.hpp"\n\n#include <gtest/gtest.h>\n#include <optional>\n#include <variant>\n\n'
               '#include "frames.hpp"\n\n']
        for message in self.messages:
            for index, example in enumerate(message.examples):
                text = json.dumps(example, separators=(",", ":"))
                check = self.example_check(message, example)
                out.append(f"TEST(WsMessages, {message.struct}Example{index}) {{\n"
                           f'\tconst std::optional<kalshi::WsMessage> message = kalshi::detail::parse_message(R"json({text})json");\n'
                           "\tASSERT_TRUE(message.has_value());\n"
                           f"\tconst kalshi::ws::Update<kalshi::ws::{message.struct}>* update =\n"
                           f"\t\tstd::get_if<kalshi::ws::Update<kalshi::ws::{message.struct}>>(&*message);\n"
                           "\tASSERT_NE(update, nullptr);\n"
                           f"\tEXPECT_EQ(update->sid, {example.get('sid', 0)});\n{check}}}\n\n")
        return "".join(out)

    def example_check(self, message: DataMessage, example: dict) -> str:
        """Checks one required string field so a misnamed member fails the test."""
        struct = self.structs[message.struct]
        msg = example.get("msg", {})
        for m in struct.members:
            if m.required and m.base_kind == "string" and isinstance(msg.get(m.json_name), str):
                value = json.dumps(msg[m.json_name])
                return f"\tEXPECT_EQ(update->msg.{m.json_name}, {value});\n"
        return ""

    def channels_doc(self) -> str:
        version = self.spec.get("info", {}).get("version", "?")
        out = ["# WebSocket channels\n\n",
               f"Generated from Kalshi's AsyncAPI {version} document (`spec/asyncapi.yaml`).\n",
               "Subscribe with `WebSocketClient::subscribe(ws::Channel::..., params)`; each message\n"
               "arrives in `on_message` as `ws::Update<T>`.\n\n",
               "| Channel | `ws::Channel` | Messages |\n| --- | --- | --- |\n"]
        from common import enumerator
        for channel in self.channels:
            types = ", ".join(f"`ws::{m.struct}`" for m in self.messages if channel in m.channels)
            out.append(f"| `{channel}` | `{enumerator(channel)}` | {types} |\n")
        return "".join(out)
