// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#pragma once

// Glaze adapters for generated enums: unknown strings read as Unknown.

#include "kalshi/models.hpp"

#include <string>
#include <string_view>

#include "../json.hpp"

namespace kalshi::detail {

inline Action parse_action(std::string_view text) noexcept {
	if (text == "buy") {
		return Action::Buy;
	}
	if (text == "sell") {
		return Action::Sell;
	}
	return Action::Unknown;
}

inline ApiKeyScope parse_api_key_scope(std::string_view text) noexcept {
	if (text == "read") {
		return ApiKeyScope::Read;
	}
	if (text == "write") {
		return ApiKeyScope::Write;
	}
	if (text == "read::block_trade_accept") {
		return ApiKeyScope::ReadBlockTradeAccept;
	}
	if (text == "read::portfolio_balance") {
		return ApiKeyScope::ReadPortfolioBalance;
	}
	if (text == "write::trade") {
		return ApiKeyScope::WriteTrade;
	}
	if (text == "write::transfer") {
		return ApiKeyScope::WriteTransfer;
	}
	if (text == "write::fcm_risk") {
		return ApiKeyScope::WriteFcmRisk;
	}
	if (text == "write::block_trade_accept") {
		return ApiKeyScope::WriteBlockTradeAccept;
	}
	return ApiKeyScope::Unknown;
}

inline ApiKeyType parse_api_key_type(std::string_view text) noexcept {
	if (text == "rsa") {
		return ApiKeyType::Rsa;
	}
	if (text == "ed25519") {
		return ApiKeyType::Ed25519;
	}
	return ApiKeyType::Unknown;
}

inline BookSide parse_book_side(std::string_view text) noexcept {
	if (text == "bid") {
		return BookSide::Bid;
	}
	if (text == "ask") {
		return BookSide::Ask;
	}
	return BookSide::Unknown;
}

inline DepositStatus parse_deposit_status(std::string_view text) noexcept {
	if (text == "pending") {
		return DepositStatus::Pending;
	}
	if (text == "applied") {
		return DepositStatus::Applied;
	}
	if (text == "failed") {
		return DepositStatus::Failed;
	}
	if (text == "returned") {
		return DepositStatus::Returned;
	}
	return DepositStatus::Unknown;
}

inline DepositType parse_deposit_type(std::string_view text) noexcept {
	if (text == "ach") {
		return DepositType::Ach;
	}
	if (text == "wire") {
		return DepositType::Wire;
	}
	if (text == "crypto") {
		return DepositType::Crypto;
	}
	if (text == "debit") {
		return DepositType::Debit;
	}
	if (text == "apm") {
		return DepositType::Apm;
	}
	return DepositType::Unknown;
}

inline ExchangeInstance parse_exchange_instance(std::string_view text) noexcept {
	if (text == "event_contract") {
		return ExchangeInstance::EventContract;
	}
	if (text == "margined") {
		return ExchangeInstance::Margined;
	}
	return ExchangeInstance::Unknown;
}

inline FeeType parse_fee_type(std::string_view text) noexcept {
	if (text == "quadratic") {
		return FeeType::Quadratic;
	}
	if (text == "quadratic_with_maker_fees") {
		return FeeType::QuadraticWithMakerFees;
	}
	if (text == "quadratic_with_combo_maker_fees") {
		return FeeType::QuadraticWithComboMakerFees;
	}
	if (text == "flat") {
		return FeeType::Flat;
	}
	return FeeType::Unknown;
}

inline GetEventsStatus parse_get_events_status(std::string_view text) noexcept {
	if (text == "unopened") {
		return GetEventsStatus::Unopened;
	}
	if (text == "open") {
		return GetEventsStatus::Open;
	}
	if (text == "closed") {
		return GetEventsStatus::Closed;
	}
	if (text == "settled") {
		return GetEventsStatus::Settled;
	}
	return GetEventsStatus::Unknown;
}

inline GetHistoricalMarketsMveFilter
parse_get_historical_markets_mve_filter(std::string_view text) noexcept {
	if (text == "exclude") {
		return GetHistoricalMarketsMveFilter::Exclude;
	}
	return GetHistoricalMarketsMveFilter::Unknown;
}

inline GetIncentiveProgramsStatus
parse_get_incentive_programs_status(std::string_view text) noexcept {
	if (text == "all") {
		return GetIncentiveProgramsStatus::All;
	}
	if (text == "active") {
		return GetIncentiveProgramsStatus::Active;
	}
	if (text == "upcoming") {
		return GetIncentiveProgramsStatus::Upcoming;
	}
	if (text == "closed") {
		return GetIncentiveProgramsStatus::Closed;
	}
	if (text == "paid_out") {
		return GetIncentiveProgramsStatus::PaidOut;
	}
	return GetIncentiveProgramsStatus::Unknown;
}

inline GetIncentiveProgramsType parse_get_incentive_programs_type(std::string_view text) noexcept {
	if (text == "all") {
		return GetIncentiveProgramsType::All;
	}
	if (text == "liquidity") {
		return GetIncentiveProgramsType::Liquidity;
	}
	if (text == "volume") {
		return GetIncentiveProgramsType::Volume;
	}
	if (text == "margin_maker_volume") {
		return GetIncentiveProgramsType::MarginMakerVolume;
	}
	if (text == "margin_taker_volume") {
		return GetIncentiveProgramsType::MarginTakerVolume;
	}
	return GetIncentiveProgramsType::Unknown;
}

inline GetMarketsMveFilter parse_get_markets_mve_filter(std::string_view text) noexcept {
	if (text == "only") {
		return GetMarketsMveFilter::Only;
	}
	if (text == "exclude") {
		return GetMarketsMveFilter::Exclude;
	}
	return GetMarketsMveFilter::Unknown;
}

inline GetMarketsStatus parse_get_markets_status(std::string_view text) noexcept {
	if (text == "unopened") {
		return GetMarketsStatus::Unopened;
	}
	if (text == "open") {
		return GetMarketsStatus::Open;
	}
	if (text == "paused") {
		return GetMarketsStatus::Paused;
	}
	if (text == "closed") {
		return GetMarketsStatus::Closed;
	}
	if (text == "settled") {
		return GetMarketsStatus::Settled;
	}
	return GetMarketsStatus::Unknown;
}

inline GetMultivariateEventCollectionsStatus
parse_get_multivariate_event_collections_status(std::string_view text) noexcept {
	if (text == "unopened") {
		return GetMultivariateEventCollectionsStatus::Unopened;
	}
	if (text == "open") {
		return GetMultivariateEventCollectionsStatus::Open;
	}
	if (text == "closed") {
		return GetMultivariateEventCollectionsStatus::Closed;
	}
	return GetMultivariateEventCollectionsStatus::Unknown;
}

inline IncentiveProgramIncentiveType
parse_incentive_program_incentive_type(std::string_view text) noexcept {
	if (text == "liquidity") {
		return IncentiveProgramIncentiveType::Liquidity;
	}
	if (text == "volume") {
		return IncentiveProgramIncentiveType::Volume;
	}
	if (text == "margin_maker_volume") {
		return IncentiveProgramIncentiveType::MarginMakerVolume;
	}
	if (text == "margin_taker_volume") {
		return IncentiveProgramIncentiveType::MarginTakerVolume;
	}
	return IncentiveProgramIncentiveType::Unknown;
}

inline IntraExchangeInstanceTransferStatus
parse_intra_exchange_instance_transfer_status(std::string_view text) noexcept {
	if (text == "pending") {
		return IntraExchangeInstanceTransferStatus::Pending;
	}
	if (text == "complete") {
		return IntraExchangeInstanceTransferStatus::Complete;
	}
	return IntraExchangeInstanceTransferStatus::Unknown;
}

inline MarketResult parse_market_result(std::string_view text) noexcept {
	if (text == "yes") {
		return MarketResult::Yes;
	}
	if (text == "no") {
		return MarketResult::No;
	}
	if (text == "scalar") {
		return MarketResult::Scalar;
	}
	if (text.empty()) {
		return MarketResult::Unset;
	}
	return MarketResult::Unknown;
}

inline MarketStatus parse_market_status(std::string_view text) noexcept {
	if (text == "initialized") {
		return MarketStatus::Initialized;
	}
	if (text == "inactive") {
		return MarketStatus::Inactive;
	}
	if (text == "active") {
		return MarketStatus::Active;
	}
	if (text == "closed") {
		return MarketStatus::Closed;
	}
	if (text == "determined") {
		return MarketStatus::Determined;
	}
	if (text == "disputed") {
		return MarketStatus::Disputed;
	}
	if (text == "amended") {
		return MarketStatus::Amended;
	}
	if (text == "finalized") {
		return MarketStatus::Finalized;
	}
	return MarketStatus::Unknown;
}

inline MarketType parse_market_type(std::string_view text) noexcept {
	if (text == "binary") {
		return MarketType::Binary;
	}
	if (text == "scalar") {
		return MarketType::Scalar;
	}
	return MarketType::Unknown;
}

inline OrderStatus parse_order_status(std::string_view text) noexcept {
	if (text == "resting") {
		return OrderStatus::Resting;
	}
	if (text == "canceled") {
		return OrderStatus::Canceled;
	}
	if (text == "executed") {
		return OrderStatus::Executed;
	}
	return OrderStatus::Unknown;
}

inline OrderType parse_order_type(std::string_view text) noexcept {
	if (text == "limit") {
		return OrderType::Limit;
	}
	if (text == "market") {
		return OrderType::Market;
	}
	return OrderType::Unknown;
}

inline OutcomeSide parse_outcome_side(std::string_view text) noexcept {
	if (text == "yes") {
		return OutcomeSide::Yes;
	}
	if (text == "no") {
		return OutcomeSide::No;
	}
	return OutcomeSide::Unknown;
}

inline QuoteStatus parse_quote_status(std::string_view text) noexcept {
	if (text == "open") {
		return QuoteStatus::Open;
	}
	if (text == "accepted") {
		return QuoteStatus::Accepted;
	}
	if (text == "confirmed") {
		return QuoteStatus::Confirmed;
	}
	if (text == "executed") {
		return QuoteStatus::Executed;
	}
	if (text == "cancelled") {
		return QuoteStatus::Cancelled;
	}
	return QuoteStatus::Unknown;
}

inline RFQStatus parse_rfq_status(std::string_view text) noexcept {
	if (text == "open") {
		return RFQStatus::Open;
	}
	if (text == "closed") {
		return RFQStatus::Closed;
	}
	return RFQStatus::Unknown;
}

inline RestingMarginReservation parse_resting_margin_reservation(std::string_view text) noexcept {
	if (text == "none") {
		return RestingMarginReservation::None;
	}
	if (text == "max") {
		return RestingMarginReservation::Max;
	}
	if (text == "sum") {
		return RestingMarginReservation::Sum;
	}
	return RestingMarginReservation::Unknown;
}

inline SelfTradePreventionType parse_self_trade_prevention_type(std::string_view text) noexcept {
	if (text == "taker_at_cross") {
		return SelfTradePreventionType::TakerAtCross;
	}
	if (text == "maker") {
		return SelfTradePreventionType::Maker;
	}
	return SelfTradePreventionType::Unknown;
}

inline SettlementMarketResult parse_settlement_market_result(std::string_view text) noexcept {
	if (text == "yes") {
		return SettlementMarketResult::Yes;
	}
	if (text == "no") {
		return SettlementMarketResult::No;
	}
	if (text == "scalar") {
		return SettlementMarketResult::Scalar;
	}
	return SettlementMarketResult::Unknown;
}

inline SettlementStatus parse_settlement_status(std::string_view text) noexcept {
	if (text == "all") {
		return SettlementStatus::All;
	}
	if (text == "unsettled") {
		return SettlementStatus::Unsettled;
	}
	if (text == "settled") {
		return SettlementStatus::Settled;
	}
	return SettlementStatus::Unknown;
}

inline Side parse_side(std::string_view text) noexcept {
	if (text == "yes") {
		return Side::Yes;
	}
	if (text == "no") {
		return Side::No;
	}
	return Side::Unknown;
}

inline StrikeType parse_strike_type(std::string_view text) noexcept {
	if (text == "greater") {
		return StrikeType::Greater;
	}
	if (text == "greater_or_equal") {
		return StrikeType::GreaterOrEqual;
	}
	if (text == "less") {
		return StrikeType::Less;
	}
	if (text == "less_or_equal") {
		return StrikeType::LessOrEqual;
	}
	if (text == "between") {
		return StrikeType::Between;
	}
	if (text == "functional") {
		return StrikeType::Functional;
	}
	if (text == "custom") {
		return StrikeType::Custom;
	}
	if (text == "structured") {
		return StrikeType::Structured;
	}
	return StrikeType::Unknown;
}

inline TimeInForce parse_time_in_force(std::string_view text) noexcept {
	if (text == "fill_or_kill") {
		return TimeInForce::FillOrKill;
	}
	if (text == "good_till_canceled") {
		return TimeInForce::GoodTillCanceled;
	}
	if (text == "immediate_or_cancel") {
		return TimeInForce::ImmediateOrCancel;
	}
	return TimeInForce::Unknown;
}

inline UserFilter parse_user_filter(std::string_view text) noexcept {
	if (text == "self") {
		return UserFilter::Self;
	}
	return UserFilter::Unknown;
}

} // namespace kalshi::detail

namespace glz {

template <>
struct from<JSON, kalshi::Action> {
	template <auto Opts>
	static void op(kalshi::Action& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_action(text);
	}
};

template <>
struct to<JSON, kalshi::Action> {
	template <auto Opts>
	static void op(const kalshi::Action& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ApiKeyScope> {
	template <auto Opts>
	static void op(kalshi::ApiKeyScope& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_api_key_scope(text);
	}
};

template <>
struct to<JSON, kalshi::ApiKeyScope> {
	template <auto Opts>
	static void op(const kalshi::ApiKeyScope& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ApiKeyType> {
	template <auto Opts>
	static void op(kalshi::ApiKeyType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_api_key_type(text);
	}
};

template <>
struct to<JSON, kalshi::ApiKeyType> {
	template <auto Opts>
	static void op(const kalshi::ApiKeyType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::BookSide> {
	template <auto Opts>
	static void op(kalshi::BookSide& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_book_side(text);
	}
};

template <>
struct to<JSON, kalshi::BookSide> {
	template <auto Opts>
	static void op(const kalshi::BookSide& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::DepositStatus> {
	template <auto Opts>
	static void op(kalshi::DepositStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_deposit_status(text);
	}
};

template <>
struct to<JSON, kalshi::DepositStatus> {
	template <auto Opts>
	static void op(const kalshi::DepositStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::DepositType> {
	template <auto Opts>
	static void op(kalshi::DepositType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_deposit_type(text);
	}
};

template <>
struct to<JSON, kalshi::DepositType> {
	template <auto Opts>
	static void op(const kalshi::DepositType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ExchangeInstance> {
	template <auto Opts>
	static void op(kalshi::ExchangeInstance& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_exchange_instance(text);
	}
};

template <>
struct to<JSON, kalshi::ExchangeInstance> {
	template <auto Opts>
	static void op(const kalshi::ExchangeInstance& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::FeeType> {
	template <auto Opts>
	static void op(kalshi::FeeType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_fee_type(text);
	}
};

template <>
struct to<JSON, kalshi::FeeType> {
	template <auto Opts>
	static void op(const kalshi::FeeType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::GetEventsStatus> {
	template <auto Opts>
	static void op(kalshi::GetEventsStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_get_events_status(text);
	}
};

template <>
struct to<JSON, kalshi::GetEventsStatus> {
	template <auto Opts>
	static void op(const kalshi::GetEventsStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::GetHistoricalMarketsMveFilter> {
	template <auto Opts>
	static void op(kalshi::GetHistoricalMarketsMveFilter& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_get_historical_markets_mve_filter(text);
	}
};

template <>
struct to<JSON, kalshi::GetHistoricalMarketsMveFilter> {
	template <auto Opts>
	static void op(const kalshi::GetHistoricalMarketsMveFilter& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::GetIncentiveProgramsStatus> {
	template <auto Opts>
	static void op(kalshi::GetIncentiveProgramsStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_get_incentive_programs_status(text);
	}
};

template <>
struct to<JSON, kalshi::GetIncentiveProgramsStatus> {
	template <auto Opts>
	static void op(const kalshi::GetIncentiveProgramsStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::GetIncentiveProgramsType> {
	template <auto Opts>
	static void op(kalshi::GetIncentiveProgramsType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_get_incentive_programs_type(text);
	}
};

template <>
struct to<JSON, kalshi::GetIncentiveProgramsType> {
	template <auto Opts>
	static void op(const kalshi::GetIncentiveProgramsType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::GetMarketsMveFilter> {
	template <auto Opts>
	static void op(kalshi::GetMarketsMveFilter& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_get_markets_mve_filter(text);
	}
};

template <>
struct to<JSON, kalshi::GetMarketsMveFilter> {
	template <auto Opts>
	static void op(const kalshi::GetMarketsMveFilter& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::GetMarketsStatus> {
	template <auto Opts>
	static void op(kalshi::GetMarketsStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_get_markets_status(text);
	}
};

template <>
struct to<JSON, kalshi::GetMarketsStatus> {
	template <auto Opts>
	static void op(const kalshi::GetMarketsStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::GetMultivariateEventCollectionsStatus> {
	template <auto Opts>
	static void op(kalshi::GetMultivariateEventCollectionsStatus& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_get_multivariate_event_collections_status(text);
	}
};

template <>
struct to<JSON, kalshi::GetMultivariateEventCollectionsStatus> {
	template <auto Opts>
	static void op(const kalshi::GetMultivariateEventCollectionsStatus& value, auto&& ctx,
				   auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::IncentiveProgramIncentiveType> {
	template <auto Opts>
	static void op(kalshi::IncentiveProgramIncentiveType& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_incentive_program_incentive_type(text);
	}
};

template <>
struct to<JSON, kalshi::IncentiveProgramIncentiveType> {
	template <auto Opts>
	static void op(const kalshi::IncentiveProgramIncentiveType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::IntraExchangeInstanceTransferStatus> {
	template <auto Opts>
	static void op(kalshi::IntraExchangeInstanceTransferStatus& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_intra_exchange_instance_transfer_status(text);
	}
};

template <>
struct to<JSON, kalshi::IntraExchangeInstanceTransferStatus> {
	template <auto Opts>
	static void op(const kalshi::IntraExchangeInstanceTransferStatus& value, auto&& ctx,
				   auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::MarketResult> {
	template <auto Opts>
	static void op(kalshi::MarketResult& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_market_result(text);
	}
};

template <>
struct to<JSON, kalshi::MarketResult> {
	template <auto Opts>
	static void op(const kalshi::MarketResult& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::MarketStatus> {
	template <auto Opts>
	static void op(kalshi::MarketStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_market_status(text);
	}
};

template <>
struct to<JSON, kalshi::MarketStatus> {
	template <auto Opts>
	static void op(const kalshi::MarketStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::MarketType> {
	template <auto Opts>
	static void op(kalshi::MarketType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_market_type(text);
	}
};

template <>
struct to<JSON, kalshi::MarketType> {
	template <auto Opts>
	static void op(const kalshi::MarketType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::OrderStatus> {
	template <auto Opts>
	static void op(kalshi::OrderStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_order_status(text);
	}
};

template <>
struct to<JSON, kalshi::OrderStatus> {
	template <auto Opts>
	static void op(const kalshi::OrderStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::OrderType> {
	template <auto Opts>
	static void op(kalshi::OrderType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_order_type(text);
	}
};

template <>
struct to<JSON, kalshi::OrderType> {
	template <auto Opts>
	static void op(const kalshi::OrderType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::OutcomeSide> {
	template <auto Opts>
	static void op(kalshi::OutcomeSide& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_outcome_side(text);
	}
};

template <>
struct to<JSON, kalshi::OutcomeSide> {
	template <auto Opts>
	static void op(const kalshi::OutcomeSide& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::QuoteStatus> {
	template <auto Opts>
	static void op(kalshi::QuoteStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_quote_status(text);
	}
};

template <>
struct to<JSON, kalshi::QuoteStatus> {
	template <auto Opts>
	static void op(const kalshi::QuoteStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::RFQStatus> {
	template <auto Opts>
	static void op(kalshi::RFQStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_rfq_status(text);
	}
};

template <>
struct to<JSON, kalshi::RFQStatus> {
	template <auto Opts>
	static void op(const kalshi::RFQStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::RestingMarginReservation> {
	template <auto Opts>
	static void op(kalshi::RestingMarginReservation& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_resting_margin_reservation(text);
	}
};

template <>
struct to<JSON, kalshi::RestingMarginReservation> {
	template <auto Opts>
	static void op(const kalshi::RestingMarginReservation& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::SelfTradePreventionType> {
	template <auto Opts>
	static void op(kalshi::SelfTradePreventionType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_self_trade_prevention_type(text);
	}
};

template <>
struct to<JSON, kalshi::SelfTradePreventionType> {
	template <auto Opts>
	static void op(const kalshi::SelfTradePreventionType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::SettlementMarketResult> {
	template <auto Opts>
	static void op(kalshi::SettlementMarketResult& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_settlement_market_result(text);
	}
};

template <>
struct to<JSON, kalshi::SettlementMarketResult> {
	template <auto Opts>
	static void op(const kalshi::SettlementMarketResult& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::SettlementStatus> {
	template <auto Opts>
	static void op(kalshi::SettlementStatus& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_settlement_status(text);
	}
};

template <>
struct to<JSON, kalshi::SettlementStatus> {
	template <auto Opts>
	static void op(const kalshi::SettlementStatus& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::Side> {
	template <auto Opts>
	static void op(kalshi::Side& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_side(text);
	}
};

template <>
struct to<JSON, kalshi::Side> {
	template <auto Opts>
	static void op(const kalshi::Side& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::StrikeType> {
	template <auto Opts>
	static void op(kalshi::StrikeType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_strike_type(text);
	}
};

template <>
struct to<JSON, kalshi::StrikeType> {
	template <auto Opts>
	static void op(const kalshi::StrikeType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::TimeInForce> {
	template <auto Opts>
	static void op(kalshi::TimeInForce& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_time_in_force(text);
	}
};

template <>
struct to<JSON, kalshi::TimeInForce> {
	template <auto Opts>
	static void op(const kalshi::TimeInForce& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::UserFilter> {
	template <auto Opts>
	static void op(kalshi::UserFilter& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_user_filter(text);
	}
};

template <>
struct to<JSON, kalshi::UserFilter> {
	template <auto Opts>
	static void op(const kalshi::UserFilter& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

} // namespace glz
