// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#pragma once

#include "kalshi/api.hpp"
#include "kalshi/fixed_point.hpp"

#include <string>
#include <string_view>

namespace kalshi::detail {

inline Result<void> invalid(std::string_view type, std::string_view field, std::string_view why) {
	return std::unexpected(
		Error{ErrorCode::InvalidRequest,
			  std::string(type) + "." + std::string(field) + " " + std::string(why)});
}

inline Result<void> validate(const AcceptQuoteRequest& value);
inline Result<void> validate(const AmendOrderV2Request& value);
inline Result<void> validate(const ApplySubaccountTransferRequest& value);
inline Result<void> validate(const BatchCancelOrdersV2RequestOrdersItem& value);
inline Result<void> validate(const BatchCancelOrdersV2Request& value);
inline Result<void> validate(const CreateOrderV2Request& value);
inline Result<void> validate(const BatchCreateOrdersV2Request& value);
inline Result<void> validate(const CreateApiKeyRequest& value);
inline Result<void> validate(const CreateFCMSubtraderRequest& value);
inline Result<void> validate(const TickerPair& value);
inline Result<void> validate(const CreateMarketInMultivariateEventCollectionRequest& value);
inline Result<void> validate(const CreateOrderGroupRequest& value);
inline Result<void> validate(const CreateQuoteRequest& value);
inline Result<void> validate(const CreateRFQRequest& value);
inline Result<void> validate(const DecreaseOrderV2Request& value);
inline Result<void> validate(const GenerateApiKeyRequest& value);
inline Result<void> validate(const IntraExchangeInstanceTransferRequest& value);
inline Result<void> validate(const ProposeBlockTradeRequest& value);
inline Result<void> validate(const UpdateFCMEventContractDailyCapRequest& value);
inline Result<void> validate(const UpdateFCMSubtraderBlockedCategoriesRequest& value);
inline Result<void> validate(const UpdateOrderGroupLimitRequest& value);

inline Result<void> validate(const AcceptQuoteRequest& value) {
	if (value.accepted_side == Side::Unknown) {
		return invalid("AcceptQuoteRequest", "accepted_side", "is required");
	}
	return {};
}

inline Result<void> validate(const AmendOrderV2Request& value) {
	if (value.ticker.empty()) {
		return invalid("AmendOrderV2Request", "ticker", "is required");
	}
	if (value.side == BookSide::Unknown) {
		return invalid("AmendOrderV2Request", "side", "is required");
	}
	if (!FixedPoint::parse(value.price)) {
		return invalid("AmendOrderV2Request", "price", "is not a fixed-point decimal");
	}
	if (!FixedPoint::parse(value.count)) {
		return invalid("AmendOrderV2Request", "count", "is not a fixed-point decimal");
	}
	return {};
}

inline Result<void> validate(const ApplySubaccountTransferRequest& value) {
	if (value.client_transfer_id.empty()) {
		return invalid("ApplySubaccountTransferRequest", "client_transfer_id", "is required");
	}
	return {};
}

inline Result<void> validate(const BatchCancelOrdersV2RequestOrdersItem& value) {
	if (value.order_id.empty()) {
		return invalid("BatchCancelOrdersV2RequestOrdersItem", "order_id", "is required");
	}
	return {};
}

inline Result<void> validate(const BatchCancelOrdersV2Request& value) {
	for (const BatchCancelOrdersV2RequestOrdersItem& item : value.orders) {
		if (Result<void> valid = validate(item); !valid) {
			return valid;
		}
	}
	return {};
}

inline Result<void> validate(const CreateOrderV2Request& value) {
	if (value.ticker.empty()) {
		return invalid("CreateOrderV2Request", "ticker", "is required");
	}
	if (value.side == BookSide::Unknown) {
		return invalid("CreateOrderV2Request", "side", "is required");
	}
	if (!FixedPoint::parse(value.count)) {
		return invalid("CreateOrderV2Request", "count", "is not a fixed-point decimal");
	}
	if (!FixedPoint::parse(value.price)) {
		return invalid("CreateOrderV2Request", "price", "is not a fixed-point decimal");
	}
	if (value.time_in_force == TimeInForce::Unknown) {
		return invalid("CreateOrderV2Request", "time_in_force", "is required");
	}
	if (value.self_trade_prevention_type == SelfTradePreventionType::Unknown) {
		return invalid("CreateOrderV2Request", "self_trade_prevention_type", "is required");
	}
	return {};
}

inline Result<void> validate(const BatchCreateOrdersV2Request& value) {
	for (const CreateOrderV2Request& item : value.orders) {
		if (Result<void> valid = validate(item); !valid) {
			return valid;
		}
	}
	return {};
}

inline Result<void> validate(const CreateApiKeyRequest& value) {
	if (value.name.empty()) {
		return invalid("CreateApiKeyRequest", "name", "is required");
	}
	if (value.public_key.empty()) {
		return invalid("CreateApiKeyRequest", "public_key", "is required");
	}
	return {};
}

inline Result<void> validate(const CreateFCMSubtraderRequest& value) {
	if (value.subtrader_suffix.empty()) {
		return invalid("CreateFCMSubtraderRequest", "subtrader_suffix", "is required");
	}
	return {};
}

inline Result<void> validate(const TickerPair& value) {
	if (value.market_ticker.empty()) {
		return invalid("TickerPair", "market_ticker", "is required");
	}
	if (value.event_ticker.empty()) {
		return invalid("TickerPair", "event_ticker", "is required");
	}
	if (value.side == Side::Unknown) {
		return invalid("TickerPair", "side", "is required");
	}
	return {};
}

inline Result<void> validate(const CreateMarketInMultivariateEventCollectionRequest& value) {
	for (const TickerPair& item : value.selected_markets) {
		if (Result<void> valid = validate(item); !valid) {
			return valid;
		}
	}
	return {};
}

inline Result<void> validate(const CreateOrderGroupRequest& value) {
	if ((value.contracts_limit_fp && !FixedPoint::parse(*value.contracts_limit_fp))) {
		return invalid("CreateOrderGroupRequest", "contracts_limit_fp",
					   "is not a fixed-point decimal");
	}
	return {};
}

inline Result<void> validate(const CreateQuoteRequest& value) {
	if (value.rfq_id.empty()) {
		return invalid("CreateQuoteRequest", "rfq_id", "is required");
	}
	if (!FixedPoint::parse(value.yes_bid)) {
		return invalid("CreateQuoteRequest", "yes_bid", "is not a fixed-point decimal");
	}
	if (!FixedPoint::parse(value.no_bid)) {
		return invalid("CreateQuoteRequest", "no_bid", "is not a fixed-point decimal");
	}
	return {};
}

inline Result<void> validate(const CreateRFQRequest& value) {
	if (value.market_ticker.empty()) {
		return invalid("CreateRFQRequest", "market_ticker", "is required");
	}
	if ((value.contracts_fp && !FixedPoint::parse(*value.contracts_fp))) {
		return invalid("CreateRFQRequest", "contracts_fp", "is not a fixed-point decimal");
	}
	if ((value.target_cost_dollars && !FixedPoint::parse(*value.target_cost_dollars))) {
		return invalid("CreateRFQRequest", "target_cost_dollars", "is not a fixed-point decimal");
	}
	return {};
}

inline Result<void> validate(const DecreaseOrderV2Request& value) {
	if ((value.reduce_by && !FixedPoint::parse(*value.reduce_by))) {
		return invalid("DecreaseOrderV2Request", "reduce_by", "is not a fixed-point decimal");
	}
	if ((value.reduce_to && !FixedPoint::parse(*value.reduce_to))) {
		return invalid("DecreaseOrderV2Request", "reduce_to", "is not a fixed-point decimal");
	}
	return {};
}

inline Result<void> validate(const GenerateApiKeyRequest& value) {
	if (value.name.empty()) {
		return invalid("GenerateApiKeyRequest", "name", "is required");
	}
	return {};
}

inline Result<void> validate(const IntraExchangeInstanceTransferRequest& value) {
	if (value.source == ExchangeInstance::Unknown) {
		return invalid("IntraExchangeInstanceTransferRequest", "source", "is required");
	}
	if (value.destination == ExchangeInstance::Unknown) {
		return invalid("IntraExchangeInstanceTransferRequest", "destination", "is required");
	}
	return {};
}

inline Result<void> validate(const ProposeBlockTradeRequest& value) {
	if (value.buyer_user_id.empty()) {
		return invalid("ProposeBlockTradeRequest", "buyer_user_id", "is required");
	}
	if (value.seller_user_id.empty()) {
		return invalid("ProposeBlockTradeRequest", "seller_user_id", "is required");
	}
	if (value.market_ticker.empty()) {
		return invalid("ProposeBlockTradeRequest", "market_ticker", "is required");
	}
	if (value.maker_side == Side::Unknown) {
		return invalid("ProposeBlockTradeRequest", "maker_side", "is required");
	}
	if (value.expiration_ts.empty()) {
		return invalid("ProposeBlockTradeRequest", "expiration_ts", "is required");
	}
	return {};
}

inline Result<void> validate(const UpdateFCMEventContractDailyCapRequest& value) {
	if (value.subtrader_id.empty()) {
		return invalid("UpdateFCMEventContractDailyCapRequest", "subtrader_id", "is required");
	}
	if (!FixedPoint::parse(value.limit)) {
		return invalid("UpdateFCMEventContractDailyCapRequest", "limit",
					   "is not a fixed-point decimal");
	}
	return {};
}

inline Result<void> validate(const UpdateFCMSubtraderBlockedCategoriesRequest& value) {
	if (value.subtrader_id.empty()) {
		return invalid("UpdateFCMSubtraderBlockedCategoriesRequest", "subtrader_id", "is required");
	}
	if (value.category.empty()) {
		return invalid("UpdateFCMSubtraderBlockedCategoriesRequest", "category", "is required");
	}
	return {};
}

inline Result<void> validate(const UpdateOrderGroupLimitRequest& value) {
	if ((value.contracts_limit_fp && !FixedPoint::parse(*value.contracts_limit_fp))) {
		return invalid("UpdateOrderGroupLimitRequest", "contracts_limit_fp",
					   "is not a fixed-point decimal");
	}
	return {};
}

} // namespace kalshi::detail
