// Generated by tools/codegen/generate.py from spec/asyncapi.yaml. Do not edit.
#pragma once

// Glaze adapters for WebSocket enums, command parameters, and frame dispatch.

#include "kalshi/websocket.hpp"

#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "../models/json_meta.hpp"
#include "frame_support.hpp"

namespace kalshi::detail {

inline ws::Channel parse_ws_channel(std::string_view text) noexcept {
	if (text == "orderbook_delta") {
		return ws::Channel::OrderbookDelta;
	}
	if (text == "ticker") {
		return ws::Channel::Ticker;
	}
	if (text == "trade") {
		return ws::Channel::Trade;
	}
	if (text == "fill") {
		return ws::Channel::Fill;
	}
	if (text == "market_positions") {
		return ws::Channel::MarketPositions;
	}
	if (text == "market_lifecycle_v2") {
		return ws::Channel::MarketLifecycleV2;
	}
	if (text == "multivariate_market_lifecycle") {
		return ws::Channel::MultivariateMarketLifecycle;
	}
	if (text == "communications") {
		return ws::Channel::Communications;
	}
	if (text == "order_group_updates") {
		return ws::Channel::OrderGroupUpdates;
	}
	if (text == "user_orders") {
		return ws::Channel::UserOrders;
	}
	if (text == "cfbenchmarks_value") {
		return ws::Channel::CfbenchmarksValue;
	}
	if (text == "cfbenchmarks_value_5hz") {
		return ws::Channel::CfbenchmarksValue5hz;
	}
	if (text == "pyth_value") {
		return ws::Channel::PythValue;
	}
	return ws::Channel::Unknown;
}

inline ws::CollateralReturnType parse_ws_collateral_return_type(std::string_view text) noexcept {
	if (text == "MECNET") {
		return ws::CollateralReturnType::MECNET;
	}
	if (text == "DIRECNET") {
		return ws::CollateralReturnType::DIRECNET;
	}
	if (text.empty()) {
		return ws::CollateralReturnType::Unset;
	}
	return ws::CollateralReturnType::Unknown;
}

inline ws::FeeTypeOverride parse_ws_fee_type_override(std::string_view text) noexcept {
	if (text == "quadratic") {
		return ws::FeeTypeOverride::Quadratic;
	}
	if (text == "quadratic_with_maker_fees") {
		return ws::FeeTypeOverride::QuadraticWithMakerFees;
	}
	if (text == "quadratic_with_combo_maker_fees") {
		return ws::FeeTypeOverride::QuadraticWithComboMakerFees;
	}
	if (text == "flat") {
		return ws::FeeTypeOverride::Flat;
	}
	if (text == "margin_market_maker_program_fees") {
		return ws::FeeTypeOverride::MarginMarketMakerProgramFees;
	}
	return ws::FeeTypeOverride::Unknown;
}

inline ws::LifecyclePriceLevelStructure
parse_ws_lifecycle_price_level_structure(std::string_view text) noexcept {
	if (text == "banded_centi_cent") {
		return ws::LifecyclePriceLevelStructure::BandedCentiCent;
	}
	if (text.empty()) {
		return ws::LifecyclePriceLevelStructure::Unset;
	}
	if (text == "linear_cent") {
		return ws::LifecyclePriceLevelStructure::LinearCent;
	}
	if (text == "deci_cent") {
		return ws::LifecyclePriceLevelStructure::DeciCent;
	}
	if (text == "tapered_deci_cent") {
		return ws::LifecyclePriceLevelStructure::TaperedDeciCent;
	}
	if (text == "center_whole_edge_half_cent") {
		return ws::LifecyclePriceLevelStructure::CenterWholeEdgeHalfCent;
	}
	if (text == "center_whole_edge_quint_cent") {
		return ws::LifecyclePriceLevelStructure::CenterWholeEdgeQuintCent;
	}
	if (text == "center_half_edge_half_cent") {
		return ws::LifecyclePriceLevelStructure::CenterHalfEdgeHalfCent;
	}
	if (text == "center_half_edge_quint_cent") {
		return ws::LifecyclePriceLevelStructure::CenterHalfEdgeQuintCent;
	}
	if (text == "center_half_edge_deci_cent") {
		return ws::LifecyclePriceLevelStructure::CenterHalfEdgeDeciCent;
	}
	if (text == "center_quint_edge_quint_cent") {
		return ws::LifecyclePriceLevelStructure::CenterQuintEdgeQuintCent;
	}
	if (text == "center_quint_edge_deci_cent") {
		return ws::LifecyclePriceLevelStructure::CenterQuintEdgeDeciCent;
	}
	if (text == "center_centi_edge_centi_cent") {
		return ws::LifecyclePriceLevelStructure::CenterCentiEdgeCentiCent;
	}
	if (text == "center_deci_edge_centi_cent") {
		return ws::LifecyclePriceLevelStructure::CenterDeciEdgeCentiCent;
	}
	return ws::LifecyclePriceLevelStructure::Unknown;
}

inline ws::MarketLifecycleV2EventType
parse_ws_market_lifecycle_v2_event_type(std::string_view text) noexcept {
	if (text == "created") {
		return ws::MarketLifecycleV2EventType::Created;
	}
	if (text == "deactivated") {
		return ws::MarketLifecycleV2EventType::Deactivated;
	}
	if (text == "activated") {
		return ws::MarketLifecycleV2EventType::Activated;
	}
	if (text == "close_date_updated") {
		return ws::MarketLifecycleV2EventType::CloseDateUpdated;
	}
	if (text == "determined") {
		return ws::MarketLifecycleV2EventType::Determined;
	}
	if (text == "settled") {
		return ws::MarketLifecycleV2EventType::Settled;
	}
	if (text == "price_level_structure_updated") {
		return ws::MarketLifecycleV2EventType::PriceLevelStructureUpdated;
	}
	return ws::MarketLifecycleV2EventType::Unknown;
}

inline ws::MultivariateMarketLifecycleEventType
parse_ws_multivariate_market_lifecycle_event_type(std::string_view text) noexcept {
	if (text == "created") {
		return ws::MultivariateMarketLifecycleEventType::Created;
	}
	if (text == "deactivated") {
		return ws::MultivariateMarketLifecycleEventType::Deactivated;
	}
	if (text == "activated") {
		return ws::MultivariateMarketLifecycleEventType::Activated;
	}
	if (text == "close_date_updated") {
		return ws::MultivariateMarketLifecycleEventType::CloseDateUpdated;
	}
	if (text == "determined") {
		return ws::MultivariateMarketLifecycleEventType::Determined;
	}
	if (text == "settled") {
		return ws::MultivariateMarketLifecycleEventType::Settled;
	}
	return ws::MultivariateMarketLifecycleEventType::Unknown;
}

inline ws::OrderAction parse_ws_order_action(std::string_view text) noexcept {
	if (text == "buy") {
		return ws::OrderAction::Buy;
	}
	if (text == "sell") {
		return ws::OrderAction::Sell;
	}
	if (text == "sell_partial") {
		return ws::OrderAction::SellPartial;
	}
	if (text == "sell_to_close") {
		return ws::OrderAction::SellToClose;
	}
	if (text.empty()) {
		return ws::OrderAction::Unset;
	}
	return ws::OrderAction::Unknown;
}

inline ws::OrderGroupUpdatesEventType
parse_ws_order_group_updates_event_type(std::string_view text) noexcept {
	if (text == "created") {
		return ws::OrderGroupUpdatesEventType::Created;
	}
	if (text == "triggered") {
		return ws::OrderGroupUpdatesEventType::Triggered;
	}
	if (text == "reset") {
		return ws::OrderGroupUpdatesEventType::Reset;
	}
	if (text == "deleted") {
		return ws::OrderGroupUpdatesEventType::Deleted;
	}
	if (text == "limit_updated") {
		return ws::OrderGroupUpdatesEventType::LimitUpdated;
	}
	return ws::OrderGroupUpdatesEventType::Unknown;
}

inline ws::UpdateAction parse_ws_update_action(std::string_view text) noexcept {
	if (text == "add_markets") {
		return ws::UpdateAction::AddMarkets;
	}
	if (text == "delete_markets") {
		return ws::UpdateAction::DeleteMarkets;
	}
	if (text == "get_snapshot") {
		return ws::UpdateAction::GetSnapshot;
	}
	if (text == "subscribe_indices") {
		return ws::UpdateAction::SubscribeIndices;
	}
	if (text == "unsubscribe_indices") {
		return ws::UpdateAction::UnsubscribeIndices;
	}
	if (text == "indexlist") {
		return ws::UpdateAction::Indexlist;
	}
	if (text == "subscribe_underlyings") {
		return ws::UpdateAction::SubscribeUnderlyings;
	}
	if (text == "unsubscribe_underlyings") {
		return ws::UpdateAction::UnsubscribeUnderlyings;
	}
	if (text == "underlying_list") {
		return ws::UpdateAction::UnderlyingList;
	}
	return ws::UpdateAction::Unknown;
}

inline ws::UserFilter parse_ws_user_filter(std::string_view text) noexcept {
	if (text.empty()) {
		return ws::UserFilter::Unset;
	}
	if (text == "self") {
		return ws::UserFilter::Self;
	}
	return ws::UserFilter::Unknown;
}

/// `SubscribeParams` plus the `channels` the client fills in, in wire order.
struct SubscribeWire {
	std::vector<ws::Channel> channels;
	std::optional<std::string> market_ticker;
	std::optional<std::vector<std::string>> market_tickers;
	std::optional<std::string> market_id;
	std::optional<std::vector<std::string>> market_ids;
	std::optional<bool> send_initial_snapshot;
	std::optional<bool> skip_ticker_ack;
	std::optional<bool> use_yes_price;
	std::optional<ws::UserFilter> user_filter;
	std::optional<std::int64_t> shard_factor;
	std::optional<std::int64_t> shard_key;
	std::optional<std::vector<std::string>> index_ids;
	std::optional<std::vector<std::string>> underlying_tickers;
};

inline SubscribeWire to_wire(std::vector<ws::Channel> channels, const ws::SubscribeParams& params) {
	SubscribeWire wire;
	wire.channels = std::move(channels);
	wire.market_ticker = params.market_ticker;
	if (!params.market_tickers.empty()) {
		wire.market_tickers = params.market_tickers;
	}
	wire.market_id = params.market_id;
	if (!params.market_ids.empty()) {
		wire.market_ids = params.market_ids;
	}
	wire.send_initial_snapshot = params.send_initial_snapshot;
	wire.skip_ticker_ack = params.skip_ticker_ack;
	wire.use_yes_price = params.use_yes_price;
	wire.user_filter = params.user_filter;
	wire.shard_factor = params.shard_factor;
	wire.shard_key = params.shard_key;
	if (!params.index_ids.empty()) {
		wire.index_ids = params.index_ids;
	}
	if (!params.underlying_tickers.empty()) {
		wire.underlying_tickers = params.underlying_tickers;
	}
	return wire;
}

/// `UpdateSubscriptionParams` plus the `sids` the client fills in, in wire order.
struct UpdateSubscriptionWire {
	std::vector<std::int64_t> sids;
	std::optional<std::string> market_ticker;
	std::optional<std::vector<std::string>> market_tickers;
	std::optional<std::string> market_id;
	std::optional<std::vector<std::string>> market_ids;
	std::optional<bool> send_initial_snapshot;
	ws::UpdateAction action{};
	std::optional<std::vector<std::string>> index_ids;
	std::optional<std::vector<std::string>> underlying_tickers;
};

inline UpdateSubscriptionWire to_wire(std::vector<std::int64_t> sids,
									  const ws::UpdateSubscriptionParams& params) {
	UpdateSubscriptionWire wire;
	wire.sids = std::move(sids);
	wire.market_ticker = params.market_ticker;
	if (!params.market_tickers.empty()) {
		wire.market_tickers = params.market_tickers;
	}
	wire.market_id = params.market_id;
	if (!params.market_ids.empty()) {
		wire.market_ids = params.market_ids;
	}
	wire.send_initial_snapshot = params.send_initial_snapshot;
	wire.action = params.action;
	if (!params.index_ids.empty()) {
		wire.index_ids = params.index_ids;
	}
	if (!params.underlying_tickers.empty()) {
		wire.underlying_tickers = params.underlying_tickers;
	}
	return wire;
}

/// Parses a data frame whose envelope `type` is `type`.
inline std::optional<WsMessage> parse_data_frame(std::string_view type, const std::string& json) {
	if (type == "orderbook_snapshot") {
		return read_update<ws::OrderbookSnapshot>(json);
	}
	if (type == "orderbook_delta") {
		return read_update<ws::OrderbookDelta>(json);
	}
	if (type == "ticker") {
		return read_update<ws::Ticker>(json);
	}
	if (type == "trade") {
		return read_update<ws::Trade>(json);
	}
	if (type == "fill") {
		return read_update<ws::Fill>(json);
	}
	if (type == "market_position") {
		return read_update<ws::MarketPosition>(json);
	}
	if (type == "event_lifecycle") {
		return read_update<ws::EventLifecycle>(json);
	}
	if (type == "event_fee_update") {
		return read_update<ws::EventFeeUpdate>(json);
	}
	if (type == "multivariate_market_lifecycle") {
		return read_update<ws::MultivariateMarketLifecycle>(json);
	}
	if (type == "rfq_created") {
		return read_update<ws::RfqCreated>(json);
	}
	if (type == "rfq_deleted") {
		return read_update<ws::RfqDeleted>(json);
	}
	if (type == "quote_created") {
		return read_update<ws::QuoteCreated>(json);
	}
	if (type == "quote_accepted") {
		return read_update<ws::QuoteAccepted>(json);
	}
	if (type == "quote_executed") {
		return read_update<ws::QuoteExecuted>(json);
	}
	if (type == "order_group_updates") {
		return read_update<ws::OrderGroupUpdates>(json);
	}
	if (type == "user_order") {
		return read_update<ws::UserOrder>(json);
	}
	if (type == "cfbenchmarks_value") {
		return read_update<ws::CfbenchmarksValue>(json);
	}
	if (type == "cfbenchmarks_value_indexlist") {
		return read_update<ws::CfbenchmarksIndexList>(json);
	}
	if (type == "cfbenchmarks_value_5hz") {
		return read_update<ws::CfbenchmarksValue5Hz>(json);
	}
	if (type == "cfbenchmarks_value_5hz_indexlist") {
		return read_update<ws::Cfbenchmarks5HzIndexList>(json);
	}
	if (type == "pyth_value") {
		return read_update<ws::PythValue>(json);
	}
	if (type == "pyth_value_underlying_list") {
		return read_update<ws::PythUnderlyingList>(json);
	}
	if (type == "market_lifecycle_v2") {
		if (msg_event_type(json) == "metadata_updated") {
			return read_update<ws::MarketMetadataUpdated>(json);
		}
		return read_update<ws::MarketLifecycleV2>(json);
	}
	return std::nullopt;
}

/// Whether `type` names a data message this SDK version parses.
inline bool is_data_type(std::string_view type) noexcept {
	return type == "cfbenchmarks_value" || type == "cfbenchmarks_value_5hz" ||
		   type == "cfbenchmarks_value_5hz_indexlist" || type == "cfbenchmarks_value_indexlist" ||
		   type == "event_fee_update" || type == "event_lifecycle" || type == "fill" ||
		   type == "market_lifecycle_v2" || type == "market_position" ||
		   type == "multivariate_market_lifecycle" || type == "order_group_updates" ||
		   type == "orderbook_delta" || type == "orderbook_snapshot" || type == "pyth_value" ||
		   type == "pyth_value_underlying_list" || type == "quote_accepted" ||
		   type == "quote_created" || type == "quote_executed" || type == "rfq_created" ||
		   type == "rfq_deleted" || type == "ticker" || type == "trade" || type == "user_order";
}

} // namespace kalshi::detail

namespace glz {

template <>
struct from<JSON, kalshi::ws::Channel> {
	template <auto Opts>
	static void op(kalshi::ws::Channel& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_channel(text);
	}
};

template <>
struct to<JSON, kalshi::ws::Channel> {
	template <auto Opts>
	static void op(const kalshi::ws::Channel& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::CollateralReturnType> {
	template <auto Opts>
	static void op(kalshi::ws::CollateralReturnType& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_collateral_return_type(text);
	}
};

template <>
struct to<JSON, kalshi::ws::CollateralReturnType> {
	template <auto Opts>
	static void op(const kalshi::ws::CollateralReturnType& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::FeeTypeOverride> {
	template <auto Opts>
	static void op(kalshi::ws::FeeTypeOverride& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_fee_type_override(text);
	}
};

template <>
struct to<JSON, kalshi::ws::FeeTypeOverride> {
	template <auto Opts>
	static void op(const kalshi::ws::FeeTypeOverride& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::LifecyclePriceLevelStructure> {
	template <auto Opts>
	static void op(kalshi::ws::LifecyclePriceLevelStructure& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_lifecycle_price_level_structure(text);
	}
};

template <>
struct to<JSON, kalshi::ws::LifecyclePriceLevelStructure> {
	template <auto Opts>
	static void op(const kalshi::ws::LifecyclePriceLevelStructure& value, auto&& ctx,
				   auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::MarketLifecycleV2EventType> {
	template <auto Opts>
	static void op(kalshi::ws::MarketLifecycleV2EventType& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_market_lifecycle_v2_event_type(text);
	}
};

template <>
struct to<JSON, kalshi::ws::MarketLifecycleV2EventType> {
	template <auto Opts>
	static void op(const kalshi::ws::MarketLifecycleV2EventType& value, auto&& ctx,
				   auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::MultivariateMarketLifecycleEventType> {
	template <auto Opts>
	static void op(kalshi::ws::MultivariateMarketLifecycleEventType& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_multivariate_market_lifecycle_event_type(text);
	}
};

template <>
struct to<JSON, kalshi::ws::MultivariateMarketLifecycleEventType> {
	template <auto Opts>
	static void op(const kalshi::ws::MultivariateMarketLifecycleEventType& value, auto&& ctx,
				   auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::OrderAction> {
	template <auto Opts>
	static void op(kalshi::ws::OrderAction& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_order_action(text);
	}
};

template <>
struct to<JSON, kalshi::ws::OrderAction> {
	template <auto Opts>
	static void op(const kalshi::ws::OrderAction& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::OrderGroupUpdatesEventType> {
	template <auto Opts>
	static void op(kalshi::ws::OrderGroupUpdatesEventType& value, auto&& ctx, auto&& it,
				   auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_order_group_updates_event_type(text);
	}
};

template <>
struct to<JSON, kalshi::ws::OrderGroupUpdatesEventType> {
	template <auto Opts>
	static void op(const kalshi::ws::OrderGroupUpdatesEventType& value, auto&& ctx,
				   auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::UpdateAction> {
	template <auto Opts>
	static void op(kalshi::ws::UpdateAction& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_update_action(text);
	}
};

template <>
struct to<JSON, kalshi::ws::UpdateAction> {
	template <auto Opts>
	static void op(const kalshi::ws::UpdateAction& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

template <>
struct from<JSON, kalshi::ws::UserFilter> {
	template <auto Opts>
	static void op(kalshi::ws::UserFilter& value, auto&& ctx, auto&& it, auto&& end) {
		std::string text;
		parse<JSON>::op<Opts>(text, ctx, it, end);
		value = kalshi::detail::parse_ws_user_filter(text);
	}
};

template <>
struct to<JSON, kalshi::ws::UserFilter> {
	template <auto Opts>
	static void op(const kalshi::ws::UserFilter& value, auto&& ctx, auto&&... args) {
		const std::string_view text = kalshi::ws::to_string(value);
		serialize<JSON>::op<Opts>(text, ctx, args...);
	}
};

} // namespace glz
