// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetAccountApiLimitsResponse> KalshiClient::get_account_api_limits() {
	return detail::decode<GetAccountApiLimitsResponse>(
		impl_->send(HttpMethod::GET, std::string{"/account/limits"}, {}, "get_account_api_limits"));
}

Result<void> KalshiClient::upgrade_account_api_usage_level() {
	return detail::expect_success(impl_->send(HttpMethod::POST,
											  std::string{"/account/api_usage_level/upgrade"}, {},
											  "upgrade_account_api_usage_level"));
}

Result<std::vector<AccountApiUsageLevelVolumeProgress>>
KalshiClient::get_account_api_usage_level_volume_progress() {
	Result<GetAccountApiUsageLevelVolumeProgressResponse> response =
		detail::decode<GetAccountApiUsageLevelVolumeProgressResponse>(
			impl_->send(HttpMethod::GET, std::string{"/account/api_usage_level/volume_progress"},
						{}, "get_account_api_usage_level_volume_progress"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->volume_progress);
}

Result<GetAccountEndpointCostsResponse> KalshiClient::get_account_endpoint_costs() {
	return detail::decode<GetAccountEndpointCostsResponse>(impl_->send(
		HttpMethod::GET, std::string{"/account/endpoint_costs"}, {}, "get_account_endpoint_costs"));
}

} // namespace kalshi
