// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<std::string> KalshiClient::get_communications_id() {
	Result<GetCommunicationsIDResponse> response =
		detail::decode<GetCommunicationsIDResponse>(impl_->send(
			HttpMethod::GET, std::string{"/communications/id"}, {}, "get_communications_id"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->communications_id);
}

Result<GetBlockTradeProposalsResponse>
KalshiClient::get_block_trade_proposals(const GetBlockTradeProposalsParams& params) {
	detail::Query query(std::string{"/communications/block-trade-proposals"});
	query.add("cursor", params.cursor);
	query.add("market_ticker", params.market_ticker);
	query.add("limit", params.limit);
	query.add("status", params.status);
	return detail::decode<GetBlockTradeProposalsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_block_trade_proposals"));
}

Result<std::string> KalshiClient::propose_block_trade(const ProposeBlockTradeRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<ProposeBlockTradeResponse> response = detail::decode<ProposeBlockTradeResponse>(
		impl_->send(HttpMethod::POST, std::string{"/communications/block-trade-proposals"},
					detail::encode(body), "propose_block_trade"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->block_trade_proposal_id);
}

Result<void>
KalshiClient::accept_block_trade_proposal(std::string_view block_trade_proposal_id,
										  const AcceptBlockTradeProposalRequest& body) {
	Result<std::string> target = detail::expand_path(
		"/communications/block-trade-proposals/{block_trade_proposal_id}/accept",
		{block_trade_proposal_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(impl_->send(HttpMethod::POST, *target, detail::encode(body),
											  "accept_block_trade_proposal"));
}

Result<GetRFQsResponse> KalshiClient::get_rfqs(const GetRfqsParams& params) {
	detail::Query query(std::string{"/communications/rfqs"});
	query.add("cursor", params.cursor);
	query.add("event_ticker", params.event_ticker);
	query.add("market_ticker", params.market_ticker);
	query.add("subaccount", params.subaccount);
	query.add("limit", params.limit);
	query.add("status", params.status);
	query.add("creator_user_id", params.creator_user_id);
	query.add("user_filter", params.user_filter);
	return detail::decode<GetRFQsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_rfqs"));
}

Result<std::string> KalshiClient::create_rfq(const CreateRFQRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<CreateRFQResponse> response = detail::decode<CreateRFQResponse>(impl_->send(
		HttpMethod::POST, std::string{"/communications/rfqs"}, detail::encode(body), "create_rfq"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->id);
}

Result<RFQ> KalshiClient::get_rfq(std::string_view rfq_id) {
	Result<std::string> target = detail::expand_path("/communications/rfqs/{rfq_id}", {rfq_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetRFQResponse> response =
		detail::decode<GetRFQResponse>(impl_->send(HttpMethod::GET, *target, {}, "get_rfq"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->rfq);
}

Result<void> KalshiClient::delete_rfq(std::string_view rfq_id) {
	Result<std::string> target = detail::expand_path("/communications/rfqs/{rfq_id}", {rfq_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(impl_->send(HttpMethod::DEL, *target, {}, "delete_rfq"));
}

Result<Quote> KalshiClient::get_rfq_quote(std::string_view rfq_id, std::string_view quote_id) {
	Result<std::string> target =
		detail::expand_path("/communications/rfqs/{rfq_id}/quotes/{quote_id}", {rfq_id, quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetQuoteResponse> response = detail::decode<GetQuoteResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_rfq_quote"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->quote);
}

Result<void> KalshiClient::delete_rfq_quote(std::string_view rfq_id, std::string_view quote_id) {
	Result<std::string> target =
		detail::expand_path("/communications/rfqs/{rfq_id}/quotes/{quote_id}", {rfq_id, quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(impl_->send(HttpMethod::DEL, *target, {}, "delete_rfq_quote"));
}

Result<void> KalshiClient::accept_rfq_quote(std::string_view rfq_id, std::string_view quote_id,
											const AcceptQuoteRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<std::string> target = detail::expand_path(
		"/communications/rfqs/{rfq_id}/quotes/{quote_id}/accept", {rfq_id, quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(
		impl_->send(HttpMethod::PUT, *target, detail::encode(body), "accept_rfq_quote"));
}

Result<void> KalshiClient::confirm_rfq_quote(std::string_view rfq_id, std::string_view quote_id) {
	Result<std::string> target = detail::expand_path(
		"/communications/rfqs/{rfq_id}/quotes/{quote_id}/confirm", {rfq_id, quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(
		impl_->send(HttpMethod::PUT, *target, std::string{"{}"}, "confirm_rfq_quote"));
}

Result<GetQuotesResponse> KalshiClient::get_quotes(const GetQuotesParams& params) {
	detail::Query query(std::string{"/communications/quotes"});
	query.add("cursor", params.cursor);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("limit", params.limit);
	query.add("status", params.status);
	query.add("quote_creator_user_id", params.quote_creator_user_id);
	query.add("user_filter", params.user_filter);
	query.add("rfq_user_filter", params.rfq_user_filter);
	query.add("rfq_creator_user_id", params.rfq_creator_user_id);
	query.add("rfq_creator_subtrader_id", params.rfq_creator_subtrader_id);
	query.add("rfq_id", params.rfq_id);
	return detail::decode<GetQuotesResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_quotes"));
}

Result<std::string> KalshiClient::create_quote(const CreateQuoteRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<CreateQuoteResponse> response = detail::decode<CreateQuoteResponse>(
		impl_->send(HttpMethod::POST, std::string{"/communications/quotes"}, detail::encode(body),
					"create_quote"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->id);
}

Result<Quote> KalshiClient::get_quote(std::string_view quote_id) {
	Result<std::string> target =
		detail::expand_path("/communications/quotes/{quote_id}", {quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetQuoteResponse> response =
		detail::decode<GetQuoteResponse>(impl_->send(HttpMethod::GET, *target, {}, "get_quote"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->quote);
}

Result<void> KalshiClient::delete_quote(std::string_view quote_id) {
	Result<std::string> target =
		detail::expand_path("/communications/quotes/{quote_id}", {quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(impl_->send(HttpMethod::DEL, *target, {}, "delete_quote"));
}

Result<void> KalshiClient::accept_quote(std::string_view quote_id, const AcceptQuoteRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<std::string> target =
		detail::expand_path("/communications/quotes/{quote_id}/accept", {quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(
		impl_->send(HttpMethod::PUT, *target, detail::encode(body), "accept_quote"));
}

Result<void> KalshiClient::confirm_quote(std::string_view quote_id) {
	Result<std::string> target =
		detail::expand_path("/communications/quotes/{quote_id}/confirm", {quote_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::expect_success(
		impl_->send(HttpMethod::PUT, *target, std::string{"{}"}, "confirm_quote"));
}

} // namespace kalshi
