// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetEventCandlesticksResponse>
KalshiClient::get_market_candlesticks_by_event(std::string_view series_ticker,
											   std::string_view ticker,
											   const GetMarketCandlesticksByEventParams& params) {
	Result<std::string> target = detail::expand_path(
		"/series/{series_ticker}/events/{ticker}/candlesticks", {series_ticker, ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("start_ts", params.start_ts);
	query.add("end_ts", params.end_ts);
	query.add("period_interval", params.period_interval);
	return detail::decode<GetEventCandlesticksResponse>(impl_->send(
		HttpMethod::GET, std::move(query).str(), {}, "get_market_candlesticks_by_event"));
}

Result<GetEventsResponse> KalshiClient::get_events(const GetEventsParams& params) {
	detail::Query query(std::string{"/events"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("with_nested_markets", params.with_nested_markets);
	query.add("with_milestones", params.with_milestones);
	query.add("status", params.status);
	query.add("series_ticker", params.series_ticker);
	query.add("tickers", params.tickers);
	query.add("min_close_ts", params.min_close_ts);
	query.add("min_updated_ts", params.min_updated_ts);
	return detail::decode<GetEventsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_events"));
}

Result<GetMultivariateEventsResponse>
KalshiClient::get_multivariate_events(const GetMultivariateEventsParams& params) {
	detail::Query query(std::string{"/events/multivariate"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("series_ticker", params.series_ticker);
	query.add("collection_ticker", params.collection_ticker);
	query.add("with_nested_markets", params.with_nested_markets);
	return detail::decode<GetMultivariateEventsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_multivariate_events"));
}

Result<GetEventFeeChangesResponse>
KalshiClient::get_event_fee_changes(const GetEventFeeChangesParams& params) {
	detail::Query query(std::string{"/events/fee_changes"});
	query.add("event_ticker", params.event_ticker);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetEventFeeChangesResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_event_fee_changes"));
}

Result<GetEventResponse> KalshiClient::get_event(std::string_view event_ticker,
												 const GetEventParams& params) {
	Result<std::string> target = detail::expand_path("/events/{event_ticker}", {event_ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("with_nested_markets", params.with_nested_markets);
	return detail::decode<GetEventResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_event"));
}

Result<GetEventMetadataResponse> KalshiClient::get_event_metadata(std::string_view event_ticker) {
	Result<std::string> target =
		detail::expand_path("/events/{event_ticker}/metadata", {event_ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::decode<GetEventMetadataResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_event_metadata"));
}

Result<std::vector<ForecastPercentilesPoint>> KalshiClient::get_event_forecast_percentiles_history(
	std::string_view series_ticker, std::string_view ticker,
	const GetEventForecastPercentilesHistoryParams& params) {
	Result<std::string> target =
		detail::expand_path("/series/{series_ticker}/events/{ticker}/forecast_percentile_history",
							{series_ticker, ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("percentiles", params.percentiles);
	query.add("start_ts", params.start_ts);
	query.add("end_ts", params.end_ts);
	query.add("period_interval", params.period_interval);
	Result<GetEventForecastPercentilesHistoryResponse> response =
		detail::decode<GetEventForecastPercentilesHistoryResponse>(impl_->send(
			HttpMethod::GET, std::move(query).str(), {}, "get_event_forecast_percentiles_history"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->forecast_history);
}

} // namespace kalshi
