// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<ExchangeStatus> KalshiClient::get_exchange_status() {
	return detail::decode<ExchangeStatus>(
		impl_->send(HttpMethod::GET, std::string{"/exchange/status"}, {}, "get_exchange_status"));
}

Result<std::vector<SeriesFeeChange>>
KalshiClient::get_series_fee_changes(const GetSeriesFeeChangesParams& params) {
	detail::Query query(std::string{"/series/fee_changes"});
	query.add("series_ticker", params.series_ticker);
	query.add("show_historical", params.show_historical);
	Result<GetSeriesFeeChangesResponse> response = detail::decode<GetSeriesFeeChangesResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_series_fee_changes"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->series_fee_change_arr);
}

Result<Schedule> KalshiClient::get_exchange_schedule() {
	Result<GetExchangeScheduleResponse> response =
		detail::decode<GetExchangeScheduleResponse>(impl_->send(
			HttpMethod::GET, std::string{"/exchange/schedule"}, {}, "get_exchange_schedule"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->schedule);
}

Result<std::string> KalshiClient::get_user_data_timestamp() {
	Result<GetUserDataTimestampResponse> response = detail::decode<GetUserDataTimestampResponse>(
		impl_->send(HttpMethod::GET, std::string{"/exchange/user_data_timestamp"}, {},
					"get_user_data_timestamp"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->as_of_time);
}

} // namespace kalshi
