// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetFcmFillsResponse> KalshiClient::get_fcm_fills(const GetFcmFillsParams& params) {
	detail::Query query(std::string{"/fcm/fills"});
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("cursor", params.cursor);
	return detail::decode<GetFcmFillsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_fcm_fills"));
}

Result<GetOrdersResponse> KalshiClient::get_fcm_orders(const GetFcmOrdersParams& params) {
	detail::Query query(std::string{"/fcm/orders"});
	query.add("subtrader_id", params.subtrader_id);
	query.add("client_order_ids", params.client_order_ids);
	query.add("cursor", params.cursor);
	query.add("event_ticker", params.event_ticker);
	query.add("ticker", params.ticker);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("status", params.status);
	query.add("limit", params.limit);
	return detail::decode<GetOrdersResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_fcm_orders"));
}

Result<std::vector<FCMSubtrader>> KalshiClient::get_fcm_subtraders() {
	Result<ListFCMSubtradersResponse> response = detail::decode<ListFCMSubtradersResponse>(
		impl_->send(HttpMethod::GET, std::string{"/fcm/subtraders"}, {}, "get_fcm_subtraders"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->subtraders);
}

Result<std::string> KalshiClient::create_fcm_subtrader(const CreateFCMSubtraderRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<CreateFCMSubtraderResponse> response = detail::decode<CreateFCMSubtraderResponse>(
		impl_->send(HttpMethod::POST, std::string{"/fcm/subtraders"}, detail::encode(body),
					"create_fcm_subtrader"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->subtrader_id);
}

Result<GetFCMEventContractDailyCapResponse>
KalshiClient::get_fcm_event_contract_daily_cap(const GetFcmEventContractDailyCapParams& params) {
	detail::Query query(std::string{"/fcm/subtraders/event_contract_daily_cap"});
	query.add("subtrader_id", params.subtrader_id);
	return detail::decode<GetFCMEventContractDailyCapResponse>(impl_->send(
		HttpMethod::GET, std::move(query).str(), {}, "get_fcm_event_contract_daily_cap"));
}

Result<void> KalshiClient::update_fcm_event_contract_daily_cap(
	const UpdateFCMEventContractDailyCapRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	return detail::expect_success(
		impl_->send(HttpMethod::PUT, std::string{"/fcm/subtraders/event_contract_daily_cap"},
					detail::encode(body), "update_fcm_event_contract_daily_cap"));
}

Result<void> KalshiClient::delete_fcm_event_contract_daily_cap(
	const DeleteFcmEventContractDailyCapParams& params) {
	detail::Query query(std::string{"/fcm/subtraders/event_contract_daily_cap"});
	query.add("subtrader_id", params.subtrader_id);
	return detail::expect_success(impl_->send(HttpMethod::DEL, std::move(query).str(), {},
											  "delete_fcm_event_contract_daily_cap"));
}

Result<std::vector<std::string>> KalshiClient::get_fcm_subtrader_blocked_categories(
	const GetFcmSubtraderBlockedCategoriesParams& params) {
	detail::Query query(std::string{"/fcm/subtraders/blocked_categories"});
	query.add("subtrader_id", params.subtrader_id);
	Result<GetFCMSubtraderBlockedCategoriesResponse> response =
		detail::decode<GetFCMSubtraderBlockedCategoriesResponse>(impl_->send(
			HttpMethod::GET, std::move(query).str(), {}, "get_fcm_subtrader_blocked_categories"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->categories);
}

Result<std::vector<std::string>> KalshiClient::update_fcm_subtrader_blocked_categories(
	const UpdateFCMSubtraderBlockedCategoriesRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<UpdateFCMSubtraderBlockedCategoriesResponse> response =
		detail::decode<UpdateFCMSubtraderBlockedCategoriesResponse>(
			impl_->send(HttpMethod::PUT, std::string{"/fcm/subtraders/blocked_categories"},
						detail::encode(body), "update_fcm_subtrader_blocked_categories"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->categories);
}

Result<GetPositionsResponse> KalshiClient::get_fcm_positions(const GetFcmPositionsParams& params) {
	detail::Query query(std::string{"/fcm/positions"});
	query.add("subtrader_id", params.subtrader_id);
	query.add("ticker", params.ticker);
	query.add("event_ticker", params.event_ticker);
	query.add("count_filter", params.count_filter);
	query.add("settlement_status", params.settlement_status);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetPositionsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_fcm_positions"));
}

} // namespace kalshi
