// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetHistoricalCutoffResponse> KalshiClient::get_historical_cutoff() {
	return detail::decode<GetHistoricalCutoffResponse>(impl_->send(
		HttpMethod::GET, std::string{"/historical/cutoff"}, {}, "get_historical_cutoff"));
}

Result<GetMarketCandlesticksHistoricalResponse> KalshiClient::get_market_candlesticks_historical(
	std::string_view ticker, const GetMarketCandlesticksHistoricalParams& params) {
	Result<std::string> target =
		detail::expand_path("/historical/markets/{ticker}/candlesticks", {ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("start_ts", params.start_ts);
	query.add("end_ts", params.end_ts);
	query.add("period_interval", params.period_interval);
	return detail::decode<GetMarketCandlesticksHistoricalResponse>(impl_->send(
		HttpMethod::GET, std::move(query).str(), {}, "get_market_candlesticks_historical"));
}

Result<GetFillsResponse>
KalshiClient::get_fills_historical(const GetFillsHistoricalParams& params) {
	detail::Query query(std::string{"/historical/fills"});
	query.add("ticker", params.ticker);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("subaccount", params.subaccount);
	return detail::decode<GetFillsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_fills_historical"));
}

Result<GetOrdersResponse>
KalshiClient::get_historical_orders(const GetHistoricalOrdersParams& params) {
	detail::Query query(std::string{"/historical/orders"});
	query.add("ticker", params.ticker);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("subaccount", params.subaccount);
	return detail::decode<GetOrdersResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_historical_orders"));
}

Result<GetPositionsResponse>
KalshiClient::get_historical_positions(const GetHistoricalPositionsParams& params) {
	detail::Query query(std::string{"/historical/positions"});
	query.add("ticker", params.ticker);
	query.add("event_ticker", params.event_ticker);
	query.add("subaccount", params.subaccount);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetPositionsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_historical_positions"));
}

Result<GetTradesResponse>
KalshiClient::get_trades_historical(const GetTradesHistoricalParams& params) {
	detail::Query query(std::string{"/historical/trades"});
	query.add("ticker", params.ticker);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("is_block_trade", params.is_block_trade);
	return detail::decode<GetTradesResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_trades_historical"));
}

Result<GetMarketsResponse>
KalshiClient::get_historical_markets(const GetHistoricalMarketsParams& params) {
	detail::Query query(std::string{"/historical/markets"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("tickers", params.tickers);
	query.add("event_ticker", params.event_ticker);
	query.add("series_ticker", params.series_ticker);
	query.add("mve_filter", params.mve_filter);
	return detail::decode<GetMarketsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_historical_markets"));
}

Result<Market> KalshiClient::get_historical_market(std::string_view ticker) {
	Result<std::string> target = detail::expand_path("/historical/markets/{ticker}", {ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetMarketResponse> response = detail::decode<GetMarketResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_historical_market"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->market);
}

} // namespace kalshi
