// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetIncentiveProgramsResponse>
KalshiClient::get_incentive_programs(const GetIncentiveProgramsParams& params) {
	detail::Query query(std::string{"/incentive_programs"});
	query.add("status", params.status);
	query.add("type", params.type);
	query.add("incentive_description", params.incentive_description);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetIncentiveProgramsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_incentive_programs"));
}

} // namespace kalshi
