// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<LiveData>
KalshiClient::get_live_data_by_milestone(std::string_view milestone_id,
										 const GetLiveDataByMilestoneParams& params) {
	Result<std::string> target =
		detail::expand_path("/live_data/milestone/{milestone_id}", {milestone_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("include_player_stats", params.include_player_stats);
	Result<GetLiveDataResponse> response = detail::decode<GetLiveDataResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_live_data_by_milestone"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->live_data);
}

Result<LiveData> KalshiClient::get_live_data(std::string_view type, std::string_view milestone_id,
											 const GetLiveDataParams& params) {
	Result<std::string> target =
		detail::expand_path("/live_data/{type}/milestone/{milestone_id}", {type, milestone_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("include_player_stats", params.include_player_stats);
	Result<GetLiveDataResponse> response = detail::decode<GetLiveDataResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_live_data"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->live_data);
}

Result<std::vector<LiveData>> KalshiClient::get_live_datas(const GetLiveDatasParams& params) {
	detail::Query query(std::string{"/live_data/batch"});
	query.add("milestone_ids", params.milestone_ids);
	query.add("include_player_stats", params.include_player_stats);
	Result<GetLiveDatasResponse> response = detail::decode<GetLiveDatasResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_live_datas"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->live_datas);
}

Result<std::optional<PlayByPlay>> KalshiClient::get_game_stats(std::string_view milestone_id) {
	Result<std::string> target =
		detail::expand_path("/live_data/milestone/{milestone_id}/game_stats", {milestone_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetGameStatsResponse> response = detail::decode<GetGameStatsResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_game_stats"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->pbp);
}

Result<EventLiveData> KalshiClient::get_event_live_data(std::string_view event_ticker,
														const GetEventLiveDataParams& params) {
	Result<std::string> target =
		detail::expand_path("/live_data/events/{event_ticker}", {event_ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("range", params.range);
	Result<GetEventLiveDataResponse> response = detail::decode<GetEventLiveDataResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_event_live_data"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->live_data);
}

Result<GetWeatherIndexResponse>
KalshiClient::get_weather_index(std::string_view city, const GetWeatherIndexParams& params) {
	Result<std::string> target = detail::expand_path("/live_data/weather/{city}", {city});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("from", params.from);
	query.add("to", params.to);
	query.add("last_sec", params.last_sec);
	query.add("detailed", params.detailed);
	return detail::decode<GetWeatherIndexResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_weather_index"));
}

Result<GetWeatherIndexCalibrationsResponse>
KalshiClient::get_weather_index_calibrations(std::string_view city) {
	Result<std::string> target =
		detail::expand_path("/live_data/weather/{city}/calibrations", {city});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::decode<GetWeatherIndexCalibrationsResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_weather_index_calibrations"));
}

} // namespace kalshi
