// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetMarketCandlesticksResponse>
KalshiClient::get_market_candlesticks(std::string_view series_ticker, std::string_view ticker,
									  const GetMarketCandlesticksParams& params) {
	Result<std::string> target = detail::expand_path(
		"/series/{series_ticker}/markets/{ticker}/candlesticks", {series_ticker, ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("start_ts", params.start_ts);
	query.add("end_ts", params.end_ts);
	query.add("period_interval", params.period_interval);
	query.add("include_latest_before_start", params.include_latest_before_start);
	return detail::decode<GetMarketCandlesticksResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_market_candlesticks"));
}

Result<GetTradesResponse> KalshiClient::get_trades(const GetTradesParams& params) {
	detail::Query query(std::string{"/markets/trades"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("ticker", params.ticker);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("is_block_trade", params.is_block_trade);
	return detail::decode<GetTradesResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_trades"));
}

Result<OrderbookCountFp>
KalshiClient::get_market_orderbook(std::string_view ticker,
								   const GetMarketOrderbookParams& params) {
	Result<std::string> target = detail::expand_path("/markets/{ticker}/orderbook", {ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("depth", params.depth);
	Result<GetMarketOrderbookResponse> response = detail::decode<GetMarketOrderbookResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_market_orderbook"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->orderbook_fp);
}

Result<std::vector<MarketOrderbookFp>>
KalshiClient::get_market_orderbooks(const GetMarketOrderbooksParams& params) {
	detail::Query query(std::string{"/markets/orderbooks"});
	query.add("tickers", params.tickers);
	Result<GetMarketOrderbooksResponse> response = detail::decode<GetMarketOrderbooksResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_market_orderbooks"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->orderbooks);
}

Result<Series> KalshiClient::get_series(std::string_view series_ticker,
										const GetSeriesParams& params) {
	Result<std::string> target = detail::expand_path("/series/{series_ticker}", {series_ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("include_volume", params.include_volume);
	Result<GetSeriesResponse> response = detail::decode<GetSeriesResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_series"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->series);
}

Result<std::vector<Series>> KalshiClient::get_series_list(const GetSeriesListParams& params) {
	detail::Query query(std::string{"/series"});
	query.add("category", params.category);
	query.add("tags", params.tags);
	query.add("include_product_metadata", params.include_product_metadata);
	query.add("include_volume", params.include_volume);
	query.add("min_updated_ts", params.min_updated_ts);
	Result<GetSeriesListResponse> response = detail::decode<GetSeriesListResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_series_list"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->series);
}

Result<GetMarketsResponse> KalshiClient::get_markets(const GetMarketsParams& params) {
	detail::Query query(std::string{"/markets"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("event_ticker", params.event_ticker);
	query.add("series_ticker", params.series_ticker);
	query.add("min_created_ts", params.min_created_ts);
	query.add("max_created_ts", params.max_created_ts);
	query.add("min_updated_ts", params.min_updated_ts);
	query.add("max_updated_ts", params.max_updated_ts);
	query.add("max_close_ts", params.max_close_ts);
	query.add("min_close_ts", params.min_close_ts);
	query.add("min_settled_ts", params.min_settled_ts);
	query.add("max_settled_ts", params.max_settled_ts);
	query.add("status", params.status);
	query.add("tickers", params.tickers);
	query.add("mve_filter", params.mve_filter);
	return detail::decode<GetMarketsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_markets"));
}

Result<Market> KalshiClient::get_market(std::string_view ticker) {
	Result<std::string> target = detail::expand_path("/markets/{ticker}", {ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetMarketResponse> response =
		detail::decode<GetMarketResponse>(impl_->send(HttpMethod::GET, *target, {}, "get_market"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->market);
}

Result<std::vector<MarketCandlesticksResponse>>
KalshiClient::batch_get_market_candlesticks(const BatchGetMarketCandlesticksParams& params) {
	detail::Query query(std::string{"/markets/candlesticks"});
	query.add("market_tickers", params.market_tickers);
	query.add("start_ts", params.start_ts);
	query.add("end_ts", params.end_ts);
	query.add("period_interval", params.period_interval);
	query.add("include_latest_before_start", params.include_latest_before_start);
	Result<BatchGetMarketCandlesticksResponse> response =
		detail::decode<BatchGetMarketCandlesticksResponse>(impl_->send(
			HttpMethod::GET, std::move(query).str(), {}, "batch_get_market_candlesticks"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->markets);
}

} // namespace kalshi
