// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<Milestone> KalshiClient::get_milestone(std::string_view milestone_id) {
	Result<std::string> target = detail::expand_path("/milestones/{milestone_id}", {milestone_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetMilestoneResponse> response = detail::decode<GetMilestoneResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_milestone"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->milestone);
}

Result<GetMilestonesResponse> KalshiClient::get_milestones(const GetMilestonesParams& params) {
	detail::Query query(std::string{"/milestones"});
	query.add("limit", params.limit);
	query.add("minimum_start_date", params.minimum_start_date);
	query.add("category", params.category);
	query.add("competition", params.competition);
	query.add("source_id", params.source_id);
	query.add("type", params.type);
	query.add("related_event_ticker", params.related_event_ticker);
	query.add("cursor", params.cursor);
	query.add("min_updated_ts", params.min_updated_ts);
	return detail::decode<GetMilestonesResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_milestones"));
}

} // namespace kalshi
