// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<MultivariateEventCollection>
KalshiClient::get_multivariate_event_collection(std::string_view collection_ticker) {
	Result<std::string> target = detail::expand_path(
		"/multivariate_event_collections/{collection_ticker}", {collection_ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetMultivariateEventCollectionResponse> response =
		detail::decode<GetMultivariateEventCollectionResponse>(
			impl_->send(HttpMethod::GET, *target, {}, "get_multivariate_event_collection"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->multivariate_contract);
}

Result<CreateMarketInMultivariateEventCollectionResponse>
KalshiClient::create_market_in_multivariate_event_collection(
	std::string_view collection_ticker,
	const CreateMarketInMultivariateEventCollectionRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<std::string> target = detail::expand_path(
		"/multivariate_event_collections/{collection_ticker}", {collection_ticker});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	return detail::decode<CreateMarketInMultivariateEventCollectionResponse>(
		impl_->send(HttpMethod::POST, *target, detail::encode(body),
					"create_market_in_multivariate_event_collection"));
}

Result<GetMultivariateEventCollectionsResponse> KalshiClient::get_multivariate_event_collections(
	const GetMultivariateEventCollectionsParams& params) {
	detail::Query query(std::string{"/multivariate_event_collections"});
	query.add("status", params.status);
	query.add("associated_event_ticker", params.associated_event_ticker);
	query.add("series_ticker", params.series_ticker);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetMultivariateEventCollectionsResponse>(impl_->send(
		HttpMethod::GET, std::move(query).str(), {}, "get_multivariate_event_collections"));
}

} // namespace kalshi
