// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<std::optional<std::vector<OrderGroup>>>
KalshiClient::get_order_groups(const GetOrderGroupsParams& params) {
	detail::Query query(std::string{"/portfolio/order_groups"});
	query.add("subaccount", params.subaccount);
	Result<GetOrderGroupsResponse> response = detail::decode<GetOrderGroupsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_order_groups"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->order_groups);
}

Result<CreateOrderGroupResponse>
KalshiClient::create_order_group(const CreateOrderGroupRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	return detail::decode<CreateOrderGroupResponse>(
		impl_->send(HttpMethod::POST, std::string{"/portfolio/order_groups/create"},
					detail::encode(body), "create_order_group"));
}

Result<GetOrderGroupResponse> KalshiClient::get_order_group(std::string_view order_group_id,
															const GetOrderGroupParams& params) {
	Result<std::string> target =
		detail::expand_path("/portfolio/order_groups/{order_group_id}", {order_group_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	return detail::decode<GetOrderGroupResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_order_group"));
}

Result<void> KalshiClient::delete_order_group(std::string_view order_group_id,
											  const DeleteOrderGroupParams& params) {
	Result<std::string> target =
		detail::expand_path("/portfolio/order_groups/{order_group_id}", {order_group_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::expect_success(
		impl_->send(HttpMethod::DEL, std::move(query).str(), {}, "delete_order_group"));
}

Result<void> KalshiClient::reset_order_group(std::string_view order_group_id,
											 const ResetOrderGroupParams& params) {
	Result<std::string> target =
		detail::expand_path("/portfolio/order_groups/{order_group_id}/reset", {order_group_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::expect_success(impl_->send(HttpMethod::PUT, std::move(query).str(),
											  std::string{"{}"}, "reset_order_group"));
}

Result<void> KalshiClient::trigger_order_group(std::string_view order_group_id,
											   const TriggerOrderGroupParams& params) {
	Result<std::string> target =
		detail::expand_path("/portfolio/order_groups/{order_group_id}/trigger", {order_group_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::expect_success(impl_->send(HttpMethod::PUT, std::move(query).str(),
											  std::string{"{}"}, "trigger_order_group"));
}

Result<void> KalshiClient::update_order_group_limit(std::string_view order_group_id,
													const UpdateOrderGroupLimitRequest& body,
													const UpdateOrderGroupLimitParams& params) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<std::string> target =
		detail::expand_path("/portfolio/order_groups/{order_group_id}/limit", {order_group_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::expect_success(impl_->send(HttpMethod::PUT, std::move(query).str(),
											  detail::encode(body), "update_order_group_limit"));
}

} // namespace kalshi
