// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetOrdersResponse> KalshiClient::get_orders(const GetOrdersParams& params) {
	detail::Query query(std::string{"/portfolio/orders"});
	query.add("ticker", params.ticker);
	query.add("event_ticker", params.event_ticker);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("status", params.status);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::decode<GetOrdersResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_orders"));
}

Result<Order> KalshiClient::get_order(std::string_view order_id) {
	Result<std::string> target = detail::expand_path("/portfolio/orders/{order_id}", {order_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetOrderResponse> response =
		detail::decode<GetOrderResponse>(impl_->send(HttpMethod::GET, *target, {}, "get_order"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->order);
}

Result<std::vector<OrderQueuePosition>>
KalshiClient::get_order_queue_positions(const GetOrderQueuePositionsParams& params) {
	detail::Query query(std::string{"/portfolio/orders/queue_positions"});
	query.add("market_tickers", params.market_tickers);
	query.add("event_ticker", params.event_ticker);
	query.add("subaccount", params.subaccount);
	Result<GetOrderQueuePositionsResponse> response =
		detail::decode<GetOrderQueuePositionsResponse>(
			impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_order_queue_positions"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->queue_positions);
}

Result<FixedPointCount> KalshiClient::get_order_queue_position(std::string_view order_id) {
	Result<std::string> target =
		detail::expand_path("/portfolio/orders/{order_id}/queue_position", {order_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetOrderQueuePositionResponse> response = detail::decode<GetOrderQueuePositionResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_order_queue_position"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->queue_position_fp);
}

Result<CreateOrderV2Response> KalshiClient::create_order(const CreateOrderV2Request& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	return detail::decode<CreateOrderV2Response>(
		impl_->send(HttpMethod::POST, std::string{"/portfolio/events/orders"}, detail::encode(body),
					"create_order"));
}

Result<void> KalshiClient::cancel_all_orders(const CancelAllOrdersParams& params) {
	detail::Query query(std::string{"/portfolio/events/orders"});
	query.add("subaccount", params.subaccount);
	return detail::expect_success(
		impl_->send(HttpMethod::DEL, std::move(query).str(), {}, "cancel_all_orders"));
}

Result<std::vector<BatchCreateOrdersV2ResponseOrdersItem>>
KalshiClient::batch_create_orders(const BatchCreateOrdersV2Request& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<BatchCreateOrdersV2Response> response = detail::decode<BatchCreateOrdersV2Response>(
		impl_->send(HttpMethod::POST, std::string{"/portfolio/events/orders/batched"},
					detail::encode(body), "batch_create_orders"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->orders);
}

Result<std::vector<BatchCancelOrdersV2ResponseOrdersItem>>
KalshiClient::batch_cancel_orders(const BatchCancelOrdersV2Request& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<BatchCancelOrdersV2Response> response = detail::decode<BatchCancelOrdersV2Response>(
		impl_->send(HttpMethod::DEL, std::string{"/portfolio/events/orders/batched"},
					detail::encode(body), "batch_cancel_orders"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->orders);
}

Result<CancelOrderV2Response> KalshiClient::cancel_order(std::string_view order_id,
														 const CancelOrderParams& params) {
	Result<std::string> target =
		detail::expand_path("/portfolio/events/orders/{order_id}", {order_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	query.add("market_ticker", params.market_ticker);
	return detail::decode<CancelOrderV2Response>(
		impl_->send(HttpMethod::DEL, std::move(query).str(), {}, "cancel_order"));
}

Result<AmendOrderV2Response> KalshiClient::amend_order(std::string_view order_id,
													   const AmendOrderV2Request& body,
													   const AmendOrderParams& params) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<std::string> target =
		detail::expand_path("/portfolio/events/orders/{order_id}/amend", {order_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	return detail::decode<AmendOrderV2Response>(
		impl_->send(HttpMethod::POST, std::move(query).str(), detail::encode(body), "amend_order"));
}

Result<DecreaseOrderV2Response> KalshiClient::decrease_order(std::string_view order_id,
															 const DecreaseOrderV2Request& body,
															 const DecreaseOrderParams& params) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<std::string> target =
		detail::expand_path("/portfolio/events/orders/{order_id}/decrease", {order_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	detail::Query query(*target);
	query.add("subaccount", params.subaccount);
	return detail::decode<DecreaseOrderV2Response>(impl_->send(
		HttpMethod::POST, std::move(query).str(), detail::encode(body), "decrease_order"));
}

} // namespace kalshi
