// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetBalanceResponse> KalshiClient::get_balance(const GetBalanceParams& params) {
	detail::Query query(std::string{"/portfolio/balance"});
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::decode<GetBalanceResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_balance"));
}

Result<std::string>
KalshiClient::intra_exchange_instance_transfer(const IntraExchangeInstanceTransferRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	Result<IntraExchangeInstanceTransferResponse> response =
		detail::decode<IntraExchangeInstanceTransferResponse>(impl_->send(
			HttpMethod::POST, std::string{"/portfolio/intra_exchange_instance_transfer"},
			detail::encode(body), "intra_exchange_instance_transfer"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->transfer_id);
}

Result<GetIntraExchangeInstanceTransfersResponse>
KalshiClient::get_intra_exchange_instance_transfers(
	const GetIntraExchangeInstanceTransfersParams& params) {
	detail::Query query(std::string{"/portfolio/intra_exchange_instance_transfers"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetIntraExchangeInstanceTransfersResponse>(impl_->send(
		HttpMethod::GET, std::move(query).str(), {}, "get_intra_exchange_instance_transfers"));
}

Result<IntraExchangeInstanceTransfer>
KalshiClient::get_intra_exchange_instance_transfer(std::string_view transfer_id) {
	Result<std::string> target = detail::expand_path(
		"/portfolio/intra_exchange_instance_transfers/{transfer_id}", {transfer_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetIntraExchangeInstanceTransferResponse> response =
		detail::decode<GetIntraExchangeInstanceTransferResponse>(
			impl_->send(HttpMethod::GET, *target, {}, "get_intra_exchange_instance_transfer"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->transfer);
}

Result<std::int64_t> KalshiClient::create_subaccount(const CreateSubaccountRequest& body) {
	Result<CreateSubaccountResponse> response = detail::decode<CreateSubaccountResponse>(
		impl_->send(HttpMethod::POST, std::string{"/portfolio/subaccounts"}, detail::encode(body),
					"create_subaccount"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return response->subaccount_number;
}

Result<void> KalshiClient::apply_subaccount_transfer(const ApplySubaccountTransferRequest& body) {
	if (Result<void> valid = detail::validate(body); !valid) {
		return std::unexpected(std::move(valid.error()));
	}
	return detail::expect_success(impl_->send(HttpMethod::POST,
											  std::string{"/portfolio/subaccounts/transfer"},
											  detail::encode(body), "apply_subaccount_transfer"));
}

Result<std::vector<SubaccountBalance>> KalshiClient::get_subaccount_balances() {
	Result<GetSubaccountBalancesResponse> response = detail::decode<GetSubaccountBalancesResponse>(
		impl_->send(HttpMethod::GET, std::string{"/portfolio/subaccounts/balances"}, {},
					"get_subaccount_balances"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->subaccount_balances);
}

Result<GetSubaccountTransfersResponse>
KalshiClient::get_subaccount_transfers(const GetSubaccountTransfersParams& params) {
	detail::Query query(std::string{"/portfolio/subaccounts/transfers"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetSubaccountTransfersResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_subaccount_transfers"));
}

Result<std::vector<SubaccountNettingConfig>> KalshiClient::get_subaccount_netting() {
	Result<GetSubaccountNettingResponse> response = detail::decode<GetSubaccountNettingResponse>(
		impl_->send(HttpMethod::GET, std::string{"/portfolio/subaccounts/netting"}, {},
					"get_subaccount_netting"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->netting_configs);
}

Result<void> KalshiClient::update_subaccount_netting(const UpdateSubaccountNettingRequest& body) {
	return detail::expect_success(impl_->send(HttpMethod::PUT,
											  std::string{"/portfolio/subaccounts/netting"},
											  detail::encode(body), "update_subaccount_netting"));
}

Result<GetPositionsResponse> KalshiClient::get_positions(const GetPositionsParams& params) {
	detail::Query query(std::string{"/portfolio/positions"});
	query.add("cursor", params.cursor);
	query.add("limit", params.limit);
	query.add("count_filter", params.count_filter);
	query.add("ticker", params.ticker);
	query.add("event_ticker", params.event_ticker);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::decode<GetPositionsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_positions"));
}

Result<GetSettlementsResponse> KalshiClient::get_settlements(const GetSettlementsParams& params) {
	detail::Query query(std::string{"/portfolio/settlements"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("ticker", params.ticker);
	query.add("event_ticker", params.event_ticker);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("subaccount", params.subaccount);
	return detail::decode<GetSettlementsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_settlements"));
}

Result<GetDepositsResponse> KalshiClient::get_deposits(const GetDepositsParams& params) {
	detail::Query query(std::string{"/portfolio/deposits"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetDepositsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_deposits"));
}

Result<GetWithdrawalsResponse> KalshiClient::get_withdrawals(const GetWithdrawalsParams& params) {
	detail::Query query(std::string{"/portfolio/withdrawals"});
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	return detail::decode<GetWithdrawalsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_withdrawals"));
}

Result<GetPortfolioRestingOrderTotalValueResponse>
KalshiClient::get_portfolio_resting_order_total_value() {
	return detail::decode<GetPortfolioRestingOrderTotalValueResponse>(
		impl_->send(HttpMethod::GET, std::string{"/portfolio/summary/total_resting_order_value"},
					{}, "get_portfolio_resting_order_total_value"));
}

Result<GetFillsResponse> KalshiClient::get_fills(const GetFillsParams& params) {
	detail::Query query(std::string{"/portfolio/fills"});
	query.add("ticker", params.ticker);
	query.add("order_id", params.order_id);
	query.add("min_ts", params.min_ts);
	query.add("max_ts", params.max_ts);
	query.add("limit", params.limit);
	query.add("cursor", params.cursor);
	query.add("subaccount", params.subaccount);
	query.add("exchange_index", params.exchange_index);
	return detail::decode<GetFillsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_fills"));
}

Result<GetTargetBalanceAllocationResponse> KalshiClient::get_target_balance_allocation() {
	return detail::decode<GetTargetBalanceAllocationResponse>(
		impl_->send(HttpMethod::GET, std::string{"/portfolio/target_balance_allocation"}, {},
					"get_target_balance_allocation"));
}

Result<void>
KalshiClient::set_target_balance_allocation(const SetTargetBalanceAllocationRequest& body) {
	return detail::expect_success(
		impl_->send(HttpMethod::POST, std::string{"/portfolio/target_balance_allocation"},
					detail::encode(body), "set_target_balance_allocation"));
}

} // namespace kalshi
