// Generated by tools/codegen/generate.py from spec/openapi.yaml. Do not edit.
#include "kalshi/api.hpp"

#include "../support.hpp"
#include "../validate.hpp"

namespace kalshi {

Result<GetStructuredTargetsResponse>
KalshiClient::get_structured_targets(const GetStructuredTargetsParams& params) {
	detail::Query query(std::string{"/structured_targets"});
	query.add("ids", params.ids);
	query.add("type", params.type);
	query.add("competition", params.competition);
	query.add("page_size", params.page_size);
	query.add("cursor", params.cursor);
	return detail::decode<GetStructuredTargetsResponse>(
		impl_->send(HttpMethod::GET, std::move(query).str(), {}, "get_structured_targets"));
}

Result<std::optional<StructuredTarget>>
KalshiClient::get_structured_target(std::string_view structured_target_id) {
	Result<std::string> target =
		detail::expand_path("/structured_targets/{structured_target_id}", {structured_target_id});
	if (!target) {
		return std::unexpected(std::move(target.error()));
	}
	Result<GetStructuredTargetResponse> response = detail::decode<GetStructuredTargetResponse>(
		impl_->send(HttpMethod::GET, *target, {}, "get_structured_target"));
	if (!response) {
		return std::unexpected(std::move(response.error()));
	}
	return std::move(response->structured_target);
}

} // namespace kalshi
